### ISSUE TITLE
Text isn't vertically aligned correctly in the menu bar

### ISSUE THREAD

**Issue by tombonez** [matryer/xbar#105]
Hi,

As seen in the screenshot below, the text isn't vertically aligned correctly in the menu bar.

<img width="295" alt="screenshot 2016-01-05 10 18 07" src="https://cloud.githubusercontent.com/assets/967673/12139925/b1f74560-b45b-11e5-91ca-83066d1aaf53.png">

Cheers,
Tom :)

**Comment by herdani** [comment]
+1

**Comment by matryer** [comment]
Why on earth not?

**Comment by matryer** [comment]
If anyone wants to try and figure this out - please do. I had a look, and there's nothing (except that it's attributed text) that makes me think it would be.

I 100% agree we should fix it though.

**Comment by matryer** [comment]
@muhqu any ideas on this one?

**Comment by tombonez** [comment]
Changing the font to Helvetica fixes the issue. Jumping off my train in 5 minutes, so will try and submit a pull request when I get home (if you don't beat me to it).

**Comment by tombonez** [comment]
Just submitted a Pull Request to fix this #153 :)

**Comment by thomasbachem** [comment]
The fix from #153 sadly only works well with the default font size (14).

v1.4beta rendered `size=11` like this (vertically centered):

![bitbar-1-4b-size11](https://cloud.githubusercontent.com/assets/231538/12221365/602219be-b798-11e5-8a33-fe4b75ae70d2.png)

And now v1.4 looks like this:

![bitbar-1-4-size11](https://cloud.githubusercontent.com/assets/231538/12221366/69c07d3a-b798-11e5-92f3-5481762417e7.png)

**Comment by tombonez** [comment]
Ah, I wasn't aware of user specified font sizes (sorry) :(

I'll try and look into this again today :)

**Comment by matryer** [comment]
Is there a general way to solve this problem? @tombonez any ideas?

**Comment by Eraac** [comment]
just installed bitbar today (1.9.2), I gave create a simple plugin just write some number, no specific size or font, but text is not centered too :/

I have try v2, but same problem. Any solution ?

My plugin just display the current timestamp

**Comment by dmcinnes** [comment]
I'm still seeing this problem in 1.9.2:
![screen shot 2017-05-31 at 1 40 28 pm](https://cloud.githubusercontent.com/assets/16557/26653045/caf4209a-4606-11e7-84cc-b9c9a0d1b825.png)
Left is Bitbar with [World Clock](https://getbitbar.com/plugins/Time/worldclock.1s.sh) and right is the system clock in MacOS 10.12.5.

**Comment by oleander** [comment]
No fix atm. The problem is that no default font is set on the text which is required for items in the menu bar to look correct in OS X 10.11+.

**Comment by klamike** [comment]
Is there a fix for the vertical alignment issue?

**Comment by thomasbachem** [comment]
@oleander You mean BitBar just needs to specify a default font? That sounds like a rather easy fix for a quite annoying bug?

**Comment by marqpdx** [comment]
Where might that default font be set, if that is actually a fix? It does sound like it would be one or a few lines. Which lines, and where to put them is of course the question :)

**Comment by marqpdx** [comment]
OK, been looking at the code. It seems one sets the font for the menu items, but it seems in our case, the actual menu itself is too big (as you can see w/ the UTC time vs the battery % to the right).

The menu items themselves, though, seem to be proper size.

Do we need to set the default font for all menu items, will that take care of the Menu font itself?

Thanks,
m


![screen shot 2018-09-01 at 8 37 14 am](https://user-images.githubusercontent.com/1056353/44947483-6edc6b80-adc2-11e8-9ac1-605f7cd7f568.png)
![screen shot 2018-09-01 at 8 36 34 am](https://user-images.githubusercontent.com/1056353/44947485-6f750200-adc2-11e8-87b3-c141b82b8c8e.png)

**Comment by inbalboa** [comment]
The repo https://github.com/guillaumewuip/bitbar from https://github.com/matryer/bitbar/issues/513#issue-462289581 is unavailable. So there is still no solution.

**Comment by burhanashraf** [comment]
> The repo https://github.com/guillaumewuip/bitbar from [#513 (comment)](https://github.com/matryer/bitbar/issues/513#issue-462289581) is unavailable. So there is still no solution.

Change this file: 
https://github.com/matryer/bitbar/pull/496/files
then rebuild using [513](https://github.com/matryer/bitbar/issues/513)

Although, [513](https://github.com/matryer/bitbar/issues/513) already includes a modified bitbar with the text alignment fix incase you missed it.

[Self sign modified bitbar](https://stackoverflow.com/questions/27474751/how-can-i-codesign-an-app-without-being-in-the-mac-developer-program)
[If you get an error when signing](https://stackoverflow.com/questions/39652867/code-sign-error-in-macos-high-sierra-xcode-resource-fork-finder-information)
