### ISSUE TITLE
Evolve plugin management

### ISSUE THREAD

**Issue by matryer** [matryer/xbar#112]
As plugins grow, we will consider a better solution for plugin management that:
- bundle supporting files with a plugin
- makes plugins more visual (images)
- makes them searchable
- makes it easy to activate/deactivate them
- maybe has its own UI
- puts plugins in their own repo
### Considerations
- would using an existing platform (like brew) solve this?

**Comment by daturkel** [comment]
Stop-gap plugin update solution is just to accept and use PR #114 and pull upstream changes to plugin folder regularly.

**Comment by jcaille** [comment]
Awesome !
Now we just need some way of maintaining configuration (see #88) in between updates so that updates are mostly seamless for users.

Afterward, we can start to think about automating the behaviour of the `enabled` folder. In #103 I proposed a solution to automate plugin management without a heavy GUI.

> Bitbar could managed installed plugins by itself. For example :
> By defaults, Bitbar looks for plugins in an `ApplicationData/Bitbar/Plugins` folder. This folder can be changed.
> Drag and dropping a script on the Bitbar status menu item symlinks this file to the plugin folder (thus "installing" it in Bitbar)
> Additional options (Remove plugin, Set refresh time, ...) should be added to the plugin dropdown. Those options either remove or modify the name of the symlinked executable file (thus keeping the legacy API)

**Comment by seripap** [comment]
How about how [packagecontrol.io](http://packagecontrol.io) or [npmjs.com](http://npmjs.com) works? Would like a simple json manifest with each plugins

**Comment by matryer** [comment]
Another option is to package plugins with a `.bitbar` extension which, when executed, 'installs' the plugin. Might be a bit too fancy.

**Comment by matryer** [comment]
NOTE: Plugins now live in a different repo: https://github.com/matryer/bitbar-plugins

**Comment by flxfxp** [comment]
Thanks @matryer, excellent.
Let me know if you need help managing/approving plugins.

**Comment by LaurentFough** [comment]
I've actually incorporated Sparkle into the project, and have compiled successfully.
I need to test updating by appcast url, and also updated package signing.
- The latter being something that we'd need to thread carefully with, as it appears as though if not done properly it breaks app delivery.

**Comment by matryer** [comment]
For anybody interested in a plugin browser, please see https://github.com/matryer/bitbar-plugins/issues/53

**Comment by shepazon** [comment]
From my perspective, the biggest issue is the lack of ability to bundle support files into a plugin. That limits the capabilities of plugins substantially.

**Comment by matryer** [comment]
Hey Eric, What kinds of support files are you thinking about?
