### ISSUE TITLE
Add a way to tell BitBar to skip the refresh and keep the last state

### ISSUE THREAD

**Issue by thomasbachem** [matryer/xbar#133]
It would be great if there was a way to tell BitBar that nothing has changed since the last refresh and the last output/state should be kept.

One could solve this with caching in the plugin itself, but that's more complicated than simply returning something like `| stale=true`.

**Comment by thomasbachem** [comment]
Specific use case: I don't need to retrieve my stocks data between 10 pm and 8 am.

**Comment by matryer** [comment]
I wonder if you could store the value somewhere and manage this within the plugin?

**Comment by thomasbachem** [comment]
Yeah, that's what I do now. Can be solved in user land, so not necessarily an important feature for BitBar itself.

**Comment by daturkel** [comment]
Would preventing redraw on the BitBar end of things potentially reduce resource usage?
