### ISSUE TITLE
Feature: ability to bring up an in-app console for monitoring plugin output

### ISSUE THREAD

**Issue by LaurentFough** [matryer/xbar#152]
At the moment, I know you can log to console, and also of course plugins written incorrectly do return errors, albeit within the menubar itself.

I envision a feature where we can open a BitBar specific log window with a history of output of the app and all enabled plugins.

An extension of this, for proper implementation would be for plugins to specify if they want to log to console, to the app or not all.

Thoughts?

**Comment by matryer** [comment]
Plugins can already log (they're free to write to files etc.) on their own, is this not enough?

**Comment by shepazon** [comment]
The problem is that if you have a plugin that doles out work to other scripts as it works, the output doesn't make it to stderr reliably (at least for me). Having a way to ensure that all output to stderr goes to a single log file would be excellent.
