### ISSUE TITLE
Ability to move/rearrange plugins separately

### ISSUE THREAD

**Issue by ffittschen** [matryer/xbar#158]
It would be great if one could cmd+drag the plugins separately e.g. to move the wifi name plugin next to the system wifi menu icon and the battery cycles plugin next to the system battery menu icon

This would also work great with Bartender, because then it would be possible to just move specific plugins into the bartender bar and leave others in the main menu bar

**Comment by dgattey** [comment]
This is possible right now on macOS High Sierra for me
