### ISSUE TITLE
$BitBarDarkMode doesn't work on v1.4

### ISSUE THREAD

**Issue by saneef** [matryer/xbar#160]
I have tried to use $BitBarDarkMode environment variable based on [tutorial](https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/is_darkmode.sh) in bitbar v1.4 and it's not working for me.

**Comment by matryer** [comment]
What did you try?

**Comment by saneef** [comment]
@matryer My Bad. It works if I restart the BitBar.app after switching between the light and dark mode on OSX.

When I tried, $BitBarDarkMode was coming empty even after refreshing the BitBar.app.

**Comment by matryer** [comment]
hmm… maybe we should notice the change and Refresh the plugins?

**Comment by jm-softevol** [comment]
Same for me. I was trying to use this variable 'on fly' as I'm using f.lux which changes Dark/Light mode automatically during the day, so I was need to change text colors if mode is Dark, but it constantly gives me 1, if it was started during the Dark mode was on.
Can this variable be refreshed each time at least some of scripts got refreshed?

**Comment by wrtsprt** [comment]
Can we reopen this? I'd love to have that work. Same problem as described above. Was trying to work around using `bitbar://refreshPlugin`, but that doesn't work either.

**Comment by matryer** [comment]
@wrtsprt Would you like to try and fix this?

**Comment by wrtsprt** [comment]
Don't have any experience with macOS development, iOS only, but I'd like to give it a shot. Is there documentation on how to get all those libs that are missing when I try to build?

**Comment by wrtsprt** [comment]
Responding to changes of mode in Mojave: https://indiestack.com/2018/10/supporting-dark-mode-responding-to-change/
