### ISSUE TITLE
Param parsing for `terminal=false` is not optimal

### ISSUE THREAD

**Issue by tresni** [matryer/xbar#165]
Per #162 (and specifically @matryer's comments), the current method of specifying arguments for `terminal=false` is not optimal.  It is limited to 5 arguments and requires the user to break up their command.

**Comment by jcaille** [comment]
Hey,

A few days ago, #50 was merged in and allows to pass bash command verbatim by enclosing them in single or double quotes. This should allow us to avoid the whole `param` thing

**Comment by tresni** [comment]
Actually this behavior is post your change as far as I can tell.  Essentially we would need to re-parse `bash=` to separate it into command and arguments to pass it to NSTask (from what I can tell/have read)

**Comment by matryer** [comment]
Can you two agree on what needs to be done here?

**Comment by matryer** [comment]
@tresni are you happy with the way params work now?

**Comment by tresni** [comment]
@matryer I've never had a problem with.  It's just that using `terminal=false` (ie NSTask) basically requires that you use `param*=` to pass arguments.  This is limited to 5 params being passable.  I'm not sure there is a great fix for this regardless of anything else.

**Comment by tresni** [comment]
Actually just reviewed the code from #50.  You could choose *not* to use `params*=` by using `args=` but the double underscore separator seems weird.  I mean it works so...  Little odd that wipespace trimming isn't applied to it, and makes the definition look weird (to me)

```
echo "Upgrade all | bash=/usr/local/bin/brew param1=upgrade param2=--all terminal=false refresh=true"
```
vs
```
echo "Upgrade all | bash=/usr/local/bin/brew args=upgrade__--all terminal=false refresh=true"
```

**Comment by jeffbeadles** [comment]
I've been trying to isolate a BitBar crash that I'm seeing, and I'm pretty sure that it is related to this thread.

I'm using v1.5beta, with the following stripped-down plug-in;

#!/bin/sh
# Test case for BitBar Crash
# By: Jeff Beadles
#
# The "-param1 lines work fine.  The -quoted lines crash bitbar

ARG=${1-"No argument given"}
# Ignore the argument, it doesn't need to do anything.

echo "crashtest | color=black"
echo "---"

echo "Enable-param1 | terminal=false bash=$0 param1=enable"
echo "Disable-param1 | terminal=false bash=$0 param1=disable"

echo "Enable-quoted | terminal=false bash=\"$0 enable\""
echo "Disable-quoted | terminal=false bash=\"$0 disable\""

exit 0

If you select the -param1 menu items, all is good.  If you select either of the -quoted menu options, it crashes BitBar.

If you remove the terminal=false, it's fine.

**Comment by tresni** [comment]
I wonder if this is related to my change in #181 as that's the only recent change to how we handle `terminal=false`.  I've definitely done `bash=\"$0 enable\"` style before.  It won't work with `terminal=false` but it should fail silently with a message in Console.app about not being able to launch the executable.

**Comment by tresni** [comment]
Okay the crash is definitely due to #181; it doesn't check to see if `params` is initialized.  However #181 didn't introduce the issue with `params`.  Somehow `menuItem.representedObject` is returning `nil`.  So I can fix the crash, but definitely looks like something change with param parsing itself.

**Comment by iosdeveloper** [comment]
@tresni Are we fine with the current implementation of `args=` (why is it not documented?) or does this still need work?

**Comment by raszi** [comment]
This `args` hack only works when terminal is disabled, which is sad because if you have terminal enabled then you stuck with 5 parameters only.

Are you planning to fix this issue or at least passing all the `params` to the bash and terminal up to `getconf ARG_MAX`?

**Comment by frakman1** [comment]
Will the `args` feature ever be documented?
