### ISSUE TITLE
Change terminal app

### ISSUE THREAD

**Issue by ElRochito** [matryer/xbar#175]
Hello,

It's possible to open another app instead of Terminal such as iTerm ?

Thansk

**Comment by tresni** [comment]
Not currently, I actually wanted the same thing and am working on some code that would launch iTerm instead of Terminal.  The AppleScript is very different for Terminal but it's doable.

**Comment by julio6114** [comment]
It's possible for me to create a pull request.
I would like tu purpose you a solution
Thanks

**Comment by julio6114** [comment]
It's ok :)
See my pull request https://github.com/matryer/bitbar/pull/179

**Comment by freeyland** [comment]
I also would like this functionality. ANy update?

**Comment by Kamik423** [comment]
Bump?

**Comment by gingerbeardman** [comment]
What happens if you make iTerm default using its own interface?

https://superuser.com/a/870487

![](https://i.stack.imgur.com/Y2UJj.png)

**Comment by jamesratcliffe** [comment]
This just make iTerm the default handler for certain types of files (e.g. .command).

This doesn't apply to Bitbar because it uses Applescript to open Terminal and tell it to run commands.

**Comment by AMD-NICK** [comment]
bump

**Comment by dlibanori** [comment]
bump

**Comment by kashyappatel1988** [comment]
This works for me 
```
 bash="/usr/bin/open" param1="-a" param2 ="iterm" param3="ssh://"
```
