### ISSUE TITLE
Multiline cycle times

### ISSUE THREAD

**Issue by SteveEdson** [matryer/xbar#191]
Is there a set time between multilines cycling through to the next one on the status bar?

If so, is it possible to change the behaviour to something like _plugin refresh time_ / _number of lines_, with a sensible minimum and maximum value of e.g. 1s / 10s. This would ensure that lines doesn't change too quickly, and aren't displayed for too long.

E.g. 12s refresh time, 4 lines = 3 second cycle time

This way, plugins with 5s refresh times can still show all the information from multiple lines.

Thanks

**Comment by taylorzane** [comment]
The current interval is 5 seconds per line. (`_cycleLinesIntervalSeconds` see: [Plugin.m#L19](/matryer/bitbar/blob/master/App/BitBar/Plugin.m#L19))

Currently this is not a configurable parameter.

If you think you can knock this out, a pull request is certainly welcome!

**Comment by frakman1** [comment]
Once implementation idea would be to have this parameter read from the metadata of the script (if included)
