### ISSUE TITLE
Use time instead of a refresh rate

### ISSUE THREAD

**Issue by h0d** [matryer/xbar#200]
Would it be possible to use an absolute time rather than a refresh rate?

E.g. having _myplugin.00:00.sh_ rather than _myplugin.10s.sh_ so that a date-based plugin only refreshes once a day.

**Comment by matryer** [comment]
Nice idea. I think BitBar's scheduling needs evolving in order to support this. Right now, it's not possible. Although you could set the refresh rate to 1 minute and just do a quick time check in your script as a workaround?

**Comment by gondalez** [comment]
👍 + it would be handy to allow recurring absolute times also.

Example use case for me is my solar inverter updates every 15 minutes on a schedule: 08:00 08:15 08:30 and so on. So I would like to refresh slightly after that time.

Could allowing a cron expression work? (perhaps within the plugin file)
In my case `01,16,31,46 * * * *` would do nicely.

Something like this.

Filename:
```
myplugin.custom.sh
```

Contents:
```
#!/usr/bin/python
...
<bitbar.custom_schedule>01,16,31,46 * * * *</bitbar.custom_schedule>
...
```

**Comment by matryer** [comment]
I like these ideas.

>
