### ISSUE TITLE
ignore editor backup/dribble files in plugins directory, to avoid duplicate output

### ISSUE THREAD

**Issue by warner** [matryer/xbar#214]
I edited one of my plugins with emacs, which leaves backup files like `plugin.60m.sh~` lying around afterwards. Most programs have a list of suffixes to ignore, but apparently bitbar doesn't, because I saw the plugin's output appear twice on the menubar (once with the updated content, once with the old content from the backup file).

Debian's "run-parts" tool might be a useful model to follow: it only looks at names that consist entirely of ASCII upper+lowercase letters, digits, underscores, and hyphens.

thanks for the great tool!

**Comment by taylorzane** [comment]
While this doesn't solve the issue of BitBar running multiple instances, you can add this to your `.emacs` to move *all* temp files to your temporary directory. I've used this since I started using emacs and it's removed my frustrations with `.gitignore` rules and just random cruft files.

```lisp
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
            `((".*" ,temporary-file-directory t)))
```

**Comment by matryer** [comment]
Is the `~` suffix common enough to have BitBar explicitly ignore that?

**Comment by matryer** [comment]
BitBar does currently ignore files prefixed with a dot, so I'm not against having a list of things to ignore.

**Comment by taylorzane** [comment]
@matryer AFAIK, any file ending in `~` is a backup of a file that was edited by `emacs`, `vi`, `nano`, et. al. On that note, if we were to implement a ignore list, we'd probably also want to add `*.swp` to that list.
