### ISSUE TITLE
Bug? BitBar 1.5.1 (and below) doesn't remember menu bar position (Bartender installed)

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#241]
When resetting/refreshing the BitBar plugins, the BitBar instances reappear at the left end of the menulets in the menu bar. I don't know if this happens with all users or only those who (like me) have Bartender installed, but I've defined a specific position for BitBar in the menu bar with CMD-drag, and BitBar doesn't comply. I had noticed this behavior before, but since I'm currently only running semi-static scripts (update once a day), I didn't mind. Now, though, with v1.5.1 BitBar resets after wake from sleep, which means that every time my computer wakes, all BitBar instances move to the left, which is annoying. Other menulets do actually remember their user-defined position, or rather: Bartender assigns them the correct position, once they relaunch after quit. What could be the problem with BitBar? Is it maybe because BitBar doesn't actually quit, but only goes "invisible", when its instances are refreshed?

**Comment by matryer** [comment]
I think the 'moving' is caused by the tear-down and setup of new items. Ideally, it would reuse existing items, which wouldn't require new items to be added. This might go some way to fixing this problem.

**Comment by JayBrown** [comment]
Just found out that the command `/usr/bin/killall SystemUIServer` will reset the menu bar items to their correct location. So for the time being the workaround for me will be adding that line to my wake-up script.

**Comment by ataxexe** [comment]
I'm having the same issue here with BitBar v1.9.2. But even without Bartender active the behavior is the same.

Unfortunately, killing SystemUIServer isn't working for me. I need to manually reposition the item on menubar.

**Comment by tikkerei** [comment]
@gingerbeardman  An updates regarding this issue? Its really annoying :worried:

**Comment by matryer** [comment]
The project is seeking maintainers. If anybody is interested, please reach out to me.

**Comment by xilopaint** [comment]
Any news here?

**Comment by xilopaint** [comment]
Any news here? @gingerbeardman?

**Comment by nash8114** [comment]
On macOS 10.15.7 the trick with renaming does not work as expected. The order of the items in the top bar appears to be unrelated to the file name, but rather determined by inode number (right-most being the lowest inode). Every time I've refreshed the bitbar, scripts are displayed in inode order.

The inconsistent results (working for some people but not for others) can be explained by people using either symlinks or script files directly. When renaming a regular file, it does not get a new inode number. When renaming a symlink, a new inode is created.

A consistent way to set the order (tested with scripts that all have the same refresh rate) is to make symlinks to the script files in the correct order. Rightmost item symlink should be created first. If you prefer to use script files directly without linking, then use cp to copy each file in the correct order. Use `ls -1i | sort -n` to check whether the order is correct.
