### ISSUE TITLE
"Add to Bitbar" button on getbitbar.com does nothing when no plugin folder is set

### ISSUE THREAD

**Issue by matryer** [matryer/xbar#243]
Clicking "Add to BitBar" should (if there is no plugin folder set) popup an error box explaining that the user should set a plugin folder first.

**Comment by iosdeveloper** [comment]
Shouldn't you get a prompt to set the directory on first launch? After that it could only be unset programmatically.

**Comment by matryer** [comment]
You do but if you just close it, it never gets set. Edge case.

**Comment by vogonistic** [comment]
Can it be avoided by creating and using a default folder like `~/Library/Application Support/BitBar`?

**Comment by matryer** [comment]
I suppose if we do that - maybe we remove the ability to change the plugin folder altogether. Makes it simpler.

**Comment by vogonistic** [comment]
I can see the use of being able to change the folder for power users and developers, but I'm guessing most users won't care or write their own plugins. 

Maybe the path should be `~/Library/Application Support/BitBar/Enabled` and `~/Library/Application Support/BitBar` could be a clone of the plugin repo.

**Comment by iosdeveloper** [comment]
I don't think executable scripts in an arbitrary directory outside the app bundle is a good idea.

**Comment by matryer** [comment]
In which case, the solution becomes a pop-up asking the user to specify the plugin folder if one isn't set when the "Add to BitBar" button is clicked. Make sense?

**Comment by vogonistic** [comment]
What happens if they press cancel again? Maybe pressing cancel should give the user a message that BitBar can only run if you choose a plugin folder and then quit, restarting the cycle the next time.

**Comment by matryer** [comment]
Hmm, it’s a good point. Or we just popup a box saying “No plugin folder set” and let the user go and do it… then we could have a `BOOL ensurePluginFolderSet` method or something?

**Comment by vogonistic** [comment]
Or a bundled plugin saying "No plugin folder set" that gets removed when it's set. If the user tries to add a plugin before a path is set, they get a message explaining it's not configured yet and to try again after it's been configured.
