### ISSUE TITLE
Feature Request: Ability to add 'tooltip' text to any line

### ISSUE THREAD

**Issue by mm2270** [matryer/xbar#262]
Similar to how menu items behave when being truncated in the resulting menu per #131  , it would be great to be able to manually add a tooltip string to any menu line. Perhaps with a new flag, like `tooltip='some string'`, or `tip='some string'` but of course the tooltip text could be a variable dynamically generated within the plug-in script itself, and not necessarily hardcoded per line.
I could make use of this to tidy up some plug-ins I use. Rather than including too much information directly rendered in the menu, I can place the less important but still relevant info into a tooltip that only appears when hovered over. It could also be used to explain what the menu line is referencing for example.
I'm thinking since BitBar already supports automatic tooltips based on truncated lines, adding them in manually per line may also be possible in a future rev. The only issue I see with this is, what would get displayed in a case where a manual tooltip string was added, **and** the line gets truncated because of the default or set `length` attribute? Some decision would need to be made on what to show in the tooltip in such a case.
Thoughts?

**Comment by matryer** [comment]
Have you seen the 'alternate' option?

**Comment by mm2270** [comment]
@matryer Yes, I've seen the 'alternate' function, and I'm using it in my scripts. Thank you for adding that in!
But I see a difference between tooltips and alt text. The alternate function doesn't show the alt text unless the Opt key held down, whereas tooltips would display upon hovering over the line, so there's a small possible issue of discoverability. Also, tooltips would not replace the line above as alternate does today. I know I could code my script so the alt text would really be a concatenation of the original line + the new text, but that's extra work in the script, and again, the issue of needing to hold down the modifier key to see it is still there.

Lastly, depending on how much info you may want to display, the alternate option could still run into the menu width maximum and end up getting cut off anyway. I don't think the tooltip text would have this problem that I can see, but I don't know that for a fact.

Anyhow, thanks for considering it. I know this isn't anything high priority compared to other enhancements and fixes in the issues list, but I'd still love to see this eventually.

**Comment by matryer** [comment]
OK - let’s see if others want this too. The community decides priorities. :)

**Comment by ibutra** [comment]
I do see the different use cases for the tooltip and the alternate, but at the same time I wonder how many people are really hovering their mouse over a Statusbar Menu to see the tooltip? In addition adding every little feature kind of bloats the api for Plugins. 

In respect to programming this feature I believe it is trivial, so if you really need it @mm2270 I could program it for you quickly even if it won't be merged into the master branch.

**Comment by matryer** [comment]
I’ve never seen tooltips in a menu bar item? Anyone else?

**Comment by mm2270** [comment]
Well, if its non standard to have tooltips in menubar items, and it may in fact be, then I'll drop the request and this can be closed. Or, keep it open as a question, and if someone wants to code it they can.
In the end its really not a deal breaker, I just thought that since tooltips are already supported for any truncated menu items it wouldn't be a bad thing to add in for any menu item line. But by all means, if it might add bloat to the app, then let's forget it. :)

**Comment by matryer** [comment]
I'm totally open to it if there's enough demand. Also, BitBar is mainly used by developers, so some 'advanced' or non-standard behaviour can be tolerated :)

Let's leave this here for now and see what people think?

**Comment by JayBrown** [comment]
It may not be a pressing issue, but I would welcome tooltips. If you implement it, they should also work for hovering over the icon in the menu bar itself, not just for the items in the menu bar. Should also (especially) work for static items (greyed out), so that when you hover them, a tooltip appears, where you can put an info text etc., or even the output of a function.

**Comment by JayBrown** [comment]
I've already changed a script of mine to include tooltips later. The menu shows (among other things) values added by the user to a local database, and the tooltip will show the date and time when the value was added.

So I'm really looking forward to the tooltips feature. :)

**Comment by JayBrown** [comment]
PS: just found a tooltip in a menu bar item, namely in BitBar itself. :) When the text of a menu item is truncated, OS X automatically shows a tooltip with the full text. So tooltips in menu bar items are in fact standard, and we should use that functionality to our advantage.

**Comment by iosdeveloper** [comment]
@JayBrown We get it. By the way, you see a tooltip on truncated lines because we set it. It is no standard in any way and OS X does not do it automatically.

**Comment by JayBrown** [comment]
k

**Comment by frakman1** [comment]
**Please don't drop this feature request**. My script would **greatly** benefit from having such a feature. I currently have to add a submenu that explains what the menu item is or how it works and it looks pretty messy and confusing. It would be a lot cleaner if hovering over the menu item would show a tooltip with further instructions.
@ibutra Please let me know if you code up this feature in a separate branch. I can merge it into my code and test it out.
Thanks!

**Comment by matryer** [comment]
Ok :)

But did you look at the "option" key approach?

Mat

**Comment by frakman1** [comment]
Hi Mat. 

Thanks for writing back. Big fan of your work by the way.

I have indeed looked into the "option" key approach and have used it extensively in my plugin (replace a list of room names with old names) but only because I could place instructions to that effect at the bottom of the submenu like this:

![image](https://user-images.githubusercontent.com/5826484/28649327-15484916-7242-11e7-9b56-9a286b311efa.png)

Thank you and to the community for adding that feature. However, as others have mentioned, it's not really appropriate in some cases especially in the main menu where space is limited. I've also struggled to get alternate text to work with submenus because I'd have to repeat code under a submenu just because it has an alternate line version (I've read the issue related to this feature and submenus and understand its limitations)

**Comment by frakman1** [comment]
I just looked at the `@"checked"` feature in the beta branch and learned that it's not as hard as I thought. I easily added it with a few lines of code:

`Plugin.m` in `buildMenuItemWithParams` at the end of the function.

```Objective-C
  if (params[@"tooltip"]) {
    item.toolTip = params[@"tooltip"];
  }
```
I was able to activate it using code like this (python) in my plug-in:
```python
print "This is a menu item | tooltip='This is a Tooltip' "
```

It looks like this when I hover over the menu item:
![image](https://user-images.githubusercontent.com/5826484/28653754-55723432-725d-11e7-8f8b-b95ead15b978.png)


Incidentally, I also added an indentation feature using @indent using the same approach. This is handy for aligning images and strings in my menus. This is the code:

```Objective-C
  if (params[@"indent"]) {
    item.indentationLevel = [params[@"indent"] intValue];
  }
```
Use it with a call like this: `| indent=8`

**Comment by JayBrown** [comment]
First a question regarding the screengrab, how did you manage those neat tabs? Will they stay like that if the first column has e.g. "16.13.4646"? I've only managed to get real tab/column behavior with monospaced fonts (bash-based BitBar plugin scripts). And then, of course, there's still **[this problem](https://github.com/matryer/bitbar/issues/403)**.

At any rate, I second the programmable tooltip functionality. Sometimes you might want to give the user some additional information on a menu item (help, tutorial, explanation etc.), and as far as I can see, that would be the most convenient way.

On the other hand, you could also add a keyboard shortcut that calls a general help function and opens a floating help/tutorial window. The content of that window could also depend on the submenu the user was in when he used the keyboard shortcut. In addition to that, a simple "Help" menu item would also be cool, e.g. like `echo "Help | help=HelpText1`, `echo "Tutorial | help=HelpText2` etc.

**Comment by matryer** [comment]
OK I support this feature. Anyone want to make a PR?

**Comment by frakman1** [comment]
@JayBrown I must have got lucky because the first column is always in the X.X.XXX format so everything lines up. All I did was:
```python
print "-- 6.3.467\t\t\t Rear Window"
```
@matryer I can make a PR, but first, **what do you think about hastening the tooltip delay?** 
Should it be implemented at all? If so, should that be set in `applicationDidFinishLaunching` or should we let the user change it manually via a terminal command (`$ defaults write -g NSInitialToolTipDelay -int 50`) ?

**Comment by frakman1** [comment]
OK. I just created a PR with just the tooltip feature - https://github.com/matryer/bitbar/pull/431
This is my first ever PR so I hope it did it right! haha

**Comment by matryer** [comment]
Check https://travis-ci.org/matryer/bitbar/builds/258215748?utm_source=github_status&utm_medium=notification <https://travis-ci.org/matryer/bitbar/builds/258215748?utm_source=github_status&utm_medium=notification>

**Comment by frakman1** [comment]
I don't get it. It said it failed but there is no indication of an error in the logs except for the end:

![image](https://user-images.githubusercontent.com/5826484/28686709-231e4e58-72da-11e7-8d8d-969b079ab6f9.png)

I only added those [three lines](https://github.com/matryer/bitbar/pull/431/files) and nothing else. 

The file I changed appears to have built properly:

![image](https://user-images.githubusercontent.com/5826484/28687295-0cfd9262-72dc-11e7-8d06-5a2e284f2baf.png)

The build succeeds:

![image](https://user-images.githubusercontent.com/5826484/28687417-4c4cc190-72dc-11e7-9535-8bbb5520ac4f.png)

Is this "normal" ?

**Comment by frakman1** [comment]
OK. It looks like there is a problem with the signing. Who handles that part?

![image](https://user-images.githubusercontent.com/5826484/28699503-0e29a662-7318-11e7-852d-9d0758fc36e6.png)

**Comment by frakman1** [comment]
@matryer @iosdeveloper 
Does anyone have any idea what's going on with the pull request or how to proceed?

**Comment by matryer** [comment]
This needs some love. Sorry, been very busy. Will try and get to this next week.

**Comment by frakman1** [comment]
@matryer Any luck getting this fixed?

**Comment by Mikii67** [comment]
I would like to add my two cents by saying that I would love to see the "tooltip" option, especially for icons....
Thank you bitbar community......

**Comment by frakman1** [comment]
@matryer Are you maintaining this anymore?

**Comment by JayBrown** [comment]
I might have read somewhere that there's a plan for a complete rewrite in Swift, but I'm not sure if that has started yet.

**Comment by frakman1** [comment]
I meant for the purpose of accepting a pull request. There is some image signing step that is failing and needs maintenance.
