### ISSUE TITLE
get bitbar plugins up to par with istat menus

### ISSUE THREAD

**Issue by dimitrieh** [matryer/xbar#264]
I would love to get into bitbar! Use it as a replacement for istatmenus. Hoever it is not yet on par with it. For example the cpu meter should be a detailed mini graph with more information when hovering over it as seen in the screenshot. Download upload rates should be able to be displayed as in the screen shot double lines etc. Is this doable atm with bitbar? 

<img width="452" alt="screenshot 2016-03-09 11 49 26" src="https://cloud.githubusercontent.com/assets/429659/13635133/3535a758-e5fa-11e5-8dff-063a00369b38.png">

_copy of https://github.com/matryer/bitbar-plugins/issues/305_

**Comment by keithamus** [comment]
If you can write a script which generates base64 images, then you can use those images as icons with a newer version of bitbar. See #32, #257

**Comment by keithamus** [comment]
My understanding is that graphics are not currently possible inside the menu though - but I could be wrong.

**Comment by strages** [comment]
i have no idea how to do this myself.

for the base64 encoding: https://github.com/nicklockwood/Base64 or is it possible with imagemagick?

maybe someone is willing to take up this challenge!

**Comment by keithamus** [comment]
ImageMagick or similar libs can be used to generate the image data, and then you can output that data as base64. For example, [here is how you'd do it with python+pil](https://stackoverflow.com/questions/31826335/how-to-convert-pil-image-image-object-to-base64-string). If you are using shell scrips, you can simply pipe `convert` through to `base64`.

**Comment by iosdeveloper** [comment]
@keithamus https://github.com/matryer/bitbar-plugins/pull/290 has examples of images in the menu (see screenshot).

@strages You may use HTML plugins to display a graph: https://github.com/matryer/bitbar/issues/210#issuecomment-184145047

**Comment by iosdeveloper** [comment]
@strages The plugin @ganeshv just submitted appears to be pretty close to what you were looking for: https://github.com/matryer/bitbar-plugins/blob/master/System/mtop.5s.sh

**Comment by strages** [comment]
nice!
