### ISSUE TITLE
Suggestion: "width=" parameter for menus and submenus / GUI glitches

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#298]
It's not a pressing issue, but how about a width= parameter for menus and submenus? I know that you can set menu/submenu width by taking the longest line of echo text in a menu, comparing it to the longest alternate, and then adding the right amount of whitespace to the former while setting trim=false, but if you have a lot of alternates with text longer than the primary line, then you also need to check and edit a lot, add one whitespace, refresh & test, add two, refresh & test, take away one, refresh & test etc., until you find the right amount. And there's a lot of weird GUI stuff going on with alternates, i.e. different submenu width flipping-back-or-forth-behavior depending on when you press the ALT key (when opening the root menu, when showing the submenu, after having entered the submenu). So it _could_ be nice to have a width= parameter that force-sets a hard width for the items in the menu/submenu that the parameter is located in, and the setting would be valid for the primary echo lines _and_ their alternates. Any line that's longer would get truncated automatically, including alternates. (Naturally, such a width parameter would only have to be in one echo line per menu/submenu.) 

PS -- regarding GUI glitches: (1) I've noticed that after refreshing a plugin, when you show the menu, the menu borders don't align correctly with the icon in the menu bar. They are off by a couple of pixels to the left. (Maybe that's because I have Bartender installed?)

(2) In addition to that (and independent of menu alignment), when you move down the menu along the items after a refresh, the menu width changes ever so slightly at some point down the menu, but I don't know if it's a random thing or if it's related to specific menu items, where e.g. whitespace and trim=false parameter has been added. (?) This does not happen when you have moved down the menu once, and then click on the menu bar icon again: then this slight "width-wobble" doesn't occur.

**Comment by mm2270** [comment]
Maybe I'm not understanding, but there is already a [`length`](https://github.com/matryer/bitbar#writing-plugins) item you can throw into any menu or menu item line that will control the maximum width of the line displayed, meaning the max amount of characters that gets displayed before the line gets truncated (the entire line then displays as tooltip text when hovered over).

Would that do what you're asking for?

**Comment by JayBrown** [comment]
Not quite: length controls the echoed text, width would control the width of the menu space, independent of the text contents of the individual lines. If you had a width parameter, you could set the width of the whole menu/submenu, and using the length parameter you would still be able to set individual lengths for the _text_ of individual lines, e.g. if they're longer than the menu width and their truncating isn't at the right location of a term or word. So a width parameter would rather be a "GUI master setting" for a menu or submenu, overriding any text length that's longer than the width setting, while leaving lengths alone that are shorter than the menu width.
