### ISSUE TITLE
re-execute script on tray click - can be implemented like $BitBar ENV is

### ISSUE THREAD

**Issue by nikolakanacki** [matryer/xbar#301]

**Comment by nikolakanacki** [comment]
Sorry, this is an oversight on my part. I forgot that you can add `bash=` or `href=` on the first line, making it "execute" when that "tray" is clicked.

**Comment by nikolakanacki** [comment]
Reopening this since there is no way to do bash command with this feature. Even with `terminal=false`, clicking the "tray icon" (first line) doesn't allow the dropdown menu to open.

**Comment by iosdeveloper** [comment]
A line with `refresh=` parameter below `---` does exactly that.
Lines with action parameters (`href`, `bash`, `refresh`) above `---` are expected to replace the menu. You could output multiple lines that will cycle above `---` and output a line without an action parameter to have both one click action and menu.

**Comment by iosdeveloper** [comment]
Potential solutions discussed in #303.

**Comment by iosdeveloper** [comment]
@nikolakanacki You might want to look into HTML plugins:
https://github.com/matryer/bitbar/issues/210#issuecomment-184145047
https://gist.github.com/muhqu/8891318/6c3a5d987e2e2753de9e154cc98d43ea0d6ddde0#file-htmlplugin-peity-demo-html-L40-L44
