### ISSUE TITLE
Status item doesn't support alternate lines

### ISSUE THREAD

**Issue by iosdeveloper** [matryer/xbar#303]
If you add action parameters (`href`, `bash`, `refresh`) to status item lines (above `---`) in v1.9, the action replaces the menu.

I came up with two potential solutions:
- Show the menu if the alt key is pressed (implemented in b47c6f4)
- Add support for alternate status item lines (implemented in a92f62c)

The latter is definitely more flexible as it gives plugin developers control over the alt key behavior in the status bar (we already have it in the menu) but is also a little more complex. What do you think? @matryer

**Comment by matryer** [comment]
I'm not sure what the right thing to do here is. Can somebody provide some use cases?

**Comment by nikolakanacki** [comment]
My issue was referenced here. The use case I'm having is wanting to remove notifications informations whenever the user sees them (opens the menu). This breaks the user "flow" (UX) when clicking the tray does either one or the other - opens the menu **or** executes bash | refresh | href. I would very much prefer to have it do both - execute **and** open the menu. Is that something you see as possible?

Great work so far by the way!

**Comment by iosdeveloper** [comment]
@nikolakanacki Unfortunately, that would make things complicated, like we can't update the menu after a refresh when it is open.

**Comment by nikolakanacki** [comment]
Uhh, yeah, that just hit my mind after clicking the "Comment" button.. It definitely would make it more complicated. How about some event or something when closing the menu? And I'm asking this with running the risk of being accused of hijacking the topic, but it seams connected to me.

**Comment by iosdeveloper** [comment]
We could execute actions that don't affect the UX (AFAIK that would be only `bash` with `terminal=false` and `refresh=false`) while showing the menu. Thoughts?

**Comment by chrisidefix** [comment]
@matryer in relation to use cases. Having no access to any menu would generally be a problem when you are **only** running (one or more) status bitbar plugins that all have no menu, but only "single click actions". I think that addition was great, but a *Right-Click* or *Option/Alt-Click* would definitely be useful in these cases, when you need to:

 1. Shut down BitBar
 2. Manually Refresh BitBar
 3. Change the Plugin Folder
 4.  ... or do anything you else through the default Preferences Menu

**Comment by iosdeveloper** [comment]
Do we agree on b47c6f4 (simple over complicated)?
