### ISSUE TITLE
Makefile doesn't work

### ISSUE THREAD

**Issue by dotwaffle** [matryer/xbar#308]
```
11:49:16 ⏚ [mwalster@mwmbp:/tmp/bitbar] master ± make all
xcodebuild -project ./App/BitBar.xcodeproj ./App/Vendor/AHProxySettings/AHProxySettings.xcodeproj ./App/Vendor/DateTools/Examples/DateToolsExample/DateToolsExample.xcodeproj ./App/Vendor/DateTools/Tests/DateToolsTests/DateToolsTests.xcodeproj ./App/Vendor/NSStringEmojize/Example/NSStringEmojize.xcodeproj ./App/Vendor/STPrivilegedTask/PrivilegedTaskExample/PrivilegedTaskExample.xcodeproj
xcodebuild: error: Unknown build action './App/Vendor/AHProxySettings/AHProxySettings.xcodeproj'.
make: *** [build] Error 65
```

This is because the "find" is finding the vendor Apps first. If I manually run:

```
11:50:06 ⏚ [mwalster@mwmbp:/tmp/bitbar] master ± xcodebuild -project App/BitBar.xcodeproj
=== BUILD TARGET BitBar OF PROJECT BitBar WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
[...]
** BUILD SUCCEEDED **

11:50:24 ⏚ [mwalster@mwmbp:/tmp/bitbar] master ±
```

Is it worth correcting the Makefile, or just removing it?

**Comment by leebaylis** [comment]
I'm having the same issue trying to make v2.0.0-beta10 on big sur 11.1 / xcode 12.3.
However, in my case, dotwaffle's workaround doesn't work:

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/mpciiljb/Dropbox/bitbar-git/bitbar/App/build/BitBar.build/Release/BitBar.build/Objects-normal/x86_64/PluginManager.o /Users/mpciiljb/Dropbox/bitbar-git/bitbar/App/BitBar/PluginManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	(1 failure)

any ideas or tips as to how to proceed? Thanks!
