### ISSUE TITLE
Feature Request: set global menu font and size

### ISSUE THREAD

**Issue by mm2270** [matryer/xbar#310]
This is not an 'issue' but a 'feature request' but since there is no "Feature Request" section in github...
I'd love a way to globally set the font and font size for all text within a menu.

Use case:
I have a fairly involved menu plug-in I'm developing we plan to use to show statistical information about the system, check on various states and report information to the user, among other things.
Some of the formatting in the menu, especially when using tabs to separate information, can be a little off from one OS to the other due to Apple changing the system font from 10.9 (Lucida Grande) to 10.10 (Helvetica Neue) and again in 10.11 (San Francisco) Who knows what other font they will throw into the next version of OS X as its default?

Because of this, I'm encoding this plug-in to use one font across all text items, so the resulting display in the menu is consistent for any machines we deploy it to.
Unfortunately, this requires me to set literally every line that I'm echoing back with something like:

```
| font=$fontname size=$fontsize
```

Where `$fontname` and `$fontsize` are variables contained elsewhere within the script. It would be downright handy if there were some kind of global menu font flag we could set in the script that would force all lines to use the font name.
Like it works today, if the font name specified doesn't exist or you fat finger it, BitBar just defaults back to using the system font, which is a perfect compromise actually.

Any chance something like that could be built in at some point?

**Comment by mm2270** [comment]
Just wanted to bubble this one to the surface again to see if there was any chance something like this could be done? Now that I've been playing with the latest beta 6 release with the "check" feature, I've added something into one of my scripts that will allow the user to choose between a few different font sizes and widths and the menu redraws with their selection. Not that any of the new features in the beta are strictly necessary for this, but having the ability to show a selection as "checked" is nice, so I'm working that in now.

But once again, I need to specify the font and font size on every line that gets rendered since there's no way to assign a global font to any items that don't have a specific font assigned to override the global one. I would love it if I could simplify my code with a global font assignment and only override individual lines on a one by one basis in the script if needed.

Other than that, still loving BitBar, and I like some of the latest features being added. Nice work on all of it!

**Comment by alexrockt** [comment]
+1 - having a global font size would be great - At the moment I've to change it manually for every plugin, because I want my font size to be 10.

**Comment by rrggrr** [comment]
+1 - Inability to specify font when output is from a python script is problematic for tabular data, unless I'm not up to speed on how to make that happen when output is not shell generated.

**Comment by iosdeveloper** [comment]
@rrggrr https://github.com/matryer/bitbar-plugins/search?l=Python&q=font&type=Code&utf8=✓ ?

**Comment by rrggrr** [comment]
@iosdeveloper That helped. Formatted output from Pandas Dataframe was as easy as adding a column to the dataframe:

df['bitbar_suffix'] = "| size=18 font='Helvetica'"

**Comment by frakman1** [comment]
@mm2270 Your plugin sounds like something I would really enjoy. Is it out yet? What is it called?
