### ISSUE TITLE
Emoji :sunny: and :cloud: not showing correctly

### ISSUE THREAD

**Issue by vikeri** [matryer/xbar#312]
Embarrased to file this issue but still...

The emojis :sunny: and :cloud: do not render properly for me. They are just a black sun and a black cloud. It does not work with using the `:sunny:` or `:cloud:` sytnax nor copying the emoji directly or using the emoji keyboard in Mac either.

Atom seems to agree on which emojis to show correctly and which to show old style. I.E. if I paste the sun emoji into atom it becomes black. Vim will render it correctly though. Quite possibly an issue not related to Bitbar but tons of Googling didn't get me anywhere.

**To reproduce**
Use emoji :sunny: or :cloud:

**Comment by vogonistic** [comment]
I've had similar trouble with :snowflake:, but I never found the reason why they show up that way.

**Comment by vogonistic** [comment]
Looks like the magic is `\U0000FE0F`, which is a variant selector that chooses the emoji variation if there are multiple ways to draw a character. I'll see if I can get it added upstream: https://github.com/diy/NSStringEmojize/issues/10

**Comment by dandaka** [comment]
I really like this B/W style. And do want to use only BW icons where possible. Any ideas, how to do that? Where could I find all B/W icon glyphs?

**Comment by iosdeveloper** [comment]
@vogonistic I don't think our chances are very high. The repo was last updated 2 years ago. I would be fine with using your fork instead.

**Comment by matryer** [comment]
Let's switch to the better fork--or maybe we fork it and maintain it together?

**Comment by irstacks** [comment]
So :godmode: has a variant selector?
