### ISSUE TITLE
Internet not connected yet when bitbar runs after computer wakes up

### ISSUE THREAD

**Issue by ratbeard** [matryer/xbar#315]
I noticed that three of my bitbar plugins that fetch data over http error out when I first open my laptop in the morning.  I assume its because my wifi connection hasn't been established yet.  The bitcoin plugin runs every 10 seconds and swallows errors so its not very noticeable, but the brew update and a custom web scraping plugin I wrote are set to run once a day and error out noticeably as seen below.  

A workaround I do is click on a plugin and do cmd+r to re-run them.  

I was wondering if other people have this problem and if theres a way to solve without the workaround or making plugins internet connection aware.

Some solutions that bitbar might be able to implement are delaying running the plugins X seconds or until its determined theres internet access after waking up.

<img width="796" alt="2016-04-06 at 9 34 56 pm" src="https://cloud.githubusercontent.com/assets/28356/14352329/91e3f4f4-fc99-11e5-84b0-44650c0a7690.png">

**Comment by matryer** [comment]
I’d consider a delay after waking up to give other services (like WiFi) time to come online.

**Comment by JayBrown** [comment]
Or begin your script with e.g. 
`ping -q -c 1 8.8.8.8`
in a countdown loop. Set the start count high enough, e.g.
`((count = 10))`

I have a similar problem… a script checking if a website is up, and right after wake the script always thinks the site is down because WiFi isn't fast enough.

**Comment by JayBrown** [comment]
This is the one I'm using, not only for BitBar, but also in other scripts. It's not my own—found it on the web, as so often—, but it hasn't let me down so far. Important to set ((COUNT = 1)) if -eq 0 within the loop to account for the the final ((COUNT = COUNT -1))
```
((COUNT = 4))
while [[ $COUNT -ne 0 ]] ; do
    ping -q -c 1 8.8.8.8 &> /dev/null
    RC=$?
    if [[ $RC -eq 0 ]] ; then
        ((COUNT = 1))
    fi
    ((COUNT = COUNT - 1))
done
if [[ $RC -eq 0 ]] ; then
	STATUS="online"
	# do something
else
	STATUS="offline"
	# do something else
fi
```

**Comment by vogonistic** [comment]
If the script runs often, you can capture the exitcode or `stderr` and it it's not empty show a `Not connected…` message instead.

**Comment by caramdache** [comment]
Using `fping` provides more reliable results than ping.

See [https://stackoverflow.com/questions/18123211/checking-host-availability-by-using-ping-in-bash-scripts](url)

**Comment by caramdache** [comment]
Specifically, here is updated and simplified test code:

```
COUNT=4
until (( COUNT == 0 )); do
  fping -c1 -t300 8.8.8.8 2>/dev/null 1>/dev/null
  if (( $? == 0 )); then
    break
  fi

  if (( --COUNT == 0 )); then
    echo "⛑"
    exit
  fi

  sleep 10
done
```
