### ISSUE TITLE
Global shortcuts

### ISSUE THREAD

**Issue by markoradak** [matryer/xbar#325]
If I haven't said it already - Amazing app! 👍 

Now - I was thinking - is there a way to add an ability of having global shortcuts for bitbar menu items? Something like `key="cmd+option+shift+p"` - or similar syntax. I think it would come handy in certain situations.

**Comment by iosdeveloper** [comment]
See #212. Local would be easy, but not very useful (you have to click to open the menu first). Global is more complex, you could use something similar to my (abandoned) alt key press detection: https://github.com/matryer/bitbar/commit/a92f62c31d7dadc28cac10bc8eeaaabc5bdd2a12.

**Comment by iammarkoradak** [comment]
Got it. I'll look into it, thanks!

**Comment by dimitrieh** [comment]
+1

**Comment by raylee** [comment]
This may now be easy to implement using https://github.com/soffes/HotKey , if you don't mind pulling in a bit of Swift and and (what looks to be) MIT licensed code.

It appears to tie the hotkey registration and unregistration to the lifetime of the objects, which is probably a convenient fit for this use case.

**Comment by gingerbeardman** [comment]
I’ve not been about to try but can you not use System Preferences > Keyboard > Shortcuts?

**Comment by raylee** [comment]
@gingerbeardman The idea here is to allow plugins to dynamically register and unregister shortcuts. That would allow (for example) a simple script to replace [Apptivate](http://www.apptivateapp.com/).

System shortcuts won't work for that use case.

**Comment by gingerbeardman** [comment]
Understood

**Comment by 097115** [comment]
If the point is to toggle BitBar's menubar items, then probably something like this could help:

    tell application "System Events"
    	tell (first application process whose bundle identifier is "com.matryer.BitBar")
    		tell menu bar item 1 of menu bar 1
    			click
    		end tell
    	end tell
    end tell
