### ISSUE TITLE
Menu items move around if plugin doesn't output anything

### ISSUE THREAD

**Issue by jessejoe** [matryer/xbar#327]
I have 2 plugins loaded, one of them only actually puts something in the bar if a condition is met when it refreshes. If that condition is not met, it doesn't output anything, but it still moves around the other menu items like it's trying to load. See this GIF:

![](http://i.imgur.com/ClFHEKJ.gif)

After clicking on another item, the space where the item that didn't load was gets filled back in.

Is there any way to make the plugins not touch the bar unless they are actually going to output something?

**Comment by iosdeveloper** [comment]
This is a known issue (see #177).
