### ISSUE TITLE
Question (bug?): possible to set new refresh rate with mv command?

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#332]
I'm trying to have the user input a new refresh rate for a plugin, e.g. change 30m to 60m. The main BitBar script is then renamed from old-basename to new-basename with the mv command. Then the plugin needs to be refreshed, but since it's already loaded, the old-basename needs to be refreshed. (Using new-basename wouldn't work.) Until this point, everything works fine. Then, however, the plugin goes into an endless "Updating…" state, from which it doesn't wake up. It seems that it wants to reload old-basename, but doesn't find it anymore, since it has been renamed to new-basename. Any way to get around this problem?

**Comment by dagware** [comment]
Yeah, I've seen this problem too. I would be really interested to see if there's a solution.

**Comment by iosdeveloper** [comment]
BitBar currently needs a reset (`command` + `R`), not a refresh, when renaming plugins. AFAIK the only way to reset externally would be to `killall` and `open` BitBar.

**Comment by JayBrown** [comment]
It's probably better to do it as gentle as possible
```
/usr/bin/osascript -e 'tell application "BitBar" to quit' &>/dev/null && sleep 1
/usr/bin/open -b com.matryer.BitBar
```
PS: Maybe there's a solution to either make BitBar scriptable, so you could do something like
```
/usr/bin/osascript  << EOT
tell application "BitBar" to activate
tell application "System Events"
	tell process "BitBar"
		click menu 1
		keystroke "r" using command down
	end tell
end tell
EOT
```
… or simply extend the URL scheme to `/usr/bin/open "bitbar://reset"`. (This would be the most elegant solution.)

**Comment by fferri** [comment]
More elegant than that would be that if BitBar sees the script doesn't exist anymore (e.g. my_script.30s.sh) it would look for anything that matches my_script.*.sh and reload.

Or better, a new way to specify refresh timeouts.

Quick idea: instead of coding the interval in the script name, the interval is printed to the stdout, so the script can decide a new timeout at each refresh.
