### ISSUE TITLE
bullet option?

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#335]
Love the `checked=true` option.

Proposal: bullet option `bullet=black` and `bullet=white` (or dark/light, whatever).

Currently doing it with emojis:
![bullets_submenu](https://cloud.githubusercontent.com/assets/477431/15786460/1485a7d6-29bd-11e6-9aa6-81786c58156e.png)

These are round large bullets, or the emojis black & white circle: ● ○
But tend to prefer squares… emojis black & white square … looks nicer to me: ■ □

Possible?

**Comment by iosdeveloper** [comment]
Checkmark is a standard of OS X. I think this is good to leave up to the plugins.

**Comment by mm2270** [comment]
I was going to make a similar comment. Although the bullet option is interesting, I can honestly say I've never seen a menu bar use bullets as opposed to simple checkmarks. Or along with them. So its definitely non-standard.

Then again, some of the options BitBar currently does aren't exactly common. Most menubar items don't use custom fonts, font sizes, styles or colors, and those are all available within BitBar. And many of them don't use icons either. (the Keyboard and Character viewer menubar item being one of the exceptions)

**Comment by JayBrown** [comment]
OS X has this diamond thingy.
![diamond](https://cloud.githubusercontent.com/assets/477431/15787955/572b3ec2-29c5-11e6-8730-4ffd97375c90.png)

Don't know what else there is.

**Comment by frakman1** [comment]
What is this `checked=true` feature? I don't see it listed in the [Plugin API section](https://github.com/matryer/bitbar#plugin-api) of the README.

**Comment by iosdeveloper** [comment]
@frakman1 It is listed in the one of the beta branch: https://github.com/matryer/bitbar/blob/beta/README.md#plugin-api

**Comment by frakman1** [comment]
Thank you @iosdeveloper !

**Comment by frakman1** [comment]
Any idea when this feature will be integrated? I looked at the commit and it included other unrelated changes.

**Comment by frakman1** [comment]
I was able to implement something like this with the existing bitbar features and some code in my plugin:

![image](https://user-images.githubusercontent.com/5826484/28651169-2cd900f0-724e-11e7-971d-4b96af1fd69e.png)

![image](https://user-images.githubusercontent.com/5826484/28651186-4b67f95e-724e-11e7-835b-52fe9f61d1a0.png)

![image](https://user-images.githubusercontent.com/5826484/28651208-6a5d5ea8-724e-11e7-815f-d2af9ca264b6.png)

**Comment by JayBrown** [comment]
Yeah, but emojis are in my view only a temporary solution. It would be great to be able to add base64-encoded images, similar to the menu bar icon.

Another great feature would also be to show the icons of files. Let's say, you want to make a BitBar menu with all preference panes installed on your system, i.e. the ones in /System/Library/, /Library, and ~/Library—which is something I plan to do, so I can quickly open them—, it would be a great help to see the panes' icons in the menu as well.

**Comment by frakman1** [comment]
I actually prefer using emojis when they fit the need because they render perfectly on retina and on-retina displays (automatically). Since I am coding on a non-retina Mac and didn't know that my icons that looked fine on my display but were in fact horrible on a retina-screen, I ended up having to re-encode all my custom icons images to 144 DPI before they would look sharp on a retina screen.

I don't understand what feature you are requesting. I can currently add a custom icon as long as it is to the left of the displayed text. See https://github.com/matryer/bitbar/issues/425

**Comment by JayBrown** [comment]
Oh, great… didn't know that you could use images in the menu itself. To the left is fine for me.

Then it leaves me with the idea to show icons of files automatically. But how would BitBar know that it needs to show a file's icon? Probably not possible.

**Comment by JayBrown** [comment]
You probably need to hack it yourself: get the path to the .icns of the target file, copy the .icns to a working directory, run `iconutil --convert iconset TargetIconSet.icns`, then base64-convert the png labeled `icon_32x32@2x.png`, write the base64 to your BitBar-script's support folder with a fitting basename, then echo it as $IMAGE. During subsequent BitBar script reloads, you can just cat the base64 string from the support folder. Should work, I assume. (Question is only, if `icon_32x32@2x.png` is the correct one for Retina support. The actual resolution is 64*64 at 72 ppi.)

**Comment by NorthIsUp** [comment]
it looks like four options are natively supported.
https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/#using-symbols-in-menus
