### ISSUE TITLE
Option to add shortcuts to BitBar items

### ISSUE THREAD

**Issue by Coriou** [matryer/xbar#342]
First of all, great tool ! I just discovered it but was quickly able to create a neat little monitor for my servers with avg load, uptime, errors, ... It's really cool.

In addition to all you can already do with BitBar, I think it would be awesome to be able to add shortcuts to items. Something like this :

`Copy|shortcut="CMD+C" bash="scriptToRun"`

And that would return something like this :

![BitBar Shortcut](https://i.imgur.com/tJM5K6M.png)

And, of course, capture the shortcut and trigger the script passed to that item when BitBar is "open" (meaning I clicked on it in my status bar)

**Comment by iosdeveloper** [comment]
See #325

**Comment by matryer** [comment]
You could just make the item selectable, and run a script that puts it into your clipboard?

**Comment by Coriou** [comment]
Yeah, of course. Copying is not what I want to do here, it just served as an example.

What I'm talking about here is support for shortcuts in general. Both capturing them, and displaying them in the "native ~~OSX~~ macOS way" like in the screenshot (tabulation is not reliable because you don't know the width of the deployed menu).

**Comment by fenhl** [comment]
This would be great, and since ⌘O, ⌘Q, and ⌘R are already existing shortcuts it should be possible to allow the plugin to define more, no?

**Comment by inspaceco** [comment]
I am wondering if anyone figured this out, I want to open a new application window on click and ther keyboard shortcut is cmd+ctl+N but I'm not sure how to execute that.

**Comment by gingerbeardman** [comment]
@inspaceco you'd need to control the other app using AppleScript (`osascript` command) but really there is probably another way to get global hotkey for that app, like using Keyboard Maestro etc.
