### ISSUE TITLE
Shortcuts and right margin

### ISSUE THREAD

**Issue by alesf** [matryer/xbar#348]
"Run in Terminal ..." menu item has a shortcut assigned to it which stretches the right margin.
It's not a problem if all of the items are textual and are not the same width but when you're dealing with images or monospaced fonts (for positioning purposes) it's noticeable.

Suggestion: move Open in Terminal option to submenu Preferences.

With shortcut:
![screen shot 2016-07-04 at 13 30 45](https://cloud.githubusercontent.com/assets/1148574/16559310/68004a64-41ec-11e6-814c-c3a1ebfc7e9c.png)

Without shortcut:
![screen shot 2016-07-04 at 13 31 17](https://cloud.githubusercontent.com/assets/1148574/16559309/67e11234-41ec-11e6-8e39-b6ca5b044391.png)

**Comment by frakman1** [comment]
I'm giving a thumbs up for the Pink Floyd song.

**Comment by m-cat** [comment]
It would make sense to move it to Preferences (Refresh All is already there, why should Run in Terminal be different?)

Also, I'm not sure if ⌘O is standard for this kind of feature, but I would prefer something that can be hit with one hand. What's wrong with ⌘T?
