### ISSUE TITLE
Get LANG environment variable?

### ISSUE THREAD

**Issue by mherger** [matryer/xbar#369]
Hi,

I'm trying to localize my plugin. I wanted to switch translation based on the LANG environment variable. Unfortunately this seems to not be available when the plugin is run in BitBar (it's available when run in the shell). Is this a known limitation? Some other way to figure out the user's language?

Michael

**Comment by iosdeveloper** [comment]
See https://github.com/matryer/bitbar/pull/146#issuecomment-185631966
