### ISSUE TITLE
Run in terminal works once when Terminal is not open already then no longer works if Terminal is running

### ISSUE THREAD

**Issue by AddictArts** [matryer/xbar#373]
Selecting "Run in Terminal" fails the second time or fails if Terminal.app is already running. This is also the same for "echo'd" commands with the "|" in the script. I am on Yosemite if that matters running TotalTerminal as well.

**Comment by iosdeveloper** [comment]
Which version of BitBar do you use?

**Comment by AddictArts** [comment]
1.9.2

**Comment by AddictArts** [comment]
Fail may be to strong, what I mean is it appears to do nothing. I get an open terminal window and no script is executed. This used to work and recently stopped working.

**Comment by iosdeveloper** [comment]
Does it say v1.9.2 under Preferences?

**Comment by AddictArts** [comment]
No. Running "Check for updates" then has the dialogue with the version

**Comment by matryer** [comment]
Open Preferences and hold the option key?

**Comment by AddictArts** [comment]
Ah, yes it says v1.9.2 when I hold the option key
