### ISSUE TITLE
BitBar icon doesn't dim on second display with dark menu bar

### ISSUE THREAD

**Issue by ehemmete** [matryer/xbar#374]
With a second display and the dark menu bar option in System Preferences->General enabled, the BitBar menu bar icon doesn't dim when the display is not primary.
This is on macOS Sierra.  (Siri also has this problem!)
My icon is the snow man in the attached screen shot.
![screen shot 2016-10-14 at 3 40 58 pm](https://cloud.githubusercontent.com/assets/6943881/19402076/9f1a0bec-9224-11e6-9d93-a86a60410081.png)

**Comment by matryer** [comment]
Why would you want to dim that little happy snowman? :D

**Comment by iosdeveloper** [comment]
Can you try `templateImage` instead of `image`?

**Comment by ehemmete** [comment]
Interesting, with the default ... it doesn't have this problem.  The snow man is the emoji snowman and used in a bash script.
echo "☃"
