### ISSUE TITLE
Could bitbar automatically refresh plugins when going from no network -> network

### ISSUE THREAD

**Issue by SCdF** [matryer/xbar#375]
When I wake my laptop from sleep it takes awhile for the wifi to get connected again.

This means that whenever I open my laptop I have to force a hard refresh of bitbar once the network connects to fix all my broken / disconnected plugins.

Ideally bitbar would detect when the OS went from no network connectivity -> connected and refresh plugins.

**Comment by iosdeveloper** [comment]
Or this is handled on the plugin side e.g. by using long running plugins and blocking until connected.

**Comment by SCdF** [comment]
Interesting! Are long-running plugins a new feature to bitbar I'm not aware of, or are you using shorthand for the idea of having an external process that manages itself that is polled frequently by a normal bitbar plugin?

**Comment by iosdeveloper** [comment]
It's a feature of v2 beta: https://github.com/matryer/bitbar/blob/beta/Docs/LongRunningPlugins.md

**Comment by SCdF** [comment]
Cool, cheers for the link. Are you saying I should re-work the plugins I use (and / or have written) to do this over and above a generic refresh solution provided by bitbar, or that it's an alternative for now?

**Comment by iosdeveloper** [comment]
It's an alternative and can be used together with the refresh timer for efficiency.

**Comment by caramdache** [comment]
Any idea when 2.0 might be out ? I am running into the same issue now.

**Comment by ABeltramo** [comment]
Any news here? I can help with the coding part but I can't find any pull request.

**Comment by gingerbeardman** [comment]
@caramdache 
@ABeltramo 

2.0 beta 10 is here: https://github.com/matryer/bitbar/releases

source is in the beta branch: https://github.com/matryer/bitbar/tree/beta

**Comment by idoo** [comment]
@matryer any plans to release v2 ?

**Comment by matryer** [comment]
v2 was going to be the swift rewrite but I wasn't really involved from a technical perspective (because I don't code in Swift), so it's a tough one. The current BitBar release is pretty stable, but I'm currently baffled by the CI being broken which is holding things up. E.g. https://travis-ci.org/matryer/bitbar-plugins/builds/631576548?utm_source=github_status&utm_medium=notification
