### ISSUE TITLE
Vertical offset in Sierra

### ISSUE THREAD

**Issue by fenhl** [matryer/xbar#376]
<img width="241" alt="screen shot 2016-10-18 at 18 16 17" src="https://cloud.githubusercontent.com/assets/641386/19490554/20861c1a-955f-11e6-8560-7b3961349aab.png">

As you can see, there is a vertical offset of the bitbar plugin text compared to system menu bar items like the clock. This offset was not present (or less noticeable) in El Capitan.

**Comment by dzg** [comment]
There is also an offset between different bitbar items (in the same language.)

Any solutions?

**Comment by oleander** [comment]
@dzg Try my pending PR. It should solve the problem. https://github.com/matryer/bitbar/pull/391

**Comment by dimitrieh** [comment]
would love this as well
