### ISSUE TITLE
TouchBar support

### ISSUE THREAD

**Issue by matryer** [matryer/xbar#378]
No reason why you shouldn't be able to check a "Show in Touch Bar" option to put any Bitbar plugin onto the new MacBook Pro Touch bar.

**Comment by iosdeveloper** [comment]
https://twitter.com/willfprice/status/791712832014299136

**Comment by matryer** [comment]
Ha.

**Comment by moshed** [comment]
better touch tool allows you to put widgets in the touchbar

![image](https://cloud.githubusercontent.com/assets/8683379/21921202/565610d4-d934-11e6-8451-80639f9c5988.png)

the time is constantly changing

**Comment by iosdeveloper** [comment]
Maybe using private API to add to the control strip: https://github.com/a2/touch-baer
