### ISSUE TITLE
BitBar for macOS widgets area maybe?

### ISSUE THREAD

**Issue by insiderq** [matryer/xbar#384]
Subj is in the topic.
Top bar is too short for some statistics.
Alternative version with projection to notification centre maybe? 
I mean, the thing is that i am able to make winkdex display on my mobile in widgets area, but a cant do that on mac. And i instantly had this thought about some app that gives you ability to display everything on notification centre and i googled here. So maybe?

**Comment by iosdeveloper** [comment]
See http://apple.stackexchange.com/a/115373

**Comment by insiderq** [comment]
No, i mean the widgets area. Bitbar for macos widgets area.

**Comment by justinmayer** [comment]
When you say "widgets area," are you referring to the all-but-deprecated [Dashboard](https://en.wikipedia.org/wiki/Dashboard_(macOS))?

**Comment by insiderq** [comment]
@justinmayer no, i mean control center widgets area

**Comment by justinmayer** [comment]
As far as I'm aware, there is no "Control Center" in macOS. I assume you refer to the **Notification Center**, which contains two views: *Today* and *Notifications*

**Comment by insiderq** [comment]
Yes

**Comment by Tekl** [comment]
I'm also looking for a customizable today widget as my menubar has no space left

**Comment by matthew-groth** [comment]
+1 for scriptable notification center widgets in today view

**Comment by m0a** [comment]
+1

**Comment by joeynotjoe** [comment]
Didn't know I wanted that, but now I do. 
+1
