### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by r-xela** [matryer/xbar#397]
I'm getting the following error for all plugins from time to time

`Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9`

![screen shot 2017-02-16 at 17 07 37](https://cloud.githubusercontent.com/assets/413476/23029509/16e4bc00-f46b-11e6-8ba1-ec9b6617b488.png)

I can quit BitBar and it works fine again. I can not create the error on purpose - it just happens.

I'm using BitBar 2-beta10 on macOS 10.12.3

**Comment by kdeldycke** [comment]
Duplicates #400. Can be closed.
