### ISSUE TITLE
bitbar://refreshPlugin should do the same as clicking "Refresh All"

### ISSUE THREAD

**Issue by kodie** [matryer/xbar#398]
If a plugin is installed via a way other than using the `bitbar://openPlugin` way, there's no way for the plugin to come up without clicking the "Refresh All" option. It would make sense to be able to do this buy simply visiting `bitbar://refreshPlugin` without passing any variables, or at least `bitbar://refreshPlugin?name=*?` (which currently does refresh all plugins but does not bring up newly installed plugins).

Thanks!

**Comment by kodie** [comment]
This would be especially handy for the [BitBar CLI tool](https://github.com/kodie/bitbar-cli) :D

**Comment by matthew-groth** [comment]
In addition, `bitbar://refreshPlugin?name=*?` tries to update plugins that have been removed from the plugins folder. This causes `Updating...` to appear in the menu bar until BitBar is forced to quit and restart.

**Comment by keresan** [comment]
i run into the same problem and kind of fix it with applescript. Its far from an ideal solution, so if you guys have come up with something better, please share.
```
set old to (path to frontmost application as text)
ignoring application responses
	tell application "System Events" to tell process "BitBar" to click menu bar item 1 of menu bar 1
end ignoring
--we need this because for unknown reason there is a delay about 5s after the first click
do shell script "killall System\\ Events"
delay 0.1
tell application "System Events" to keystroke "r" using {command down}
activate application old
```
