### ISSUE TITLE
bash= cannot contain spaces, at least with Javascript plugins

### ISSUE THREAD

**Issue by kodie** [matryer/xbar#399]
I have the following test plugin and every single item returns the same error:

The plugin:

```javascript
#!/usr/bin/env /usr/local/bin/node

console.log('Test | dropdown=false')
console.log('---');

console.log('Test 1 | bash="cd /Test Folder"');
console.log("Test 2 | bash='cd /Test Folder'");
console.log(`Test 3 | bash="cd /Test Folder"`);
console.log(`Test 4 | bash='cd /Test Folder'`);
console.log('Test 5 | bash=\"cd /Test Folder\"');
console.log("Test 6 | bash=\'cd /Test Folder\'");
console.log(`Test 7 | bash=\"cd /Test Folder\"`);
console.log(`Test 8 | bash=\'cd /Test Folder\'`);

console.log('---');
console.log('Refresh | refresh=true terminal=false');
```

The error:

```
-bash: cd: too many arguments
```

I'm guessing this is related to https://github.com/matryer/bitbar/issues/297

I am running BitBar 1.9.2

**Comment by kodie** [comment]
Just checked, this problem also exists in v2 beta 10

**Comment by oleander** [comment]
@kodie Could you try the swift version? There's a download link the bottom of this pullrequest https://github.com/matryer/bitbar/pull/391

**Comment by kodie** [comment]
@oleander I got the same results as beta 10, also all of my plugins broke with this version as well.

**Comment by kodie** [comment]
Nevermind, I'm dumb. You have to wrap quotes around the path rather than the entire command. Duh.

**Comment by kodie** [comment]
Actually, none of these work when trying to get the script to call itself:

```
#!/usr/bin/env /usr/local/bin/node

var self = process.argv[1];

console.log('Test | dropdown=false')
console.log('---');

console.log(self);
console.log('Test 1 | bash=\"' + self + '\" param1=test');
console.log("Test 2 | bash=\"" + self + "\" param1=test");
console.log(`Test 3 | bash=\"${self}\" param1=test`);
console.log('Test 4 | bash=\'' + self + '\' param1=test');
console.log("Test 5 | bash=\'" + self + "\' param1=test");
console.log(`Test 6 | bash=\'${self}\' param1=test`);

console.log('---');
console.log('Refresh | refresh=true terminal=false');
```

**Comment by oleander** [comment]
What's the error message you get?

**Comment by kodie** [comment]
```
Directory does not exist
```

**Comment by davidjmerritt** [comment]
I am also seeing this with python scripts as well using the non-executable rule even if I escape the spaces (on Mac):

> bash=/usr/bin/ruby param1=/Users/user/rubyscript.rb param2=arg1 param3=arg2 if script is not executable

For example:
```
print 'Restart Server|bash=/user/bin/python param1="'+SCRIPT_DIR.replace(' ','\\ ')+'/'+SCRIPT_FILE+'" param2=restart terminal=true'
```

Terminal doesn't even launch :(

**Comment by groucho86** [comment]
This formatting seems to work for me:
`print 'Fix symlink| bash=/usr/bin/python param1="/Users/xx/sub folder/Documents/resolve_lut_sym.py" terminal=false'`

**Comment by davidjmerritt** [comment]
It's my bad.  param2="is missing quotes"

**Comment by dimitrov-adrian** [comment]
Escaping spaces helps when terminal=true but when is false, then it doesn't helps.

**Comment by zanza00** [comment]
I have a similar problem, I am trying to open current wallpaper and i have problems with escaping the spaces and parenthesis

here is my code https://gist.github.com/zanza00/2365f66c31477e48b984444a3aeb932f

and the error inside the terminal

```
open /Users/simonepicciani/Dropbox (Personal)/IFTTT/reddit/wallpapers/Anarchy_L.A.S.E.R.S.jpg    
-bash: syntax error near unexpected token `('
```

if I execute the script in the terminal the line is correct 

`Anarchy_L.A.S.E.R.S | terminal=true bash=open param1="/Users/simonepicciani/Dropbox (Personal)/IFTTT/reddit/wallpapers/Anarchy_L.A.S.E.R.S.jpg"`

what am I missing?

**Comment by gingerbeardman** [comment]
@zanza00 you need to make sure that path is quoted. you can see in the error it isn't. 

try 
`param1="\"/Users/simonepicciani/Dropbox (Personal)/IFTTT/reddit/wallpapers/Anarchy_L.A.S.E.R.S.jpg\""`

**Comment by zanza00** [comment]
@gingerbeardman thanks for the suggestion, sadly it didn't work. the quote is always stripped away.

I even tried something silly as putting 5 quotes before and 5 after 😞 

Maybe there is some kind of sanitize? I looked at the source code but my knowledge of objective C is awful and i didn't understand much.

**Comment by gingerbeardman** [comment]
@zanza00 how about just quoting the space character? 

`param1="/Users/simonepicciani/Dropbox\ (Personal)/IFTTT/reddit/wallpapers/Anarchy_L.A.S.E.R.S.jpg"`

**Comment by garyking** [comment]
> @zanza00 how about just quoting the space character?
> 
> `param1="/Users/simonepicciani/Dropbox\ (Personal)/IFTTT/reddit/wallpapers/Anarchy_L.A.S.E.R.S.jpg"`

It will work only if the space is preceded by two backslashes, not one.
