### ISSUE TITLE
BitBar runs out of file descriptors

### ISSUE THREAD

**Issue by tresni** [matryer/xbar#400]
Occasionally seeing `Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9`.

![1 bhartvigsen brians-air-2 zsh 2017-03-08 19-39-33](https://cloud.githubusercontent.com/assets/210250/23733646/62bd1b46-0437-11e7-95a2-71230fa10c4e.png)

system.log reports:
```
Mar  8 18:52:16 Brians-Air-2 BitBar[50844]: Error when running package_manager.7h.py: Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9
Mar  8 19:40:41 Brians-Air-2 BitBar[50844]: Error when running VPNThings.3s.sh: Failed to set posix_spawn_file_actions for fd -1 at index 0 with errno 9
```

Refreshing gives just BitBar with `No plugins found` message.  Quit BitBar and restart and everything returns to normal.

Google seems to indicate we are possible holding to many file handles open with a proposed solution of closing the [output pipe](https://github.com/matryer/bitbar/blob/aa4dee753105ee887b58e9ddddbbd4a539ed95ac/App/BitBar/ExecutablePlugin.m#L28-L32) [file handle](https://github.com/matryer/bitbar/blob/aa4dee753105ee887b58e9ddddbbd4a539ed95ac/App/BitBar/ExecutablePlugin.m#L43-L44).  Best example I can find (haven't tested) is [How to solve a memory leak on a NSFileHandle](http://stackoverflow.com/questions/17679104/how-to-solve-a-memory-leak-on-a-nsfilehandle) & [File descriptors not freed up without a -closeFile call](http://www.cocoabuilder.com/archive/cocoa/289471-file-descriptors-not-freed-up-without-closefile-call.html).  Creating our own `@autoreleasepool` would also potentially work as proposed in these solutions.

**Comment by elia** [comment]
I'm having the same issue, occasionally.

**Comment by matryer** [comment]
@tresni That's a great report, I don't suppose you fancy having a stab at a PR for it do you?

**Comment by elia** [comment]
Meanwhile I worked around the problem with this plugin that I share in case anyone bumps into this issue and is not knowledgeable enough to send a PR (like myself 😅), it basically restarts BitBar every 1h:


`restarter.5m.rb`

```rb
#!/usr/bin/env ruby

config = File.expand_path "~/.config/bit-bar-restarted-at"
restarted_at = Time.at(File.exist?(config) ? File.read(config).strip.to_i : 0)
one_hour = 3600 # seconds
now = Time.now
force = ARGV.include?('-f')

restart = -> do
  code = <<-APPLE_SCRIPT
  tell application "BitBar"
      quit
  end tell
  delay 2 -- Wait for BitBar to close
  tell application "BitBar" to launch
  APPLE_SCRIPT

  system 'osascript', '-e', code

  Dir.mkdir File.dirname(config) unless File.exist?(File.dirname(config))
  File.write config, now.to_i
end

if force || (now - restarted_at) > one_hour
  puts "♻"
  puts "---"
  restart.call
  puts "Just restarted!"
else
  puts "♲"
  puts "---"
end

puts "Last restarted #{(now - restarted_at).to_i / 60}m ago"
puts "#{((now - restarted_at).to_i + 3600) / 60}m until the next restart"
puts "⚡️ Force restart | terminal=false bash='#{__FILE__}' param1='-f'"
```
