### ISSUE TITLE
Is it possible to have no plugins with no output?

### ISSUE THREAD

**Issue by jessejoe** [matryer/xbar#401]
I use bitbar to alert me when something is happening, so when this happens the plugin will echo something to the taskbar to notify me. When this thing is not happening, I don't want anything in the menu bar, so it echoes nothing. However when there are no plugins with no output, the menu has a placeholder that says `BitBar` which constantly flickers and refreshes. I can get around this by echoing something when the thing is not happening, but that's just wasted space in the menu bar to me. I tried to use the zero-width space unicode character and other empty characters, but they seem to be stripped out and not considered a usable character.

**Comment by jessecarbon** [comment]
FYI, this removing this strip allows empty characters - https://github.com/matryer/bitbar/blob/aa4dee753105ee887b58e9ddddbbd4a539ed95ac/App/BitBar/Plugin.m#L497

Although there is still a little bit of space used so that you can click on it.

**Comment by jessejoe** [comment]
FYI, this removing this strip allows empty characters - https://github.com/matryer/bitbar/blob/aa4dee753105ee887b58e9ddddbbd4a539ed95ac/App/BitBar/Plugin.m#L497

Although there is still a little bit of space used so that you can click on it:

![image](https://cloud.githubusercontent.com/assets/1694586/24217054/e4477d40-0f14-11e7-81a1-8197ee0a05f8.png)

**Comment by NickChristensen** [comment]
@jessejoe I've looked for something similar, and can't find a way to actually hide empty items. In the meantime though, I've been outputting a `\b` character, which renders the same empty menu in your screenshot above.
