### ISSUE TITLE
Tabs with defined column width in BitBar menu using monospaced font?

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#403]
Maybe I'm missing something. I'm currently trying to port a shell script to BitBar, but the tabbed formatting seems to be missing.

Normally I do it like
```
tabs 20
echo -e "Column 1 content:\tColumn 2 content"
```
and so on. In BitBar this is not possible, because the "TERM environment variable isn't set". I can't do `export TERM=bash` or use `tabs` as `tabs -T bash 20`, because the "terminals database is inaccessible" to BitBar's own built-in shell.

So how do you guys use tabs with **defined column width** in BitBar? I.e. how do you make the second column always start at the same offset, independent of the character count in the first column?

(Monospaced output, of course, i.e. "terminal-like".)

**Comment by dimitrieh** [comment]
related to https://github.com/matryer/bitbar/issues/350
