### ISSUE TITLE
[INFO] No refresh after wake (script solution)

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#404]
Not sure if "no refresh after wake" is planned for a future release, but this is how I'm currently doing it for a script I'm writing:

```
WSCONT=true
PMLOG=$(/usr/bin/pmset -g log \
	| /usr/bin/grep -v "Wake Requests" \
	| /usr/bin/awk '{print $1, $2, $3, $4}' \
	| /usr/bin/grep -w "Wake" \
	| /usr/bin/tail -r | /usr/bin/head -1)
CURRENT_POSIX=$(/bin/date +'%s')
CURRENT_DAY=$(/bin/date +'%F')
WAKEDAY=$(echo "$PMLOG" | /usr/bin/awk '{print $1}')
if [[ $WAKEDAY == $CURRENT_DAY ]] ; then
	WAKEDATE=$(echo "$PMLOG" | /usr/bin/awk '{print $1, $2, $3}')
	WAKEPOSIX=$(/bin/date -f'%F %T %z' -j "$WAKEDATE" +'%s')
	DATEDIFF=$(echo "$CURRENT_POSIX - $WAKEPOSIX" | /usr/bin/bc)
	# add the number of seconds in the next line after "-lt"
	[[ $DATEDIFF -lt 47 ]] && WSCONT=false
fi
if ! $WSCONT ; then
	# do something different than usual
else
	# run the BitBar plugin as usual
fi
```

You could probably leave out the day comparison, and just go for the epoch time subtraction.

**Comment by xindi-dumbledore** [comment]
may i ask where this script should go?

**Comment by JayBrown** [comment]
Into your own BitBar script(s), somewhere at the beginning.

**Comment by xindi-dumbledore** [comment]
You mean the plugin? or something related to BitBar itself? I tried to put it in my plugin file but it doesn't seem to work... maybe I understand it wrong

**Comment by JayBrown** [comment]
Right. If you have a plugin-script (i.e. something like `MyScriptName.5m.sh`) in your BitBar plugins folder, you can add the bash snippet into the script somewhere at the beginning. You basically have to analyze the script first, to see where to best put the snippet, and then re-arrange the script a little bit, i.e. the default original script (most of it at least) would replace the line `# run the BitBar plugin as usual`, and your own variation would replace `# do something different than usual`, e.g.

```
echo "Refresh aborted after wake."
exit
```

But it's really only necessary for complex scripts that take a lot of time to run. And it also depends on your computer. If you have new & fast Mac, you probably don't need it, but if you're running a complex script also on an older Mac, like I'm doing, it's best to let the computer fully wake first, and not congest the wake process too much, ergo cancel a complex BitBar script.

**Comment by xindi-dumbledore** [comment]
thanks a lot~ now it seems to work~ :D but this script can't solve the problem of BitBar changing its position in menubar after wake right?
