### ISSUE TITLE
Plugin not showing output and can't figure out why

### ISSUE THREAD

**Issue by mgroth0** [matryer/xbar#405]
I must be forgetting something. I have made a bunch of plugins already, but now all of a sudden for some reason I can't _make_ or _add_ new ones.

Space is not an issue. There is plenty of free space in my menu bar and I am debugging with small output strings.

I have [bitbar-cli](https://github.com/kodie/bitbar-cli) installed, and it is correctly showing the plugins I am trying to install with the `bitbar list` command.

I am running `chmod +x` on all plugins. I don't think metadata can be a problem. I've done a side-by-side comparison of finders "get info" for my working and not-working plugins, and they are exactly the same.

The plugins are very simple and show correct output when executed on their own outside of bitbar. Here are a couple of examples of attempts I have made:

**pleasework.2s.sh**
```
echo "pleasework"
```

**pleasework.2s.applescript**
```
#!/usr/bin/osascript

get "pleasework"
```

Both of these files are in my plugins folder. I ran `chmod +x` on both. There is plenty of space in my menu bar.

In addition, when I try to install plugins that I know have worked in the past, such as [deathTimer](https://getbitbar.com/plugins/Lifestyle/deathTimer.5m.py), they are not working. And yet certain plugins that I have always have installed, such as [kmstatus](https://forum.keyboardmaestro.com/t/create-menu-bar-status-icons-using-bitbar/3658) are still working fine.

Also, I don't think its possible that space can be an issue. In my experience, if bitbar output becomes too long all plugin's output immediately becomes hidden. But I can still see some of my working plugin's output, so I don't think any kind of whitespace characters or anything like that could be the problem.

I'm completely stumped. How can I further investigate this?

**Comment by matthew-groth** [comment]
Turns out I was wrong about the spacing issue. If one plugin takes up too much space, others do not disappear. This still doesn't fully explain the trouble I am having, however.

**Comment by matthew-groth** [comment]
I was able to finally get my new plugin working by removing all plugins and re-adding them one by one. I don't understand what went wrong here. If anyone can comment on what may have been going wrong here that would be good. Otherwise this issue can be closed.
