### ISSUE TITLE
how to set bitbar plugin will not loop it's turn in Multi-line plugin ?

### ISSUE THREAD

**Issue by liulover5** [matryer/xbar#412]
how to set bitbar plugin will not loop in Multi-line plugin ?
eg (on mac):
data.1s.sh
echo "$(data)"
echo "today is good day, data: $(data)"

sometimes show:
2017年 4月 6日 星期四 23时04分25秒 CST
today is good day, data: 2017年 4月 6日 星期四 23时04分25秒 CST

sometimes show:
today is good day, data: 2017年 4月 6日 星期四 23时04分25秒 CST
2017年 4月 6日 星期四 23时04分25秒 CST

how  to keep first cmd (echo "$(data)") show on first line (menu bar visible) ?
what make the turn changed ? (1s data flash is ok does not matter)
confused for one of plugin length is changed , before it's plugins jump jump jump...

**Comment by oleander** [comment]
Place `---` between the first and the second row to prevent BitBar from cycling between them in the menu bar. The docs is a bit unclear about this behaviour but it seems like it cycles between each line above `---` once every 5 second according to the source code; [PluginTest.m#L28](https://github.com/matryer/bitbar/blob/aa4dee753105ee887b58e9ddddbbd4a539ed95ac/App/BitBarTests/PluginTest.m#L28).

```
echo "$(data)"
echo "---"
echo "today is good day, data: $(data)"
```
