### ISSUE TITLE
bitbarapp.com expired on 06/08/2017 and is not available at this time.

### ISSUE THREAD

**Issue by sbytnar** [matryer/xbar#418]
Hi,

The BitBar update checker code looks at bitbarapp.com.
Please decide what you are doing with bitbarapp.com and update bitbar appropriately.
https://github.com/matryer/bitbar/search?utf8=✓&q=bitbarapp.com&type=

Thanks,
--Steve

**Comment by matryer** [comment]
@iosdeveloper What exactly is bitbarapp.com used for? Perhaps we can use https://getbitbar.com/ like the main plugins site?

**Comment by iosdeveloper** [comment]
@matryer Used to host the Sparkle feed using mackuba/sparkler.

**Comment by matryer** [comment]
Can we use feed.getbitbar.com?

**Comment by oleander** [comment]
You wont be able to send updates to your current users if you leave the current domain expired. I would renew it, then use github pages to distribute the `appcast.xml` file used by Sparkle to retrieve its updates. Newer versions of Sparkle lets us autogenerate a `appcast.xml` (`./bin/generate_appcast`) which can then be served as a static asset by any host; i.e Github Pages.

OS X 10.12 requires all updates to go through an encrypted connection, but Github doesn't support https for custom domains (like feed.getbitbar.com). This security feature can be turn off in the app which would allow the app to download uploads over an insecure connection. Sparkle can then use the DSA signature shipped with the binary to verify it. This would yield the same level of security as using a secure connection (and protect against MITM attacks).

Hope that sheds some light on the situation.

**Comment by iosdeveloper** [comment]
We already have auto-generated Sparkle feeds as per #338. bitbarapp.com was using mackuba/sparkler as a proxy serving it with a Let's Encrypt certificate. Since we use Developer ID signing (instead of DSA signatures), Sparkle checks updated binaries for being signed using the same Developer ID.

**Comment by iosdeveloper** [comment]
@matryer If you decide to register bitbarapp.com, I can provide you the A and AAAA records for the existing instance of macuba/sparkler with all the statistics it collected so far.

**Comment by oleander** [comment]
Tomato, Tomato :) What i ment was that, as long as the application is signed, transporting it over a secure connection is redundant. Use feed.getbitbar.com to serve the updates directly from github without a proxy in between.

bitbarapp.com still needs to be renewed tho, unless you want to loose all your users.

**Comment by stefanlasiewski** [comment]
Hello folks, I just started using BitBar recently and came across this error. In addition, for those of us who use SSH 

```
May  4 16:39:05 mac BitBar[837]: Sparkle: ===== BitBar =====
May  4 16:39:05 mac BitBar[837]: Sparkle: Error: An error occurred in retrieving update information. Please try again later. A server with the specified hostname could not be found. (URL https://bitbarapp.com/feeds/bitbar)
May  4 16:39:05 mac BitBar[837]: Sparkle: Error: A server with the specified hostname could not be found. (null) (URL https://bitbarapp.com/feeds/bitbar)
May  4 16:39:12 --- last message repeated 1 time ---
```

**Comment by matryer** [comment]
@iosdeveloper I bought the domain
