### ISSUE TITLE
Add Support for iMessage

### ISSUE THREAD

**Issue by frakman1** [matryer/xbar#423]
A  iMessage call from terminal takes the form of:

```
osascript -e 'tell application \"Messages\" to send \"Hello World\" to buddy \"123123123\" of service \"SMS\"'
```

There are too any parameters to pass into bash. 

- Is there a way to do this with the current implementation?
- If not, can you please add this feature?

**Comment by oleander** [comment]
Take a look a this issue; https://github.com/matryer/bitbar/issues/415#issuecomment-304750938

**Comment by frakman1** [comment]
Forgive me for not understanding, but how this is related?

**Comment by oleander** [comment]
You can use the example I provided (`sudo` & `bash`) to call your example above.

**Comment by frakman1** [comment]
My python script that sends the  iMessage does so in response to clicking an entry so it  has to be part of the `| bash=` syntax of the `print` command. How can I put a super long command like that in there?

**Comment by oleander** [comment]
See if you can get started with my example and I'll help you with the details. Something like `bash="/bin/bash" param1="-c" param2="osascript -e ...."` should work.

**Comment by frakman1** [comment]
Oh really? I can put everything in the param2 slot? Cool. I'll give that a shot.

I actually hacked up the code to support a `imsg` command with two paramters. One for the message and one for the number. It was easier than I thought since I just copied the code that handled calling the Terminal command. Conveniently, it uses AppleScript for the `terminal=true` case.

Perhaps it is unnecessary but if people think it's useful, I could issue a pull-request with it.

**Comment by frakman1** [comment]
Re-Opening this issue to highlight that returned text input value from an osascript to open a dialog box causes an error when an apostrophe is used. See detailed comment/notes [here](https://github.com/matryer/bitbar/issues/172#issuecomment-312988690)

**Comment by WeibingChen17** [comment]
Have you tried docstring? 
```
sendAMessage = '''
osascript -e 'tell application "Messages" to send "Hello World" to buddy "123123123" of service "SMS"'
'''
os.system(sendAMessage)
```
