### ISSUE TITLE
How to make menubar content always be in dark mode?

### ISSUE THREAD

**Issue by frakman1** [matryer/xbar#426]
I have given up on trying to make my menu colors look good in regular, non-dark menu bar theme.

So my question is this:

 **Is there a way to force the menu content (everything under the menu bar icon) to be in dark mode?**

 If so, could someone please point me to some code that will accomplish this and where in the BitBar project I would add this? I don't mind making this change locally and only to my special build.

**Comment by iosdeveloper** [comment]
I think this is a system(-wide) setting out of control of the app.

**Comment by iosdeveloper** [comment]
If you don't set a color it will always look good. 😛

**Comment by frakman1** [comment]
I think I need to call something like this. I'm just not sure what!haha I don't see a popover anywhere in the code.

```objective-c
self.appearance = [NSAppearance appearanceNamed:NSAppearanceNameVibrantDark];
```

Any ideas anyone?

**Comment by frakman1** [comment]
I know it's possible to do this, I see sample code all over gighub but I'm not that good at objective-c to tell what view to change to make it happen.
