### ISSUE TITLE
embedded images are size-limited

### ISSUE THREAD

**Issue by frakman1** [matryer/xbar#432]
When I use the `| image=` syntax to embed an image in a submenu, the image is thumbnailed and stunted in size instead of being full-size. This is fairly large image, 1024x768. The text in the image is unreadable unless it is made bigger.

Is this a Apple thing or something that is controlled by the code?

I don't see anything in the `createImageFromBase64` function that controls size but I could be missing something.

**Comment by JayBrown** [comment]
I have the exact opposite problem. In this case I just grabbed an application icon's (.icns) via reading the app's Info.plist, sent it through `base64`, and embedded it with `some string | image=$appicon`. However, the size is **way too big**. I basically want it to be of the same size as the default menu font.

Anyone know how to resize (in this case: size down) images?

![snap](https://i.imgur.com/nqzilKO.jpg)

**Comment by JayBrown** [comment]
Found a workaround.

```
sips -Z 32 "$appiconloc" --out /tmp/"-$appname" &>/dev/null
appicon=$(base64 -i /tmp/"$appname" 2>/dev/null)
```

It would be lot nicer, though, if you could write `sips` output to stdout… but that doesn't seem to be possible, so you have to write to disk. 😕

![snap](https://i.imgur.com/uqhrO5c.png)

**Comment by frakman1** [comment]
@JayBrown 
Boy, wouldn't it be great if there was a way to instruct BitBar of the size you want the image to be? 
Well, I accepted the challenge and decided to implement this feature since it wasn't that hard. Now I can do something like:

```python
print " text | image={} width=32 height=32".format(icon)
```

and it will resize the image appropriately.

Is this something you could use?

**Comment by JayBrown** [comment]
That would definitely be better. I could run image files through `base64` directly, in their original size, and just tweak width & height in the script.

But wouldn't BitBar have to be updated for that? And would it work in zsh/bash?

**Comment by frakman1** [comment]
Correct, you would need a new BitBar. I am assuming you are able to build it from source. I can share the source in a fork of BitBar in a new branch in my repo.

**Comment by JayBrown** [comment]
That's probably not a good idea, because I'll need this functionality for distribution, so it has to work with the standard BitBar release. But if BitBar development picks up again—fingers crossed! Swift rewrite?!—, it should definitely be implemented.

**Comment by frakman1** [comment]
Understood. I made a pull-request for this feature so it can be incorporated one day.
You can find it [here](https://github.com/matryer/bitbar/pull/577)

**Comment by JayBrown** [comment]
Is that resolution-agnostic? I'm asking because if you use `sips` to reduce the size, it's different for legacy 72ppi images than for 144ppi Retina images. So e.g. a Retina image resized to 32*32 neatly fits into the menu on a Retina screen, but if it's a 72ppi image, 32*32 is way to big, and you need to go even lower to 16*16.

**Comment by frakman1** [comment]
I don't know. There were a ton of implementations that use extensions and what-not. This was the simplest.
Can you post the base64 array of an icon and I will test it?

**Comment by frakman1** [comment]
Looks like it works for `144ppi` at `16x16`. Since [144ppi](https://nicedoc.io/matryer/bitbar) is the BitBar recommended resolution, I am going with this.

Using this as a test icon (look familiar? 😊 ) :

![image](https://user-images.githubusercontent.com/5826484/93718077-b23fd900-fb47-11ea-8ff1-6ee3bf693fdf.png)

```python
testicon = 'iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAB3RJTUUH5AkUEQsL+qiYiQAAATRJREFUWMPt2DFLw1AUBeBzGqXEQguCoqWDipObIv4Guzagf9FF1/pLdNJsCqkKVihWW0+HanqTpkVohw73bi/vkPe9m0wX8JpftAsBmiy0TnKQ2Ze2iGYyyberJD9ymbAWxb2/9fv1fp3kcy5DDPmTPgh0RPIeAEqFGAAgvyWF5iXHFjO+TbMrqW4yOxYDALUofpJ0ajLlDAYAhrxLkuQi7dAUJtvCcRd1rtl9viUAVFuPMzPdm4PxWYM5Z62BpYU/em+oZf5Di4M2Aq4WaMnlIAc5yEEOcpCDHOQgBznIQQ5aAdBXv98q3JUqZtJxUhhBu2EmHbtFmZerxpmZdIRFmc5bcpkOG36nEnsgY4MJyOyUQtIm0Xw1mArJXi5TrkXxp0Fuk+xMXcQOHQIdknyA1z9qBO2FeWRAq484AAAAAElFTkSuQmCC'
```
It renders the same size in the menus as long as I use 16x16 (same code on both Macs):
```python
display("Local Docker | image={} width=16 height=16".format(testicon))
```
![image](https://user-images.githubusercontent.com/5826484/93718037-74db4b80-fb47-11ea-98bb-21e24bc9c4f1.png)

**Comment by JayBrown** [comment]
This is how I'm doing it: 32*32 at 144dpi… looks fine.

![snap](https://i.imgur.com/ydZFcBw.png)

I had one icon that the script converted on the fly, which was 72dpi, and 32*32 was too big, so I'm now using `sips` to check the resolution first, and then converting either to 32*32 or 16*16.

**Comment by JayBrown** [comment]
Though when you use 11p font size, the text tends to be offset, so in the case below I had to reduce the icon size to 28x28. But you might also be able to do it with 32x32, and just some padding of 4–6 pixels. Will have to test that.

![snap](https://i.imgur.com/q21isTx.png)

**Comment by frakman1** [comment]
I don't understand why yours are at 32x32 at 144ppi and mine is at 16x16 at 144ppi?
When I try 32x32, it's twice as large and too big for the menubar:

![image](https://user-images.githubusercontent.com/5826484/93729613-4c793e80-fb93-11ea-87a7-4703de3620be.png)

**Comment by JayBrown** [comment]
I might be wrong, but isn't 32x32 at 144 ppi the same "display size" as 16x16 at 72 ppi?

**Comment by JayBrown** [comment]
Tested it, and it seems that way. In macOS Preview: original 144/32x32 above at 100% size. And converted 72/16x16 at 100% size below.

![snap](https://i.imgur.com/DhYxfQi.jpg)
