### ISSUE TITLE
Better behavior for two lines of text in menu bar

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#437]
Wouldn't it be easy to improve the option to show two lines of text in the menu bar?

Say there's the initial line `echo -e "Text String\nOther Text String"`

BitBar will not center the text, and it will not adjust the font size to auto-fit the two lines in the menu bar.

You can always say `echo -e "Text String\nOther Text String" | size=10`, but line spacing is messed up, so it doesn't look good. Furthermore, there doesn't seem to be a way to tell BitBar to center both lines of text.

So the idea for a feature enhancement is for BitBar to auto-adjust the font size and line spacing, if it encounters a `\n` in the initial echo-line, and some form of option to center, left-align or right-align the text strings.

The latter would be related to [**#429**](https://github.com/matryer/bitbar/issues/429)

**Comment by frakman1** [comment]
@JayBrown 
Did you ever figure out how to indent/align text?
I'm trying to dump some json data. It looks good on the terminal:
```json
{
  "status": "OK",
  "rows": [
    {
      "elements": [
        {
          "duration": {
            "text": "17 mins",
            "value": 1011
          },
          "distance": {
            "text": "10.8 mi",
            "value": 17377
          },
          "duration_in_traffic": {
            "text": "18 mins",
            "value": 1050
          },
          "status": "OK"
        }
      ]
    }
  ],
```
But looks ugly in the menubar
![image](https://user-images.githubusercontent.com/5826484/88980859-93813c80-d292-11ea-929b-c14c6b4a5545.png)

**Comment by JayBrown** [comment]
I haven't looked into that for quite some time, but as far as I recall, I didn't manage to make this work.

```
echo -e "\ttest"
echo "   test"
echo -e "\ua0\ua0\ua0test"
```

all work in Terminal, shell scripts etc., but not in BitBar.

**Comment by frakman1** [comment]
I finally got it to work! Woo Hoo. Game changer!

![image](https://user-images.githubusercontent.com/5826484/89239943-b1b7a700-d5c8-11ea-9f86-87bd94cf6cb8.png)

The trick was to use an invisible character between the dashes for the indent (or whatever) and the actual variable holding the text. It may not copy/paste correctly on here but you can copy paste them from somewhere online which is what I did.

```python
print("----" + '‎‎' + line + "| color=white size=11 font='Courier New'")
```

**Comment by frakman1** [comment]
Looks good in color too:

![image](https://user-images.githubusercontent.com/5826484/89240980-b03bae00-d5cb-11ea-9d16-44c03a29d2f7.png)

**Comment by johnoscott** [comment]
Oh wow - that does look good. Hey @frakman1 can you share the code for this ?

**Comment by frakman1** [comment]
@johnoscott Sorry for the delay. I was still working on the code. Although not really happy with it, I have put a ribbon on it and declared it feature-complete as of now. You can find it [here](https://github.com/frakman1/bitbar-plugins/blob/dockerinfo/Dev/Docker/dockerinfo.365d.py). Feel free to suggest any improvements on the formatting. I still can't get everything to line up reliably.
