### ISSUE TITLE
Vertical text?

### ISSUE THREAD

**Issue by Henrietta1989** [matryer/xbar#444]
I have working script but i would like to show four digit number vertically in menubar (not in dropdown menu) to save menu space. Me and many others have lots of apps running in menubar so it would help if numbers are vertically or if user could put 2-3 rows of tiny numbers instead of just one row of big numbers.

Now it shows:
1234

I would like to have like this and width of menu is as narrow as possible:
1
2
3
4

or

1234
34.5
5.6

or

1  3  5
2  4  .
3  .   6
4  5

**Comment by iosdeveloper** [comment]
You can do this in v2 thanks to #324.
