### ISSUE TITLE
How to run coffee script shebang?

### ISSUE THREAD

**Issue by kithokit** [matryer/xbar#445]
In your document, the coffeescript is supported by doing some hack.

I am not able to follow based on your documents.

Can you show us the example on how to run coffeescript files using bitbar?

**Comment by Chandler-Davidson** [comment]
I agree that the documentation is a bit misleading. A much simpler fix would be to compile to JS and then test your plugin. For CoffeeScript, your shebang will look similar to this: `#!/usr/local/bin/node /usr/local/bin/coffee
`. Simply the path to Node, then the path to CoffeeScript.
