### ISSUE TITLE
use python {:-10.2f} to do fixed width but not working

### ISSUE THREAD

**Issue by leewi9** [matryer/xbar#448]
![image](https://user-images.githubusercontent.com/10832544/32035438-d273da54-ba4b-11e7-99ba-70e7695f1371.png)

1、fixed width for the entire bitbar 
2、set the margin-top 
3、fixed width for the line, i tried `print` with `format` `{:-10.2f}` but it seems not ideal (check the screenshot)

**Comment by leewi9** [comment]
Mac OS X 10.12 Sierra

**Comment by leewi9** [comment]
![image](https://user-images.githubusercontent.com/10832544/32036761-4c17c246-ba54-11e7-8b47-475476028a04.png)

it's ok now, this can be closed.

**Comment by gingerbeardman** [comment]
I guess you needed to specify a fixed width font?
