### ISSUE TITLE
Flag emojis codes are not rendered

### ISSUE THREAD

**Issue by saisasidhar** [matryer/xbar#451]
Emoji codes like `:in: :de: :jp:` etc are not converted into corresponding Unicode characters (🇮🇳 🇩🇪 🇯🇵). Although all flag emojis are available in mac and are listed in the Character Window.

Tested on macOS 10.12.5

**Comment by frakman1** [comment]
If it makes a difference, you can copy and paste the emoji directly into the script and it will render properly in the bitbar app. I am on macOS 10.12.6
