### ISSUE TITLE
Feature Request: I want to be able to set the refresh time to less than a second, for example to 200ms

### ISSUE THREAD

**Issue by pablo-zocdoc** [matryer/xbar#452]
By having a faster refresh time suddenly bitbar becomes a great way to get feedback from macros or commands that otherwise would require a full blown macOS notification (one of those popups that appear on the right side of the screen).

It will serve as a subtle way to display notifications or errors from your commands.

You would configure your scripts similarly to how you do it now but instead of let's say writing 1s you would write 300ms in the script name.

**Comment by mikemintz** [comment]
I was able to achieve this naming my script `something.2e-1s.py`. As long as your number is a valid floating point number and doesn't have a period, like `2e-1`, it seems like it should work.

**Comment by FusionX13** [comment]
> I was able to achieve this naming my script `something.2e-1s.py`. As long as your number is a valid floating point number and doesn't have a period, like `2e-1`, it seems like it should work.



> By having a faster refresh time suddenly bitbar becomes a great way to get feedback from macros or commands that otherwise would require a full blown macOS notification (one of those popups that appear on the right side of the screen).
> 
> It will serve as a subtle way to display notifications or errors from your commands.
> 
> You would configure your scripts similarly to how you do it now but instead of let's say writing 1s you would write 300ms in the script name.

I had a feeling that's why it wouldn't be put in.

**Comment by frakman1** [comment]
Can someone give me an example of why you'd need a notification that's more than one second frequency?

**Comment by mikemintz** [comment]
It's less about frequency and more about latency. I use bitbar to display a list of open macos spaces and highlight the active space. When I switch to a new space, I like immediate feedback in the bitbar display rather than waiting a second for it to update.

**Comment by frakman1** [comment]
MacOS Spaces? Is that like a workspace at the top bar? I never use that, but I'd like to see what you mean by "highlighting the active space". Can you post a screenshot please?

**Comment by mikemintz** [comment]
Yeah, showing the workspaces on the top bar. Here's a screenshot with 3 open spaces and the second one is focused: ![](https://paper-attachments.dropbox.com/s_1A0E4DCE5F0AC94896002426CEDB0A17A5A4C2C63334266F9A923554B3F3E99C_1596909825750_image.png)
