### ISSUE TITLE
Long running scripts get duplicated

### ISSUE THREAD

**Issue by fabiospampinato** [matryer/xbar#456]
bitbar v2-beta10. 

If I run the `Refresh All` action all my long-running scripts get duplicated. There's no problem with short-lived scripts.

Am I supposed to kill the old processes by myself or something?

**Comment by hallyn** [comment]
me too - i have two timer plugins up right now.

**Comment by gingerbeardman** [comment]
you could set an environment variable at the start of your script and clear it at the end. then in your script you can check if it's set and exit your script early rather than running it again.

ideally, this sort of check would be done in BitBar but at least it would be a workaround.

**Comment by fabiospampinato** [comment]
@gingerbeardman thanks for your suggestion, although I'm not sure it would actually work. It would ensure that only the old version of the script is running instead of both the old and the new, but I want the new version to be running, that's why I'm refreshing it in the first place. 

I think simply by incrementing that environment variable on the new script, and checking if its value changed on the old, and in that case exiting, would do the trick. 

If v2-beta10 didn't have any other deal breakers for me I would think about implemented this.

**Comment by garyking** [comment]
There are possibly multiple scenarios that would cause a plugin to duplicate, but I had one plugin that ran every 5 seconds and it would get duplicated, and changing it to 10 seconds fixed that.

I have another plugin that runs every 1 second, but it doesn't get duplicated, so as I said, there are probably several factors at play.

**Comment by kabar1** [comment]
I have the same problem.
