### ISSUE TITLE
BitBar process has a constant CPU usage (of ~1%) even when idle

### ISSUE THREAD

**Issue by daniele-orlando** [matryer/xbar#457]
Platform: MacOS 10.13.2
Version: 1.9.2

```
Given BitBar with 2 plugins installed with a refresh interval of 10 minutes each
Then the BitBar expected CPU usage should be 0% during the idle time
And should raise only when the 10 minutes elapse.
```

Current implementation of BitBar has a notable impact on the battery usage.

![ps](https://user-images.githubusercontent.com/504386/35230524-8f1f8efc-ff96-11e7-881b-92cfaf20e42e.png)

**Comment by jefflenz** [comment]
Any updates to this?  I'm noticing this as well.  Why is CPU so high for an idle bitbar?

**Comment by gingerbeardman** [comment]
I built the current code and ran it through Instruments, and nothing looked obviously wrong. Most time is spent system calls on the Main Thread:

- NSApplication, 75% of the time
  - CFRunLoop, 60%
    - Observers, 25%
    - Timers, 20%
    - Queue, 15%

I had a quick look through the code and I have seen slightly better CPU usage by changing:

https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L80
from
`DISPATCH_QUEUE_PRIORITY_DEFAULT`
to
`DISPATCH_QUEUE_PRIORITY_BACKGROUND`

Feel free to try that and report back?
