### ISSUE TITLE
 Is there a way to display a literal pipe symbol ("|") in a plugin?

### ISSUE THREAD

**Issue by mdbraber** [matryer/xbar#461]
I can't get it to show w/ escaping, printing ASCII sequences or other... Any other ideas? @

**Comment by JayBrown** [comment]
You're right, I just tested it. `echo "\x7c"` (zsh) and `printf "\x7c\n"` (bash) don't work. **I think printing ASCII as literal glyph/symbol should be added as a feature in a BitBar.** (In my humble opinion.)

Until then I assume it's better to use alternative symbols; here are some

```
echo "Test ∥ Test │ Test ┃ Test |"
```

1. parallel
2. box drawing light vertical
3. box drawing heavy vertical
4. pipe

I believe no. 2 & no. 3 are preferable, although they are a little longer than the actual pipe symbol.

Anyone with a different idea?

**Comment by m-cat** [comment]
The literal pipe seems to be parsed by BitBar:

> Your lines might contain | to separate the title from other parameters

You should be able to add escaping for this symbol (e.g. something like "\|")in a PR.

**Comment by gingerbeardman** [comment]
OP and myself have tried escaping pipe like that but it doesn't work @m-cat

**Comment by m-cat** [comment]
I meant that you need to add escaping to BitBar itself (i.e. add parsing for \\|) in a PR. Have you tried this as well?

**Comment by JayBrown** [comment]
Not sure if that would be successful. Programmatically yes, but it seems that BitBar development has ended, so a PR would be ignored.

**Comment by gingerbeardman** [comment]
@JayBrown I have permission to merge PRs 👍

**Comment by m-cat** [comment]
@gingerbeardman Are you able to make new releases as well? (e.g. to download from getbitbar.com) Glad it's not a dead project, the idea is very cool but there are a few annoying bugs like #105.

**Comment by gingerbeardman** [comment]
@m-cat yes, I'm looking into a few PRs that would make a difference for a new release. If you can fix that one, I'll happily merge and release

**Comment by m-cat** [comment]
@gingerbeardman and I'll happily try to fix this when I have time :) Thanks!

**Comment by vandreykiv** [comment]
Hey, any updates on this? Thanks

**Comment by m-cat** [comment]
I no longer have time to work on this project. Hopefully someone else can get to this issue though.

**Comment by MatthewScholefield** [comment]
A simple workaround for is to pipe the outputs of your script through `perl -pe 's/\|(?![^|]*$)/║/gm'`. Note this assumes you always have a final bar with some valid labels. For example:

```console
$ echo "This is the text | that includes | bars... | href=https://google.com" | perl -pe 's/\|(?![^|]*$)/║/gm'
This is the text ║ that includes ║ bars... | href=https://google.com
```

**Comment by IdiosApps** [comment]
I found this issue about displaying pipe / vertical bar / bar / vbar (using alternative names for SEO to find this).
In terminal, printing vbar is OK:
```bash
echo "a | b"
a | b
```

If you have this in a xbar script:
```
#!/bin/bash
echo "a | b"
```
xbar will say `malformed parameters: missing equals`.

As a workaround (I don't have the time to raise a PR to fix this), I am using `echo a ‖ b`. xbar is happy with this, and it looks OK.
Just realised the above comment is suggesting similar, nice one @MatthewScholefield

**Comment by spnw** [comment]
I found another alternative to the pipe character: `ǀ`
