### ISSUE TITLE
Print multiple images in one line?

### ISSUE THREAD

**Issue by bridger217** [matryer/xbar#462]
I'm writing a sports scores plugin that I want to display both team logos along with their scores in the menu bar. Right now I can only display one, any tips? (using Python 3)

**Comment by fabiospampinato** [comment]
I'm not sure if there's any other way of doing it with bitbar, but you could create a new image and put the 2 logos in there, same for the scores, and then just display that single image.

**Comment by bridger217** [comment]
how can I create a variable image in python that I can then encode into b64?

**Comment by fabiospampinato** [comment]
I don't know, you should look that up on Google, I'm sure somebody else had to face a similar problem.

**Comment by kassio** [comment]
Was this solve? Can I have multiple images on a submenu?
