### ISSUE TITLE
Ideia: a plugin to add a note to Apple Notes app

### ISSUE THREAD

**Issue by leninebike** [matryer/xbar#466]

**Comment by frakman1** [comment]
Nice Idea. 

I was able to get this to work in a prototype build. I 'll see if I can get a plugin made (never made one before)

**Comment by leninebike** [comment]
That would be great. I already managed to do something a little easier: created a simple plugin with a nice icon to launch the Apple Notes from the menubar. I’ll upload it as soon as I learn a little bit how Github works.
