### ISSUE TITLE
Is it possible to have 2 colors in the menu bar

### ISSUE THREAD

**Issue by ausinha** [matryer/xbar#467]
can I have part of status in the menu bar in blue, and another part in red?

**Comment by jasonm23** [comment]
yes.

**Comment by jasonm23** [comment]
Can you go into more detail of what you want, maybe provide a mockup

**Comment by ausinha** [comment]
Attaching a mock up. In the far left, you will see 0:14 (in red) and 16 (in orange). currently I wrote 2 different scripts to get this effect. Is it possible for a single bitbar script to product a menu bar item with more than 2 colors.
![mockup](https://user-images.githubusercontent.com/359261/39403295-fd744f8c-4b45-11e8-9993-0b8393ae224d.png)

**Comment by jasonm23** [comment]
Cool, thanks for the mockup.

Ok, so good news is, it's totally possible.   There's no real bad news, aside from the fact that ansi is how you set colors.

Try this ... (it'll work on any menu item or on the top item)

```
echo "\e[30mA\e[31mA\e[32mA\e[33mA\e[34mA\e[35mA\e[36mA\e[37mA\e[40mA\e[41mA\e[42mA\e[43mA\e[44mA\e[45mA\e[46mA\e[47mA | ansi=true "
```

the numbers:

`30 - 37` = foreground color - black, red, green, yellow, blue, magenta, cyan, white
`40 - 47` = background color - black, red, green, yellow, blue, magenta, cyan, white

To combine foreground and background just do:

`\e[37;42m` - e.g. White text on green background.

**Comment by jasonm23** [comment]
There's a lot of guides on ANSI color codes like this one:

http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html 

In their examples `\u100b` is the same as `\e` in my example.

It's the ESC control code.

For a deep dive read up in  https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by jasonm23** [comment]
FYI default background and foreground colors can be selected with 39 and 49... e.g.

`\e[39m` - default foreground
`\e[49m` - default background

**Comment by ausinha** [comment]
Conceptually I get it, I have a fancy colored bash prompt using ANSI colors. However, your example and my own simple example doesn’t work, I get no colors. E.g., the following doesn’t give a color:

> print(u'\u001b[38;5;27m blue \u001b[38;5;9m red | ansi=true')

**Comment by ausinha** [comment]
Conceptually I get it, I have a fancy colored bash prompt using ANSI colors. However, your example and my own simple example doesn’t work, I get no colors. E.g., the following doesn’t give a color:

`print(u'\u001b[38;5;27m` blue \u001b[38;5;9m red | ansi=true')

When I run it as a standalone script, I do see the colors.

<img width="682" alt="screen shot 2018-04-29 at 11 11 45 am" src="https://user-images.githubusercontent.com/359261/39408041-2225b4b2-4b9e-11e8-8c8b-84947bec1464.png">

**Comment by jasonm23** [comment]
Please note above where I mentioned xterm256color and 24bit extended color codes **aren't** supported.

Any 38;5 or 38;2 stuff won't work.

**Comment by jasonm23** [comment]
(that goes for 48;2 and 48;5 of course too.)

**Comment by jasonm23** [comment]
What happens if you do:

```
print(u'\u001b[34m blue \u001b[31m red | ansi=true')
```

**Comment by jasonm23** [comment]
LGTM in terminal:

<img width="851" alt="screen shot 2018-04-30 at 8 43 49 am" src="https://user-images.githubusercontent.com/71587/39412666-a11cd25a-4c52-11e8-9ad9-868d4a195d48.png">

In BitBar...

<img width="121" alt="screen shot 2018-04-30 at 8 50 44 am" src="https://user-images.githubusercontent.com/71587/39412722-9e05f8de-4c53-11e8-8c35-3c4bf0756fb1.png">


Seems fine.

**Comment by jasonm23** [comment]
FYI I actually used 36 (cyan) instead of 34 (blue) in my bitbar test.

**Comment by jasonm23** [comment]
<img width="108" alt="screen shot 2018-04-30 at 8 52 44 am" src="https://user-images.githubusercontent.com/71587/39412754-dea71120-4c53-11e8-9e7e-cd546cb0bb2d.png">

**Comment by ausinha** [comment]
It works, thanks!

**Comment by m-cat** [comment]
Hi, how would we do this in bash (and not Python)?

I tried this code from above but it doesn't work:

```
echo "\e[30mA\e[31mA\e[32mA\e[33mA\e[34mA\e[35mA\e[36mA\e[37mA\e[40mA\e[41mA\e[42mA\e[43mA\e[44mA\e[45mA\e[46mA\e[47mA | ansi=true "
```

Thanks!

**Comment by gingerbeardman** [comment]
Try this https://misc.flogisoft.com/bash/tip_colors_and_formatting @m-cat

**Comment by m-cat** [comment]
Thanks, I got it to work with that syntax, for colors at least. `\\e` doesn't work and neither do bold, underline etc. I guess for bold I have to use `font=LucidaGrande-Bold`.

@ausinha , I think this Issue can be closed :)

**Comment by gingerbeardman** [comment]
bold works using this syntax:
`echo -e "Normal \033[1;1mBold \033[0;21mNormal"`

you can also use `tput`, example:
```
bold=$(tput bold)
normal=$(tput sgr0)
echo "this is ${bold}bold${normal} but this isn't"
```

please post your final code here to help others

**Comment by m-cat** [comment]
Neither of those examples work for me :/

> please post your final code here to help others

Oh, I basically did almost the same thing as in your Hello World example:

```
echo -e "\\033[31mTrack\\t$track"
```

**Comment by gingerbeardman** [comment]
Indeed, they work in Terminal but not in a bitbar test script. Hmm.

**Comment by jasonm23** [comment]
Just for reference this is only three ways to represent the same character.

- `\e` is a convenient way provided by Bash to insert the Escape character. (although it can depend on the version of bash/echo (`-e` is usually not needed, but it's the best way to get escape chars recognized in `echo` _usually_) 

The ASCII char for Escape / Esc is `27` in decimal, however you can't convert directly from decimal to a char in Bash†

* `\033` is 27 as octal (base 8) we can use that directly in bash strings.

* `\0x1B` is 27 as hex/hexadecimal (base 16) we can also use that in bash strings.

We can do this... 

```
echo "\x1b[32mHello \e[33mOh hai \033[34mHow are you?"
```

or perhaps 

```
echo -e "\x1b[32mHello \e[33mOh hai \033[34mHow are you?"
```

Depending on the shell version in use.

**Comment by jasonm23** [comment]
If you find `echo` is giving you trouble, it's often better to use `printf`.

`awk` is also a good way to format strings, but at that point, just switch up to Python, Ruby or Perl.
