### ISSUE TITLE
Single dock icon, multiple script executions.

### ISSUE THREAD

**Issue by m-denton** [matryer/xbar#476]
I would like to have a single icon in my dock that when clicked, has multiple submenu scripts that can be invoked individually. I have gotten close but so far, it seems they are all updated. Is there a common way of doing this? I have tried (unsuccessfully) multiple echo "Result: $fn_result|bash=$0 param1=script1 refresh=false" where $fn_result is something like:

```
if [[ param1 == "script1" ]];then
    func1()
fi
func1(){
    fn_result="🍎"
}
```

Not sure the best route for this.

**Comment by gingerbeardman** [comment]
Have a look at this plugin, it may be of some help: https://github.com/matryer/bitbar-plugins/blob/master/Dev/GitHub/notifications.30s.py

**Comment by m-denton** [comment]
Do you have a screenshot of this plugin in action?

**Comment by gingerbeardman** [comment]
Not right now, but I'll post one next time i get a notification.

It has different menus items which respond to alt, and each do different things (mark all as read, or mark individual as read).

**Comment by m-denton** [comment]
Would be very much appreciated!

**Comment by gingerbeardman** [comment]
with no modifier keys held:
![screen shot 2018-05-31 at 14 59 52](https://user-images.githubusercontent.com/49612/40786768-c62e5a7e-64e3-11e8-8167-03f617d1a73b.png)

whilst pressing alt:
![untitled](https://user-images.githubusercontent.com/49612/40786771-c7ff69b0-64e3-11e8-98fc-20ac6ce29c89.png)

**Comment by m-denton** [comment]
Very cool, can you dumb down the mockup to bar minimum for getting this functionality?

**Comment by m-denton** [comment]
Essentially what I need to get to is the following where clicking on Prod/Dev/QA on the submenu with run that specific function only and update the submenu icon:

`#!/bin/bash

USER=""
TOKEN=""
BASE_URL=""
#CRUMB=$(curl -s 'http://${USER}:${TOKEN}@${BASE_URL}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
echo "🔥"
echo "---"
prodfunc()
{
    local JOB_NAME=""
    #local RESULT=$(curl -X POST -H "$CRUMB" "http://${USER}:${TOKEN}@${BASE_URL}/job/${JOB_NAME}/build")
    #sleep 5
    local STATUS=$(curl -silent http://${USER}:${TOKEN}@${BASE_URL}/job/${JOB_NAME}/lastBuild/api/json?pretty=true | grep "result" | awk '{print $3}')
    if [[ $STATUS == *"SUCCESS"* ]]; then
        prod='Prod:🍏'
    else
        prod='Prod:🍎'
    fi
}

devfunc()
{
    local JOB_NAME=""
    #local RESULT=$(curl -X POST -H "$CRUMB" "http://${USER}:${TOKEN}@${BASE_URL}/job/${JOB_NAME}/build")
    #sleep 5
    local STATUS=$(curl -silent http://${USER}:${TOKEN}@${BASE_URL}/job/${JOB_NAME}/lastBuild/api/json?pretty=true | grep "result" | awk '{print $3}')
    if [[ $STATUS == *"SUCCESS"* ]]; then
        dev='Dev:🍏'
    else
        dev='Dev:🍎'
    fi
}

qafunc()
{
    local JOB_NAME=""
    #local RESULT=$(curl -X POST -H "$CRUMB" "http://${USER}:${TOKEN}@${BASE_URL}/job/${JOB_NAME}/build")
    #sleep 5
    local STATUS=$(curl -silent http://${USER}:${TOKEN}@${BASE_URL}/job/${JOB_NAME}/lastBuild/api/json?pretty=true | grep "result" | awk '{print $3}')
    if [[ $STATUS == *"SUCCESS"* ]]; then
        qa='QA:🍏'
    else
        qa='QA:🍎'
    fi
}
if [ "$1" = 'prod' ]; then
    prodfunc
elif [ "$1" = 'dev' ]; then
    devfunc
elif [ "$1" = 'qa' ]; then
   qafunc
fi

echo "$prod | bash=$0 param1=prod refresh=false"
echo "$dev | bash=$0 param1=dev refresh=false"
echo "$qa |bash=$0 param1=qa refresh=false"`
