### ISSUE TITLE
Running bitter over login window

### ISSUE THREAD

**Issue by AllPurposeBen** [matryer/xbar#478]
Is it possible to run bitbar over the login window? I manage several student Mac labs and it would be helpful for non-IT staff lab monitors/instructors to be able to check the status of a few things (if our software update system has pending updates, last logged in user name, etc) at a glance without having to log into a user account. 

Is that feasible? Maybe calling the bitbar binary with a loginwindow session launch agent?

**Comment by matryer** [comment]
I don’t know about that. I’ll poke around and see if there’s any hope. Typically, Apple tends to be quite restrictive, so my guess is No.

Regards,
Mat

---

Mat Ryer
Machine Box

WEB: https://machinebox.io/
SLACK: https://machinebox.io/slack
BLOG: https://blog.machinebox.io/
TWITTER: @machineboxio
