### ISSUE TITLE
Can't get python scripts to work ..

### ISSUE THREAD

**Issue by sjmcdowall** [matryer/xbar#482]
I am trying the slack python script -- but it complains that I haven't "pip install requests" .. but I HAVE installed it ... and the script runs fine from my command terminal (iterm2) etc. 

The problem appears to be the minimal environment that is "setup" when we execute the scripts -- I am not sure how we execute a script with what shell, etc. but I created a simple test.sh plugin that dumps the ENV to a file .. and it's very minimal with not all the paths, etc. that are there when I launch a terminal window or a new tab, etc. in my terminal window... 

This is Mac OS -- I use ZSH for the shell and oh-my-zsh .. but .. I looked in /etc/paths and there is a nice list of paths there -- but they aren't in the PATH env either... 

The start of the python script is:
```
#!/usr/bin/env python
# coding=utf-8
#
# <bitbar.title>Slack Notification</bitbar.title>
# <bitbar.version>v1.1</bitbar.version>
# <bitbar.author>mgjo5899</bitbar.author>
# <bitbar.author.github>mgjo5899</bitbar.author.github>
# <bitbar.desc>Displays number of unread Slack messages</bitbar.desc>
# <bitbar.image>https://i.imgur.com/I3MdNmU.png</bitbar.image>
# <bitbar.dependencies>python</bitbar.dependencies>
#
# by mgjo5899
try:
	import requests
except ImportError:
	print('You need to `pip install requests`')

import json
```

Again, this runs just fine if I do a "./slack-msg.1m.py" .. but errors with the "You need to 'pip install requests'" when run in Bitbar .. 

So obviously my "shell" environment isn't normal or correct -- but there isn't much doc on how exactly BitBar attempts to execute this stuff... 

Here is the output from my little "test.sh" dumping the environment:
```
PATH=/usr/bin:/bin:/usr/sbin:/sbin
TMPDIR=/var/folders/2_/t69bm8252ks2086cwkvn_6ww0000gn/T/
LOGNAME=sjm
HOME=/Users/sjm
XPC_FLAGS=0x0
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.IX1O2MQMy4/Render
USER=sjm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.iwZAJ2Nthx/Listeners
SECURITYSESSIONID=186a8
DISPLAY=/private/tmp/com.apple.launchd.Z8RSomuX7E/org.macosforge.xquartz:0
XPC_SERVICE_NAME=0
BitBar=1
SHELL=/usr/local/bin/zsh
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHLVL=1
PWD=/
OLDPWD=/
```

Thanks!

**Comment by infothrill** [comment]
you can also write a shell wrapper that takes care of installing a virtualenv including dependencies, then launches the actual python script. Example: https://github.com/infothrill/bitbar-plugin-pingdom/blob/master/bitbar-pingdom.60s.sh
