### ISSUE TITLE
Bitbar ignores Perl @INC path if set for "local::lib" installs - looks for system path instead

### ISSUE THREAD

**Issue by ventz** [matryer/xbar#484]
Hi,

Bitbar seems to ignore Perl's @INC if set for "local::lib" installs.

If you install Perl with brew, it suggests setting up:

```
 PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
 echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.bash_profile
```

So that the perl modules end up in `$HOME/perl5`

Bitbar seems to ignore this and it still looks for them in /usr/local/...location of system perl...

One way to "bypass" that is to force install the module with:
```
sudo cpan -f install $same-module-you-already-installed
```

But it really should read and honor the "local::lib" path if one exists for the user that it's running as.

**Comment by ventz** [comment]
@matryer Was this fixed at some point? (I didn't see a change linked to the close)

**Comment by matryer** [comment]
@ventz This issue was closed automatically when the project switched from BitBar to xbar. Beta testing has started, and since it's a fundamental rewrite from the ground-up in Go, it's unlikely the same issues apply. They may, and we'll make sure things like this are part of our testing.

**Comment by ventz** [comment]
Ah, that's great to hear about the project take over!!

**Comment by ventz** [comment]
@matryer Just read your medium post about how BitBar came to be - that's amazing! :)
