### ISSUE TITLE
How to use with python and a virtual env (ie do not want dependencies in '/Library/Python/2.7/site-packages')

### ISSUE THREAD

**Issue by estysdesu** [matryer/xbar#491]
TL&DR: How can I have my interpreter point to a venv python that way my module has read/write permissions in that folder, but not have issues with formatting (posix_spawn: error 8)

I want to use a virtual env for my BitBar python script. Its actually kind of necessary. I can run it from a virtual environment just fine in the terminal, but when trying to set the interpreter to the one in the environment with the shebang [#!/Applications/BitBar/ScoreBarEnv python] I get a posix_spawn: error 8. This is fixed if I have the shebang [#!/usr/bin/env -S PATH="${PATH}:/usr/local/bin" python] but then my module (even if installed in [/Library/Python/2.7/site-packages]) won't run. 

the module I'm using is nflgame -> the reason it does not like running from /Library/Python/2.7/site-packages is because it needs read/write permissions to a json folder in its site-package.

**Comment by infothrill** [comment]
You can write a shell wrapper that creates a virtualenv, installs dependencies and then runs your program. Example: https://github.com/infothrill/bitbar-plugin-pingdom/blob/master/bitbar-pingdom.60s.sh
