### ISSUE TITLE
`bash` with Ruby and script doesn't work

### ISSUE THREAD

**Issue by garyking** [matryer/xbar#492]
If I have a line like this:

`JavaScript notif|terminal="false" bash="/usr/local/bin/node" param1="/app.js"`

Then it works fine.

If I have a line like this:

`Ruby notif|terminal="false" bash="/usr/bin/ruby" param1="/app.rb"`

Then it doesn't work. 

Yet *both* of the following two commands work if I run them directly in Terminal (or if I change `terminal` to be `true` in BitBar for each command):

`/usr/local/bin/node /app.js`

`/usr/bin/ruby /app.rb`

Why would Ruby not work when Node does? Anyone know what needs to be changed for this to work?

**Comment by garyking** [comment]
Like I said, if I set `terminal` to `true` then the Ruby script works fine.

**Comment by gingerbeardman** [comment]
Please consult the correct usage of the bash attribute in the manual. 

Also see https://github.com/matryer/bitbar/issues/433 , https://github.com/matryer/bitbar/issues/460 etc

**Comment by harryloewen** [comment]
@garyking The terminal is less sensitive, that's why it mostly works there. And I was wrong, ruby and `terminal=false` works perfectly, just needed to use absolute paths, no white spaces, etc

**Comment by gingerbeardman** [comment]
Also consult out the following plugins that use:

1. `bash`
2. `terminal=false`
3. `param1=copy` (`param2` etc)
4. `refresh=false`
5. `terminal=false`

100+ at time of writing
https://github.com/matryer/bitbar-plugins/search?q=bash+%22terminal%3Dfalse%22

< 10 at time of writing
https://github.com/matryer/bitbar-plugins/search?l=Ruby&q=bash+%22terminal%3Dfalse%22

**Comment by garyking** [comment]
Thanks I'll check those out. I already made a workaround for the issue a few weeks ago, though, so this isn't an urgent issue anymore.
