### ISSUE TITLE
Cannot open menu when title has href parameter

### ISSUE THREAD

**Issue by StephenGregory** [matryer/xbar#500]
Bitbar 1.9.2
macOS 10.14.3 

Given this output, it is impossible to view the dropdown items. Clicking or context-clicking on "foo menu" will always open the URL and never reveal the dropdown.

```
echo "foo menu | href=http://somewhere.com/"
echo "---"
echo "You'll never see this"
```

**Comment by gingerbeardman** [comment]
This behaviour is by design.

**Comment by StephenGregory** [comment]
If that is the case, how does one refresh the plugin immediately after they've made a modification to it?

**Comment by gingerbeardman** [comment]
If you don't overload the menubar icon with a href, refreshing is easy. If you choose to overload the icon with href, then you won't be able to refresh on demand. Put a time refresh on the filename, or develop your plugin without the icon overloaded, and only overload it when you've finished development. I'm sure you're aware of all of this

**Comment by StephenGregory** [comment]
> you won't be able to refresh on demand.

That's what I was getting at. Short of killing the Bitbar process, I was wondering if there's a less intrusive way to tell Bitbar to refresh everything (other than the development workflow you mentioned).

If not and there is no desire to support this, you can close this issue.

**Comment by gingerbeardman** [comment]
You can use a second plugin to access refresh?

**Comment by ercumentkisa** [comment]
In this scenario, one can neither open the menu nor manually quit from Bitbar. It would be great to access the menu if you right-click or cmd+click.

**Comment by gingerbeardman** [comment]
@ercumentkisa please start a new issue with that request 👍
