### ISSUE TITLE
Travis CI builds are failing for all PRs since 2017

### ISSUE THREAD

**Issue by sohocoke** [matryer/xbar#504]
There is a queue of PRs with failed CI builds. It seems to be failing for the same reason since 2017 (#431).

An exerpt from #502:
```
$ security import $CERT_P12 -k $KEYCHAIN -P "$CERT_PW" -T /usr/bin/codesign
security: SecKeychainItemImport: One or more parameters passed to a function were not valid.
The command "security import $CERT_P12 -k $KEYCHAIN -P "$CERT_PW" -T /usr/bin/codesign" exited with 1.
```

These kinds of issues tend to be very easy for whomever has originally set up CI to fix. It would be great if the project maintainers around 2017 could have a quick look to see if e.g. $KEYCHAIN and $CERT_PW are valid when the above command runs.

/cc @matryer @iosdeveloper @gingerbeardman

**Comment by matryer** [comment]
I have disabled the CI. Will this help?

**Comment by mpicard** [comment]
I don't think so, look at this build log, it is all green, tests all pass, all commands exit 0 and the end of the build it just decides to exit 1. There is something wrong or it's timing out?

**Comment by sohocoke** [comment]
There's a command failure reported at the early stages of the build, printed in red. My best guess is that the envvar's related to code signing are somehow off.  

@matryer Could you check if $KEYCHAIN and $CERT_PW are valid at build time? If you can't, who can?

**Comment by gingerbeardman** [comment]
Maybe the Developer certificate has expired?

**Comment by Phil0xF7** [comment]
I think the issue is the environment variables used for secrets are restricted to PRs from the main repository only.

According to the Travis CI docs:

https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.
> 
> Pull requests sent from forked repositories do not have access to encrypted variables or data even if these are defined in the fork source project.

A solution could be to disable the code signing parts for PRs since you only need it when creating new releases.
