### ISSUE TITLE
Bold ANSI escape sequence not working in dropdown

### ISSUE THREAD

**Issue by garyking** [matryer/xbar#522]
Does the bold ANSI escape sequence not work in dropdowns in BitBar?

I'm using `\u001b[1m` and it correctly bolds the text when printed to the console, but not when it appears in the BitBar dropdown.

**Comment by gingerbeardman** [comment]
Do you have ANSI switched on for the drop-down item?

**Comment by garyking** [comment]
Yeah, it's on. I tried it with not specifying the ANSI value (which defaults to on), and explicitly specifying as on. ANSI colors work, but not bold.

**Comment by dsemaya** [comment]
I'm seeing the same thing.  Bold and underline won't work for me. Colors do.

**Comment by gingerbeardman** [comment]
I don't think it's supported.

See this example: https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/ansi.sh
