### ISSUE TITLE
Help! Plugin that uses chromedriver not working

### ISSUE THREAD

**Issue by dzg** [matryer/xbar#525]
I've written a plugin in python3 that uses [MintAPI](https://github.com/mrooney/mintapi) – which calls `chromedriver`.
The script works fine from shell, but from bitbar it throws an error "Permission denied: /chromedriver"

Anyone know why?

**Comment by gingerbeardman** [comment]
if it relies on environment variables that are available in shell, they are not available in bitbar plugin. you need to import them, see examples or other plugins
