### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by dzg** [matryer/xbar#526]
I have a line in my plugin:
`Refresh | bash="python3 /Users/zeev/iCloud/bitbar/mint/mint-getData.py" terminal=false refresh=true`
which does NOT run when clicked.
It only runs if I set `terminal=true`

**Comment by dzg** [comment]
anyone?

**Comment by gingerbeardman** [comment]
I am too busy to help right now, but please read the docs and consult other examples.

https://github.com/matryer/bitbar-plugins/search?l=Python&q=terminal%3Dfalse

**Comment by davidsharp** [comment]
I was facing a similar problem this same problem, but just using `open`: `echo "Spotify|bash=open param1=/Applications/spotify.app terminal=false"`, where `terminal=true` works

This is the technique I borrowed from the other plugins I was seeing:
```
if [[ "$1" = "open" ]]; then
  open /Applications/Spotify.app
fi

...

echo "Spotify|bash=$0 param1=open terminal=false"
```

It's not ideal though, and I couldn't see any documentation for this

**Comment by dzg** [comment]
I've tried 5 different examples, e.g., `showhide-files.1d.py` – which does not work.
Thoroughly confused.
