### ISSUE TITLE
Official forks?

### ISSUE THREAD

**Issue by dimitrieh** [matryer/xbar#530]
Dear community and maintainers of this project,

Similar to any other user of BitBar I really like this application and use it daily for many things. What I am wondering about though is its continued development and if it's still actively maintained.

There is a lot of open PR's and there seem to be some forks floating around which have advanced further than the current repository. 

Does anyone have a good overview of or knowledge about which forks to use when, which are active in their development, or perhaps even are official successors to the current project?

kind regards,

**Comment by xilopaint** [comment]
Look into #495.
