### ISSUE TITLE
Get a higher-contrast color for dropdown content, but that is dark mode friendly?

### ISSUE THREAD

**Issue by henrik** [matryer/xbar#532]
Say my plugin gives the output

```
Foo
---
Bar
```

The default seems to be for "Bar" to have grey text. I think that's a bit hard to read for my purposes, so I want to do "Bar|color=black". But then if I switch to dark mode, it's unreadable.

Here are some mutually exclusive ideas for how to improve the situation:
* Change the default to be black in light mode, and white in dark mode, instead of this light grey.
* Allow plugins to specify you want high contrast, e.g. "Bar|color=high_contrast", which would make the text black or white depending on the mode.
* Allow plugins to specify different values for light and dark mode, e.g. "Bar|light_mode_color=black dark_mode_color=white".

**Comment by henrik** [comment]
Hi @matryer! Just out of curiosity, is this a won't-fix close or a did-fix close or something else? :)

**Comment by matryer** [comment]
@henrik This issue was closed automatically when BitBar became xbar. Lots has changed, so we're going to wait and see if these are still issues or not once beta testing gets underway. This may already be solved.
