### ISSUE TITLE
Plugins written in JXA (JavaScript for Automation) are preceded by a warning icon

### ISSUE THREAD

**Issue by davidsharp** [matryer/xbar#535]
I thought I'd try writing a plugin in JXA rather than Node.js, since it's built for dealing more closely with the OS and saves me writing a bash plugin that also contains JXA.

It seems to work (although it's a little funky in the way it outputs), my main problem with it however is that it displays this little ⚠️ icon ahead of the item, and I'm not sure if I can do anything to remove this.

Presumably it's down to the way the output works, all the plugin logs display in the dropdown and the overall return value is what appears in the menu bar (worth also noting, this is the opposite to how it displays when run in terminal).

I'm not sure how to remedy this (and whether it's possible to easily remedy), but I'd be interested to hear what you all think.

Here's the example plugin code:
```
#!/usr/bin/env osascript -l JavaScript

function run(argv) {
  console.log('hello from jxa')
  return 'jxa test'
}
```

And the plugin in action:
![Screenshot 2020-01-08 at 10 36 48 am](https://user-images.githubusercontent.com/5731838/71971602-d4d0d280-3202-11ea-9a23-62c1edcdc439.png)

**Comment by matryer** [comment]
Your program needs to exit with code `0`? Do you know what that exits with?

**Comment by davidsharp** [comment]
Running the script in my terminal, `echo $?` gives me exit code 0
