### ISSUE TITLE
Bitbar crashes due to port leaks

### ISSUE THREAD

**Issue by seaweedsoup** [matryer/xbar#536]
I have a script running every second by the bitbar app and the Bitbar is leaking a port per execution. 
Then bitbar crashes once it cannot get a port any more. 

Following lines are crash log from console app:

Process:               BitBar [1149]
Path:                  /Applications/BitBar.app/Contents/MacOS/BitBar
Identifier:            com.matryer.BitBar
Version:               1.9.2 (1.9.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BitBar [1149]
User ID:               501

Date/Time:             2020-01-10 13:03:31.874 -0800
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Anonymous UUID:        C6EA9A39-F85A-48C6-4820-6E0ABF22203C

Time Awake Since Boot: 320000 seconds

System Integrity Protection: enabled

Crashed Thread:        6  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRunLoop addPort:forMode:]: port argument cannot be nil'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff309648ab __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff66bd5805 objc_exception_throw + 48
2   Foundation                          0x00007fff32f79fce -[NSRunLoop(NSRunLoop) _addPort:forMode:] + 0
3   Foundation                          0x00007fff3303f7ed -[NSConcreteTask waitUntilExit] + 162
4   BitBar                              0x00000001065ec875 -[ExecutablePlugin refreshContentByExecutingCommand] + 546
5   BitBar                              0x00000001065ecca1 __27-[ExecutablePlugin refresh]_block_invoke + 45
6   libdispatch.dylib                   0x00007fff67ee9583 _dispatch_call_block_and_release + 12
7   libdispatch.dylib                   0x00007fff67eea50e _dispatch_client_callout + 8
8   libdispatch.dylib                   0x00007fff67eec358 _dispatch_queue_override_invoke + 763
9   libdispatch.dylib                   0x00007fff67ef87e2 _dispatch_root_queue_drain + 326
10  libdispatch.dylib                   0x00007fff67ef8f22 _dispatch_worker_thread2 + 92
11  libsystem_pthread.dylib             0x00007fff681446b6 _pthread_wqthread + 220
12  libsystem_pthread.dylib             0x00007fff68143827 start_wqthread + 15

**Comment by Joshfindit** [comment]
Can you post your config?

**Comment by seaweedsoup** [comment]
Thank you for a quick reply. 
However, I don't quite get how to obtain the config from bitbar. Could you please provide any instruction to obtain the config? In case, if you are talking about my script, I built a swift code to detect who prevents display sleep then rename it to <script>.1s.sh. This binary will display a green clover or "❗️ 1 | color=red
---
firefox (1880) | color=red".
