### ISSUE TITLE
Ability to skip Updating ... output when refreshing plugins through URL Scheme

### ISSUE THREAD

**Issue by ptomasroos** [matryer/xbar#542]
It would be nice to be able to skip the 
```Updating ... ```
output when refreshing the plugins through the URL Scheme.

In my case it creates a lot more noise than what the output would be when the update would be finished.

https://github.com/matryer/bitbar/blob/e140612a1c93dc9cc9611875178451d7ec6e8b44/App/BitBar/ExecutablePlugin.m#L63

**Comment by denisidoro** [comment]
In my case I'd like to use BitBar to show the current mission control desktop number.

But having an "Updating..." before having "2" makes the tray area "flicker" (because of the expansion/contraction of the widget width.
