### ISSUE TITLE
macOS, space in path to iCloud drive

### ISSUE THREAD

**Issue by HPM41** [matryer/xbar#550]
hi

from one of my plugins: i cannot call a shell script, lying on the iCloud drive. tried all sorts of quotes and the backslash. 

can you help?

thanks and regards
HP

**Comment by JayBrown** [comment]
I just tested two options, and both work.

Create a directory in your iCloud Drive, e.g. `~/Library/Mobile\ Documents/com~apple~CloudDocs/BitBar`, then open the BitBar preferences at `~/Library/Preferences/com.matryer.BitBar.plist` e.g. in **[PrefEdit](https://www.bresink.com/osx/PrefEdit.html)**, and then set the value for the property "pluginsDirectory" to `/Users/yourUser/Library/Mobile\ Documents/com~apple~CloudDocs/BitBar` without any quotes or backslashes. Please note, that apparently it needs to be the full path, i.e. the "yourUser" after "/Users/" needs to be replaced with your actual user name, i.e. `id -un`.

You can also create a symbolic link to your iCloud Drive anywhere in your home folder—I have mine in `~/Documents/CloudStorage/iCloudDrive`, and if you've done that, you can actually navigate into and select your BitBar plugins folder residing in your iCloudDrive from BitBar's select-plugin-folder dialog.
