### ISSUE TITLE
Seeking Swift developer

### ISSUE THREAD

**Issue by matryer** [matryer/xbar#555]
I am looking for a Swift developer who lost their job because of the pandemic. BitBar is too good to go stale, and I don't have the time to learn Swift and rebuild the project.

If you can recommend somebody, please tweet me [@matryer](https://twitter.com/matryer).

Let's see if we can breathe some life into this project.

**Comment by martinbeentjes** [comment]
I am curious how difficult such a project is to pick up to get my hands on Swift actually, maybe too optimistic tho..

**Comment by indeyets** [comment]
@matryer would you be interested in help with maintaining current code base? I don't have much time for rewriting from scratch, but I could definitely help with going thru PRs and maybe shaping something better suitable for further work.

BitBar deserves several bugfix-releases before reimplementation happens

**Comment by AlekSi** [comment]
There is https://github.com/swiftbar/SwiftBar now

**Comment by AlekSi** [comment]
I guess it is fixed by https://github.com/matryer/bitbar/issues/607 now 😆
