### ISSUE TITLE
2 lines of text in menubar

### ISSUE THREAD

**Issue by jvdmeij** [matryer/xbar#556]
If you echo text with a small font size, there is space to fill two lines with text. Is there a standard option for this, or could this be a possible feature on the roadmap?

<img width="93" alt="Screenshot 2020-05-06 at 20 26 26" src="https://user-images.githubusercontent.com/7727264/81214325-fc308400-8fd7-11ea-97ad-0528e7433a8b.png">

**Comment by seanf** [comment]
Related: https://github.com/matryer/xbar/issues/617
