### ISSUE TITLE
Option to disable auto-refresh ?

### ISSUE THREAD

**Issue by AndreaCallia** [matryer/xbar#559]
Hi all and thanks for this great tool...

The tool would be almost perfect, but it has an important flaw: when is refreshed (either automatically or by clicking on "Refresh all"), then all the Bitbar items quickly disappear and immediately reappear. 

It may seem that this has no consequences, but when icons reappear, they are placet in the leftmost positions. This causes the following issues:

1. The icons are not kept in a fixed position (not important for me);
2. If there is little space to fit all the menubar icons (it happens with many app with a "crowded" menu), the Bitbar items will be hidden (this is an importante issue for me);
3. If you use any app which hides unused menubar items (there are many of them, for example ["Hidden Bar"](https://github.com/dwarvesf/hidden)), then since usually such an app is based on hiding the leftmost icons, it will hide the Bitbar icons every time they are refreshed.

In order to prevent this, some people who do not need auto-refreshing (like me) may find very useful to just disable it, thus avoiding the issues above. 

Would it be possible to add a setting for this?

I would be available to do this, if you tell me which file and which code I should change.

Many thanks again for your work...

**Comment by frakman1** [comment]
1- You can make it only refresh once a year by renaming the script like this `script.365d.sh`
2- You can also drag them around if you prefer (until the next refresh when they get reordered again)
![drag](https://user-images.githubusercontent.com/5826484/89718414-41c06c80-d98c-11ea-9d07-64bc1eafaf50.gif)
3- You can rename the script to order their position relative to one-another by prepending numbers or letters to the script name.`1-script.sh`,`2-script.sh`
