### ISSUE TITLE
Is there a way to Empty the trash or move a file to trash with bitbar?

### ISSUE THREAD

**Issue by FusionX13** [matryer/xbar#564]
So I have some experience with bash but don't know how to move files to the trash. I know where the trash file is located but it says, "Permission denied." Also, is there a way to move all files to the trash that are in a current folder?

**Comment by frakman1** [comment]
What are you calling the "current folder" ? Your script can navigate to whatever folder you want.
You can run something like this to make apple script trash the files for you:

```
osascript -e "tell application \"Finder\" to delete POSIX file \"${PWD}/${InputFile}\""
```
