### ISSUE TITLE
Auto-refresh isn't working with macOS Big Sur

### ISSUE THREAD

**Issue by macguitar** [matryer/xbar#566]
Installed BitBar v1.9.2 with Big Sur 11.0 Beta (20A4300b). Everything seems to work fine except that it's not automatically refreshing. I have the "1m" in my plugin filename and it refreshed fine on prior macOS versions. So, it seems something broke with Big Sur.

**Comment by JayBrown** [comment]
Note: there's also BitBar 2.0 beta 10.

Two questions:
(1) Does the internal refresh with `refresh=true` work?
(2) Does refreshing with an external command work? If external refresh works, then a workaround (for the time being) might be to create a LaunchAgent (or several) to refresh the user's BitBar instances

**Comment by JayBrown** [comment]
The external refresh would be `open "bitbar://refreshPlugin?name=foo"`

**Comment by macguitar** [comment]
Since 1.9.2 has a newer date, I figured that was actually newer/better, but I'll try 2.0b10 and also the external command and let you know. Thanks!

**Comment by macguitar** [comment]
Question for #1) do I just add refresh=true at the end of my .php file? or at the beginning? or where? Thanks!

**Comment by JayBrown** [comment]
The `refresh=true` is part of the actual script. I only use UNIX shell scripts with BitBar, so it would be something like…

`echo "--Restore From Backup | refresh=true terminal=false bash=$0 param1=restore-replace param2=favs"`

…meaning that if the user clicks on "Restore From Backup", it will re-run the script with `$1` as "restore-replace` and `$2` as `favs`, and then refresh it afterwards (`refresh=true`).

Don't know how it would work with php.

**Comment by macguitar** [comment]
So, 2.0b10 didn't work. But refreshing with an external command work did work! I am still trying to figure out how to get the internal refresh to work. I'll test that when I figure it out.

**Comment by JayBrown** [comment]
You can also run the external command `open "bitbar://refreshPlugin?name=foo"` from within the script, so if `refresh=true` (or its php equivalent) doesn't work, then you can put the external command in the necessary places within the script.

But this won't give you the regular auto-update… for that you would need a LaunchAgent until there's a bug fix.

**Comment by macguitar** [comment]
Also, just to be clear, if I click the menu bar and press Command-r on the keyboard, then it also refreshes. It just won't refresh automatically based on the filename interval.

**Comment by JayBrown** [comment]
Something very similar seems to be happening on my system with BitBarDistro: https://github.com/matryer/bitbar/issues/567

**Comment by Al-Ferguson** [comment]
Under the current version of MacOS 11 - Big Sur

Interestingly, BitBar has issues when launched at Login or when I start it from the Applications folder via click. But, it seems to work fine if I use "open -c BitBar" from my zsh shell. I thought these all should be the same?!?!?!?!
