### ISSUE TITLE
Can't refresh BitBarDistro

### ISSUE THREAD

**Issue by JayBrown** [matryer/xbar#567]
I'm trying to refresh a BitBarDistro-bundled script with `open "bitbar://refreshPlugin?name=cckm.12h.sh"`, but instead it opens the regular BitBar app.

When BitBar is already running, nothing happens, i.e. nothing gets refreshed.

I tried using a different URI scheme in the BitBarDistro Info.plist and run `open "cckm://refreshPlugin?name=cckm.12h.sh"`, but that didn't work either.

Is there any way to refresh scripts nested in a BitBarDistro bundle without affecting the regular BitBar scripts? ty

**Comment by JayBrown** [comment]
Also realized now that refresh doesn't work either when setting `refresh=true`, e.g. with a simple

`echo "Refresh… | terminal=false refresh=true bash=$0"`

It works fine in the regular BitBar app.

Using v2.0.0 beta10 in both cases
On macOS 10.15.5

**Comment by JayBrown** [comment]
Using [CMD]-R to refresh works on the other hand.

**Comment by frakman1** [comment]
I have a similar issue whereby the `bitbar://` handler is remapped to a different BitBar app that I build with Xcode.
Do you know how to pick an app to go with that handler? The usual Mac OS methods don't list `bitbar://` anywhere.

**Comment by JayBrown** [comment]
I use the successor to the RCDefaultApps preference pane, called **[SwifDefaultApps](https://github.com/Lord-Kamina/SwiftDefaultApps)**

![snap](https://i.imgur.com/IH5K5fG.jpg)

Imho—and if there ever are updates to or Swift rewrites of BitBar & BitBarDistro—the user should be able to freely choose URI schemes to go with each an every **BitBarDistro** bundle, simply by modifying the Info.plist, and BitBarDistro should support them without the need to recompile in Xcode. (This is easily possible; cf. e.g. **Platypus**.) The main **BitBar** app should be restricted to the `bitbar://` URI scheme, however.

**Comment by frakman1** [comment]
Although I don't have that (I am on High Sierra) I did manage to find the Default Apps settings page and got it to work now. Thank you so much!
![image](https://user-images.githubusercontent.com/5826484/89714876-af11d480-d96f-11ea-968b-59e6769fa28d.png)

**Comment by frakman1** [comment]
@JayBrown I think I found where the URL scheme is set in the Bitbar Xcode projects that I built manually.
It's under the target's `Info` tab
![image](https://user-images.githubusercontent.com/5826484/91738052-ef82fd80-eb7d-11ea-863a-48d42686cff8.png)

**Comment by frakman1** [comment]
Unfortunately, that didn't work. I even changed the Identified to be my app's Bundle Identifier. Compiling with this doesn't even show the new URL scheme under the MacOS Setting's Apps/URL. It still defaults to `bitbar` (I'm trying to add a new one for my app)
