### ISSUE TITLE
xterm-256color Support?

### ISSUE THREAD

**Issue by dsemaya** [matryer/xbar#568]
Following along with [issue 467](https://github.com/matryer/bitbar/issues/467), I am trying to include many more than the standard ANSI colors.  Apparently the macOS terminal supports 256 colors.  I can successfully output those colors in bash on my Catalina Mac but most of those colors will not appear in BitBar.  Those that do appear are incorrect.  

Below is a sample bash script based on [this script](https://misc.flogisoft.com/_export/code/bash/tip_colors_and_formatting?codeblock=56) on the site above.  In Terminal it shows all the colors but in Bitbar is shows few.

Is there a way to get more colors than the 16 ANSI colors?  I need more colors than that for my script. 

Thanks!

<img width="696" alt="Screen Shot 2020-07-23 at 1 13 56 PM" src="https://user-images.githubusercontent.com/8286222/88316866-6fe45200-cce6-11ea-8a9c-6c416a38a828.png">
<img width="465" alt="Screen Shot 2020-07-23 at 1 14 07 PM" src="https://user-images.githubusercontent.com/8286222/88316875-7377d900-cce6-11ea-8faa-64cd89e0d62f.png">

```
#!/bin/bash
echo "256 | "
echo "---"

for fgbg in 38 48 ; do # Foreground / Background
    for color in {0..255} ; do # Colors
        # Display the color
        printf "\e[${fgbg};5;%sm  %3s  \e[0m" $color $color 
        # Display 6 colors per lines
        if [ $((($color + 1) % 6)) == 4 ] ; then
  echo " | ansi=true font=courier trim=false";
            echo # New line
        fi
    done
    echo # New line
done

exit 0
```

**Comment by frakman1** [comment]
Have you tried the `ansi-256-colors` [branch](https://github.com/matryer/bitbar/tree/ansi-256-colors)?
From the [diff](https://github.com/matryer/bitbar/compare/ansi-256-colors), it looks like it supports it.

**Comment by dsemaya** [comment]
Thanks, I didn't know that existed.  Although it appears to be 4 years out of date and I can't get it to build.  Any chance this could be merged back into the main release?

**Comment by frakman1** [comment]
You'll have to do that yourself since it doesn't look like this project is supported much anymore.
I'll try it in my build and see if it works for me. Can you post the error you ran into?

**Comment by frakman1** [comment]
It works for me.

![image](https://user-images.githubusercontent.com/5826484/92003108-9f877080-ed0e-11ea-8308-7834f2595144.png)

![image](https://user-images.githubusercontent.com/5826484/92003093-9b5b5300-ed0e-11ea-83f2-348ef14c149a.png)

**Comment by dsemaya** [comment]
Thanks, @frakman1.

Where are the build instructions? 

I downloaded the branch and ran `make` in terminal and got a Sparkle error:

```
$ make
xcodebuild -project ./App/BitBar.xcodeproj
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project ./App/BitBar.xcodeproj

note: Using new build system
note: Planning build
note: Constructing build description
error: This Copy Files build phase contains a reference to a missing file 'Sparkle.framework'. (in target 'BitBar' from project 'BitBar')

** BUILD FAILED **

make: *** [build] Error 65

```
I tried building in Xcode, and removed the Sparkle.framework library to avoid the errors.  Then I got an error:

```
error: Build input file cannot be found: '/Users/myusername/Documents/bitbar ansi-256-colors/App/Vendor/STPrivilegedTask/STPrivilegedTask.m' (in target 'BitBar' from project 'BitBar')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'BitBar' from project 'BitBar')

```

**Comment by frakman1** [comment]
> ... removed the Sparkle.framework library to avoid the errors. 

Don't do that. You'll just run into further errors where the code references the Sparkle files. There are commits other forks that remove Sparkle thoroughly. If you want, you can do that later after you get it to work.

This project makes use of git submodules. See [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for details on how they work. Basically, cloning the BitBar repo will have empty folders for the 3rd party submodules that it uses and the `git modules` commands will fill them out. Do this:

```bash
git clone https://github.com/matryer/bitbar   
cd bitbar
git submodule init
git submodule update
```

Then open the `BitBar.xcodeproj` file and (optionally run clean) hit the play/run button. It should compile successfully.

You may want to use the `beta` branch since it has more features than the `master` branch.

Hope that helps and Good Luck!

**Comment by yanzhang0219** [comment]
Take a look at [SwiftBar](https://github.com/swiftbar/SwiftBar). It is a promising successor fully written by swift and maintained actively. 256 colors ANSI will be supported soon when 1.1.0 is released.
