### ISSUE TITLE
Several plugins with warning signs

### ISSUE THREAD

**Issue by joaofrgomes** [matryer/xbar#576]
Hi guys. I don't know what am I doing wrong here, and why two of my plugins are displaying warnings while two others aren't.

<img width="389" alt="Captura de ecrã 2020-09-19, às 17 46 25" src="https://user-images.githubusercontent.com/29361091/93672180-c7156180-faa0-11ea-9af7-fc0a361b491f.png">

I'm new to the app and I think I followed the setup instructions correctly. However, the warnings it gives me, even for basic stuff such as while trying to do updates, are nonsensical and incoherent with my setup; it complains that it's in a read-only volume, and that I should move it to the Applications folder, which I already did… what gives? And then, at best, I get this one: 
<img width="532" alt="Captura de ecrã 2020-09-19, às 17 52 26" src="https://user-images.githubusercontent.com/29361091/93672206-f3c97900-faa0-11ea-8394-47225691a2e2.png">

All of this looks very broken and too much of a hassle, and didn't cause a great first impression; even though the custom skins I created for ByteController, the app I've been using for controlling iTunes for years now, don't look perfect in dark mode and I had to gimp the Play/Pause button and make it static for Catalina as the app can no longer retrieve the current status of Music.app, I'll likely keep using it while on an Intel Mac or an Apple Silicon Mac with Rosetta 2 support… But eventually it will cease working for good and I'll have to switch to an alternative. If I get BitBar to work, I'd much rather stick with it for future proofing and additional functionality.

**Comment by don1138** [comment]
I had the same problem, and solved it by setting setting permissions on all items in the scripts folder:

`chmod +x ./*`

I'm still getting the **Update Error!** dialog on **Check For Updates…**, though.
Might also be a permissions issue. If I figure it out I'll post here.
