### ISSUE TITLE
bash command won't run unless terminal=true

### ISSUE THREAD

**Issue by don1138** [matryer/xbar#578]
I'm using BitBar to run **defaultbrowser** (https://github.com/kerma/defaultbrowser).

```
#!/bin/bash

echo "💊"
echo "---"
echo "Safari | terminal=true bash='defaultbrowser safari'"
echo "Firefox | terminal=true bash='defaultbrowser firefox'"
echo "Chrome | terminal=true bash='defaultbrowser chrome'"
```

If I set `terminal=false`, nothing happens. Set it back to `terminal=true`, Terminal opens, script runs.

Bug or feature – Any thoughts?

**Comment by einstweilen** [comment]
Have you tried to give the full path to 'defaultbrowser'? e.g. bash='/usr/local/bin/defaultbrowser safari'

**Comment by don1138** [comment]
Thanks for the tip, but yes, I gave that a try as well – no luck.

**Comment by jtorvald** [comment]
@don1138 I had the same issue, solved it with:
echo "Boop | bash=/bin/zsh param1=-c param2='open /Applications/Boop.app' terminal=false"
