### ISSUE TITLE
musicRating.10s.sh doesn't work if the script path contains a space?

### ISSUE THREAD

**Issue by edjusted** [matryer/xbar#587]
Here's the error I get when I click on the musicRating bitbat:

Your script path /Users/***/Library/Application Support/BitBar plugins/musicRating.10s.sh has a space in it, which BitBar does not support Play/Pause/Next/Previous buttons will not work.

It *does* work when I move it to something like /Users/***/Desktop/BitBarPlugins

But this seems like it should be an easy fix to allow us to keep it in a folder with a space?

**Comment by matryer** [comment]
This will be fixed as part of the rewrite - see #607
