### ISSUE TITLE
"Updating..." message is really annoying. How to refresh the plugin seamlessly?

### ISSUE THREAD

**Issue by yanzhang0219** [matryer/xbar#589]
Hello,
I am using URL Scheme to refresh the plugin. On the menu bar, it becomes "Updating..." and then the updated output appears. This process is really distractive. Especially if the item output is very long, when it is refreshed, it shrinks to show "Updating..." and then expands to show the updated output, as if the item is **flashing** on the menu bar out of the corner of my eye. 

I tried to search for the solution from the existing issues. I tried to change `self.content = @"Updating ...";` to `self.content=@" ";` in `bitbar/App/BitBar/ExecutablePlugin.m` file. However, it doesn't solve the problem. It just changes the updating message from "Updating..." to an empty string, but the updating process is still obvious, making the item shrink and expand, like flashing. 

**How to make the plugin being refreshed seamlessly?** That means the previous output will stay there until showing the updated output, i.e., completely hide the updating message. [**SwiftBar**](https://github.com/swiftbar/SwiftBar/issues?q=color) does a really good job for this feature. 

I attached two GIFs below. The first one is for BitBar, and the second for SwiftBar. We can see SwiftBar refreshes its plugins (by URL Scheme) seamlessly.

1. BitBar
![bitbar](https://user-images.githubusercontent.com/11582667/101710291-058a3f00-3a46-11eb-95a6-f9b5b72109c1.gif)

2. SwiftBar
![swiftbar](https://user-images.githubusercontent.com/11582667/101710306-0b802000-3a46-11eb-888b-3b0254e79a6b.gif)

Thank you very much.

**Comment by matryer** [comment]
Agree.
