### ISSUE TITLE
latest release not working on catalina

### ISSUE THREAD

**Issue by Scartiloffista** [matryer/xbar#590]
![image](https://user-images.githubusercontent.com/36407154/101834888-38622f00-3b3b-11eb-9faf-a8455bd73483.png)

**Comment by ashaikh** [comment]
FYI - This also happens in Mojave and I tried both Homebrew and the app download on Github.

**Comment by ashaikh** [comment]
I tested this more for you and the version that works with Mojave and probably Catalina is version 1.9.2

**Comment by pdelre** [comment]
Related recent brew changes:

https://github.com/Homebrew/homebrew-cask/pull/95155 (Updates to 1.10.0)
https://github.com/Homebrew/homebrew-cask/pull/95232 (Prevents installation on macOS < BigSur)

**Comment by ashaikh** [comment]
Awesome thanks for the speedy response.

**Comment by core-code** [comment]
also, previous releases were properly signed by 'Developer ID Application: Code and That Ltd (B3T8QSC4HG)' while the newest release only has an adhoc signature. what is going on here?

**Comment by ctsrc** [comment]
Can the old version be installed on Catalina still? My install of bitbar was updated to 1.10.0 which gives me the same error message as OP got when they tried to run it.

I uninstalled the new version:

```
brew uninstall bitbar
```

But trying to install the old version through homebrew is not readily possible as far as I can tell.

There are a bunch of idea on how to install older versions of stuff through homebrew at https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula but those methods are both convoluted and many of those ways don't seem to work any longer anyways.

Is support for older versions of macOS coming back in a future version of bitbar?

**Comment by yanzhang0219** [comment]
I believe it is a good time to take a look at the promising successor [SwifBar](https://github.com/swiftbar/SwiftBar)

**Comment by solarizedalias** [comment]
I somehow rolledback to `v1.9.2` patching the formula. 
I'm not sure but I'll share it if that's hopefully useful for anyone else here for the time being.
You can find the path to the formula by `brew formula bitbar` and apply this patch.
Alternatively, you can directly edit the formula by `brew edit bitbar`.

```patch
diff --git a/Casks/bitbar.rb b/Casks/bitbar.rb
index e47cf6b776..31feca5a65 100644
--- a/Casks/bitbar.rb
+++ b/Casks/bitbar.rb
@@ -1,14 +1,14 @@
 cask "bitbar" do
-  version "1.10.0"
-  sha256 "d0e023583d443f98f2adb3c307da01de608abc98d03887e5fd85d3004716d0fb"
+  version "1.9.2"
+  sha256 "9e317d58143f544ab3b2b35e4d0ef2f11b9578fe6872cec1415da961acb1aee4"
 
-  url "https://github.com/matryer/bitbar/releases/download/v#{version}/BitBar.app.zip"
+  url "https://github.com/matryer/bitbar/releases/download/v#{version}/BitBar-v#{version}.zip"
   appcast "https://github.com/matryer/bitbar/releases.atom"
   name "BitBar"
   desc "Utility to display the output from any script or program in the menu bar"
   homepage "https://github.com/matryer/bitbar/"
 
-  depends_on macos: ">= :big_sur"
+  depends_on macos: ">= :mojave"
 
   app "BitBar.app"
 
```

**Comment by piotrd** [comment]
@matryer was the breaking change intentional?

**Comment by matryer** [comment]
@piotrd No I think this is a build target error... let me build with a lower build target and see if that works.

**Comment by matryer** [comment]
Try v1.10.1 - although it seems like the vertical alignment issue persists :(

**Comment by hagemt** [comment]
@matryer: Just want to say thanks for the fix and this awesome project. <3 bitbar

**Comment by AddictArts** [comment]
On Catalina 1.10.1 runs now, but nothing in the menu is clickable, for example the howbrew script plugin "Upgrade All" does nothing. In 1.9.2 it would launch a terminal and run $ brew upgrade

**Comment by matryer** [comment]
Hmm, weird. I will have a look at this tomorrow @AddictArts and see if I can figure out what's going on.

**Comment by wmuizelaar** [comment]
For the record: v1.10.1 also complains that it cannot be opened because Apple cannot check it for malicious software.

**Comment by core-code** [comment]
> For the record: v1.10.1 also complains that it cannot be opened because Apple cannot check it for malicious software.

thats what i mentioned above:

> > also, previous releases were properly signed by 'Developer ID Application: Code and That Ltd (B3T8QSC4HG)' while the newest release only has an adhoc signature.

**Comment by matryer** [comment]
This one was built with the correct code signing.  But I think there are still issues on some operating systems. 

[BitBar.app.zip](https://github.com/matryer/bitbar/files/5729547/BitBar.app.zip)

**Comment by jamesholcomb** [comment]
MacOS Big Sur 11.1 using the 👆 .zip 

![image](https://user-images.githubusercontent.com/362729/104107933-fd603200-5285-11eb-8957-503f87fe0005.png)

**Comment by matryer** [comment]
Thanks for trying it—will investigate.

**Comment by randallzug** [comment]
After right-click opening once, xBar v2.0.26 works with Mojave 10.14.6 without issue. This is a pleasant surprise, since the readme.md says at least Catalina is required.
