### ISSUE TITLE
Vertical alignment is still wrong

### ISSUE THREAD

**Issue by fenhl** [matryer/xbar#593]
Since #584 was merged and released, the text is now 3 physical pixels too low. (macOS 11.0.1, BitBar 1.10.0, logical pixel size: 2.0 physical pixels)

![offset](https://user-images.githubusercontent.com/641386/101989516-c0118000-3c98-11eb-93bc-82c976266141.png)

**Comment by matryer** [comment]
Do we need some more cases in here? https://github.com/matryer/bitbar/pull/584/files

**Comment by matryer** [comment]
This will be fixed as part of the rewrite - see #607
