### ISSUE TITLE
Bash-Problems with 1.10.1

### ISSUE THREAD

**Issue by warmup72** [matryer/xbar#596]
I´m Using macOS 10.15.7 and have updated to Bitbar 1.10.1.
After this Update:
1. Linefeed in the menubar (\n) doesn't work anymore
2.  Buttons like "echo "View Realtime Log | color=back bash='$0' param1=show_tm terminal=true refresh=false" doesn't work anymore.

=> after 1h of trying I´m now back on 2-beta10 without this problems :-(

**Comment by warmup72** [comment]
Okay -it´s reproducebal, the option 
terminal=true doesn't work anymore.
The Terminal opens, but the script doesn't start

**Comment by matryer** [comment]
Sorry @warmup72, this is annoying. There's some work to do to figure out what's changed here.
