### ISSUE TITLE
Drag to Bitbar

### ISSUE THREAD

**Issue by jessefrye** [matryer/xbar#6]
I would love to drag a folder into bitbar and have it open in a text editor.

I would also love to drag a link into bitbar to save or post it to a social/cloud service.

**Comment by iosdeveloper** [comment]
How do we pass the dropped item to plugins (as argument) without breaking existing plugins i.e. how do plugins indicate the types they accept (metadata)?

**Comment by ermsdev** [comment]
Interested in using this for my time logger, I use xbar to start intervals in timewarrior, most of my intervals are options in the dropdown based on a config file, but I want to make my plugin let me drag and drop ticket/issue links onto xbar to start an interval that references that link.

It looks like this issue had work but might not have made it in, not sure if there's still development on xbar but wanted to add my interest. Not familiar with the tools to be able to do it myself for now.
