### ISSUE TITLE
Feature request: Right justify value of a key/value pair

### ISSUE THREAD

**Issue by shepazon** [matryer/xbar#605]
Couldn't think of the best way to phrase this request. It would be useful for tools that are showing various values of flags, variables, or other fields, to be able to right-justify the values, so they could get an output like this:

```
+-------------------------------------+
|IP Address             192.145.55.76 |
|Connection Time           4:32:42 AM |
|Time Remaining    1 hour, 45 minutes |
+-------------------------------------+
|Disconnect Now                   ⌥⌘D |
+-------------------------------------+
```

This would really help to improve readability, I think, for tools showing output along these lines. Another possibility would instead be to allow showing the values all left justified, but all vertically aligned with one another, like this:

```
+----------------------------------------+
|IP Address       192.145.55.76          |
|Connection Time  4:32:42 AM             |
|Time Remaining   1 hour, 45 minutes     |
+----------------------------------------+
|Disconnect Now                       ⌥⌘D|
+----------------------------------------+
```

**Comment by matryer** [comment]
hey @shepazon, if you used a fixed width font, could you achieve this by padding with spaces?

**Comment by shepazon** [comment]
@matryer The problem with that idea is that I don't necessarily know the width of the menu, so I can't necessarily get the spacing right just using spaces and a fixed-width font. If the menu were a fixed width all the time, then yes, it could be done. :)

**Comment by shepazon** [comment]
Thinking it would be interesting to come up with a way to let item titles be attributed strings... not sure how that would work other than possibly by letting you specify them using HTML or RTF and converting, and even that probably wouldn't solve this particular issue.
