### ISSUE TITLE
Any chance for 10.13 support? (last version to use Nvidia GPUs)

### ISSUE THREAD

**Issue by Joshfindit** [matryer/xbar#611]
xbar looks awesome, but I just went to run it and it's only macOS 11+ 😥

![image](https://user-images.githubusercontent.com/1937155/110356964-28aa9780-8011-11eb-944b-4355b399b152.png)

**Comment by matryer** [comment]
@Joshfindit I'll see what the minimum os we can get away with it, and let you know.

**Comment by ianfoo** [comment]
This is an interesting dialog, because it tells a falsehood about requiring macOS 11, as someone who is running xbar on Catalina (macOS 10.15.7).

**Comment by matryer** [comment]
@Joshfindit Does this do the same?
[xbar.v2.0.19-beta-5-g9a866463.tar.gz](https://github.com/matryer/xbar/files/6117744/xbar.v2.0.19-beta-5-g9a866463.tar.gz)

**Comment by beaudett** [comment]
Hi. My mac is running 10.14.6 and I can start the above version of xbar from command line. From the Finder it doesn't start saying that I have macOS 10.14.16 and the application requires 10.13 or later.

**Comment by matryer** [comment]
@Joshfindit @beaudett Please try the latest, we think we've fixed this: https://github.com/matryer/xbar/releases/latest

**Comment by beaudett** [comment]
I am sorry to say that with v2.0.25-beta it shows:
![Screenshot 2021-03-12 at 13 30 02](https://user-images.githubusercontent.com/4553043/110940390-1ee9a280-8337-11eb-9186-e0e9caff2f29.png)
and it also breaks from the command line:

> xbar v2.0.25-beta
> application requires at least OS X version 10.15.0 (10.15.0), but is being run on 10.14.6 ( 10.14.6/18G8022), and so is exiting.SIGABRT: abort PC=0x7fff58bb72c2 m=0 sigcode=0
> signal arrived during cgo execution

Thank you so much for your efforts !

**Comment by matryer** [comment]
Here's one with 10.13 set as the minimum version: [xbar.v2.0.25-beta-1-g8d8f34f1.tar.gz](https://github.com/matryer/xbar/files/6130082/xbar.v2.0.25-beta-1-g8d8f34f1.tar.gz)

**Comment by beaudett** [comment]
Indeed, it works, both from the Finder and from command line ! Thank you !

**Comment by matryer** [comment]
@leaanthony We'll leave 10.15 on the README for now, but if the app runs fine on older operating systems, I see no reason not to support them.

**Comment by Joshfindit** [comment]
Confirmed it works fine for me too. Installed plugins from the browser, have realtime readout in the menubar.

Thank you!

**Comment by matryer** [comment]
@Joshfindit That's great, thanks for letting me know. You'll two will need to be our testers, we don't have computers that can run that operating system. :)

**Comment by Joshfindit** [comment]
@matryer Ping me any time

**Comment by beaudett** [comment]
Hi @matryer 
I just tried v2.0.31-beta on MacOS 10.14.6 and I get a crash.
The printout can be found [here](https://gist.github.com/beaudett/56137662412402576feecdad74ddd5c7).

**Comment by matryer** [comment]
Is it reproducible? If so, can you describe the steps?

It’s likely we’re using an API that isn’t supported in that version. We’re
targeting 10.15 but would still like to fix this if we can.

**Comment by beaudett** [comment]
Yes, it is 100% reproducible. It is the version from the tarfile from the release page. If I click on the xbar icon in the Finder, nothing happens. From the terminal, I just run ```./xbar.app/Contents/MacOS/xbar``` and I get the crash and the printout mentioned earlier. 
It seems to be a change introduced between   [xbar.v2.0.27-beta-17 ](https://github.com/matryer/xbar/releases/download/v2.0.27-beta/xbar.v2.0.27-beta-17-g014c4684.tar.gz) and [xbar.v2.0.28-beta](https://github.com/matryer/xbar/releases/download/v2.0.28-beta/xbar.v2.0.28-beta.tar.gz) that is causing the problem as the former is running fine and the latter has a sigv that looks similar to the one I shared (at least to me). 
Thanks a lot for your help !

**Comment by Joshfindit** [comment]
I am able to successfully run `v2.0.32-beta` on `10.13.6`

One thing that might be the issue: I've had crashes with certain plugins. Move everything out from `~/Library/Application Support/xbar/plugins/` and try opening xbar again.

Check https://github.com/matryer/xbar-plugins/issues/1567 if that fixes it

**Comment by Joshfindit** [comment]
Just to be thorough, I just ran [xbar.v2.0.32-beta.tar.gz](https://github.com/matryer/xbar/releases/download/v2.0.32-beta/xbar.v2.0.32-beta.tar.gz) and it also works successfully.

**Comment by beaudett** [comment]
Hi @Joshfindit. Thanks for the hint ! If I remove my home-made plugins, xbar starts successfully, including [xbar.v2.0.31-beta](https://github.com/matryer/xbar/releases/download/v2.0.31-beta/xbar.v2.0.31-beta.tar.gz). I'll do my homework and try to fix them.

**Comment by Joshfindit** [comment]
@beaudett We've found that it's the `color=` that's causing it to crash on 10.13. I've personally just removed the color directives from all the scripts I use and no more crashes. There's further discussion on https://github.com/matryer/xbar-plugins/issues/1567 if you want to join in.
