### ISSUE TITLE
panic: NSImage template

### ISSUE THREAD

**Issue by matryer** [matryer/xbar#615]
I installed v2.0.9-beta, and ran it from the terminal as `/Applications/xbar.app/Contents/MacOS/xbar` and got the following crash dump:

<details>
<pre><code>
2021-03-08 23:50:42.875 xbar[2842:34822] -[NSImage template]: unrecognized selector sent to instance 0x41938f80
2021-03-08 23:50:42.877 xbar[2842:34822] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSImage template]: unrecognized selector sent to instance 0x41938f80'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff207636af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff2049b3c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff207e5c85 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff206cb07d ___forwarding___ + 1467
	4   CoreFoundation                      0x00007fff206caa38 _CF_forwarding_prep_0 + 120
	5   xbar                                0x00000000043fc2a8 processTextMenuItem + 1176
	6   xbar                                0x00000000043fd174 processMenuItem + 1476
	7   xbar                                0x00000000043fd37a processMenuData + 106
	8   xbar                                0x00000000043fd633 GetMenu + 147
	9   xbar                                0x00000000043fe57d ShowTrayMenu + 301
	10  xbar                                0x00000000043ffacc UpdateTrayMenuInStore + 460
	11  xbar                                0x00000000043efc36 __SetTrayMenu_block_invoke + 38
	12  libdispatch.dylib                   0x00007fff204455dd _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x00007fff204467c7 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff20452b86 _dispatch_main_queue_callback_4CF + 940
	15  CoreFoundation                      0x00007fff20726970 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00007fff206e8852 __CFRunLoopRun + 2731
	17  CoreFoundation                      0x00007fff206e76ce CFRunLoopRunSpecific + 563
	18  HIToolbox                           0x00007fff2896f630 RunCurrentEventLoopInMode + 292
	19  HIToolbox                           0x00007fff2896f42c ReceiveNextEventCommon + 709
	20  HIToolbox                           0x00007fff2896f14f _BlockUntilNextEventMatchingListInModeWithFilter + 64
	21  AppKit                              0x00007fff22f079b1 _DPSNextEvent + 883
	22  AppKit                              0x00007fff22f06177 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
	23  AppKit                              0x00007fff22ef868a -[NSApplication run] + 586
	24  xbar                                0x00000000043f39ac Run + 4076
	25  xbar                                0x00000000043e70cf _cgo_0185d2c5ec34_Cfunc_Run + 47
	26  xbar                                0x0000000004071390 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff205c3462 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43e70a0, 0xc000159da0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc000159d70 sp=0xc000159d38 pc=0x4008efb
github.com/wailsapp/wails/v2/internal/ffenestri._Cfunc_Run(0x4c04cb0, 0xc000000000, 0x0)
	_cgo_gotypes.go:359 +0x45 fp=0xc000159da0 sp=0xc000159d70 pc=0x43cc9a5
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run.func6(0x4c04cb0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/ffenestri/ffenestri.go:171 +0x65 fp=0xc000159dd0 sp=0xc000159da0 pc=0x43cf745
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run(0xc0000683c0, 0x45696a0, 0xc000110d20, 0xc0001c4a80, 0x95a, 0xc000068a00, 0x0, 0x0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/ffenestri/ffenestri.go:171 +0x2f1 fp=0xc000159e40 sp=0xc000159dd0 pc=0x43cde91
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc00012d290, 0xc00012d290, 0x0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/app/desktop.go:224 +0x659 fp=0xc000159ee8 sp=0xc000159e40 pc=0x43dbc79
github.com/wailsapp/wails/v2.Run(0xc00019c000, 0xc000068240, 0x44c84d3)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/wails.go:24 +0x5f fp=0xc000159f18 sp=0xc000159ee8 pc=0x43dc29f
main.main()
	/Users/matryer/Code/go/src/github.com/matryer/xbar/app/main.go:17 +0x30e fp=0xc000159f88 sp=0xc000159f18 pc=0x43e160e
runtime.main()
	/usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc000159fe0 sp=0xc000159f88 pc=0x403ddb6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000159fe8 sp=0xc000159fe0 pc=0x4071701

goroutine 6 [select]:
github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start.func1(0xc00006a420)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/servicebus/servicebus.go:83 +0x157
created by github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/servicebus/servicebus.go:77 +0xce

goroutine 7 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start.func1(0xc00006afc0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/runtime.go:73 +0x17c
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/runtime.go:70 +0x3f

goroutine 8 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start.func1(0xc000074370)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/log.go:68 +0x157
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/log.go:64 +0x5c

goroutine 9 [select]:
github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start.func1(0xc000110d20)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/messagedispatcher/messagedispatcher.go:118 +0x225
created by github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/messagedispatcher/messagedispatcher.go:115 +0x9e

goroutine 10 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*URL).Start.func1(0xc000074640)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/url.go:66 +0x157
created by github.com/wailsapp/wails/v2/internal/subsystem.(*URL).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/url.go:62 +0x5c

goroutine 11 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start.func1(0xc0000746e0)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/event.go:89 +0x153
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/event.go:86 +0x9b

goroutine 12 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start.func1(0xc000074780)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/menu.go:72 +0x153
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/menu.go:69 +0x9b

goroutine 13 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start.func1(0xc000074820)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/call.go:77 +0x14a
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/subsystem/call.go:74 +0x5a

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 34 [select]:
github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start.func1(0xc000068a40)
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/signal/signal.go:59 +0x9e
created by github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start
	/Users/matryer/Code/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-alpha.47/internal/signal/signal.go:58 +0xc9

goroutine 22 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func1(0xc000096090, 0xc00008e300, 0xc00024a180, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:182 +0x109
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:179 +0x138

goroutine 58 [semacquire]:
sync.runtime_Semacquire(0xc000097548)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000097540)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/matryer/xbar/pkg/plugins.Plugins.Run(0xc000202300, 0x4, 0x4, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:103 +0xc5
main.(*app).RefreshAll.func1(0xc000124090, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/app/app.go:151 +0x55
created by main.(*app).RefreshAll
	/Users/matryer/Code/go/src/github.com/matryer/xbar/app/app.go:148 +0x6d2

goroutine 71 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func2(0xc0003d91a0, 0xc00024a0c0, 0x4570198, 0xc000216540, 0xc000201200)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:201 +0x1af
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:198 +0x19c

goroutine 36 [semacquire]:
sync.runtime_Semacquire(0xc0000975a8)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0000975a0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run(0xc00024a000, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:211 +0x1aa
github.com/matryer/xbar/pkg/plugins.Plugins.Run.func1(0x4570198, 0xc000216540, 0xc000097540, 0xc00024a000)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:99 +0x3f
created by github.com/matryer/xbar/pkg/plugins.Plugins.Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:98 +0x9f

goroutine 37 [semacquire]:
sync.runtime_Semacquire(0xc0003d91a8)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0003d91a0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run(0xc00024a0c0, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:211 +0x1aa
github.com/matryer/xbar/pkg/plugins.Plugins.Run.func1(0x4570198, 0xc000216540, 0xc000097540, 0xc00024a0c0)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:99 +0x3f
created by github.com/matryer/xbar/pkg/plugins.Plugins.Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:98 +0x9f

goroutine 38 [semacquire]:
sync.runtime_Semacquire(0xc000096098)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000096090)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run(0xc00024a180, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:211 +0x1aa
github.com/matryer/xbar/pkg/plugins.Plugins.Run.func1(0x4570198, 0xc000216540, 0xc000097540, 0xc00024a180)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:99 +0x3f
created by github.com/matryer/xbar/pkg/plugins.Plugins.Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:98 +0x9f

goroutine 39 [semacquire]:
sync.runtime_Semacquire(0xc000097584)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000097584)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run(0xc00024a240, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:211 +0x1aa
github.com/matryer/xbar/pkg/plugins.Plugins.Run.func1(0x4570198, 0xc000216540, 0xc000097540, 0xc00024a240)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:99 +0x3f
created by github.com/matryer/xbar/pkg/plugins.Plugins.Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:98 +0x9f

goroutine 43 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func1(0xc000097584, 0xc00008e780, 0xc00024a240, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:182 +0x109
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:179 +0x138

goroutine 44 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func2(0xc000097584, 0xc00024a240, 0x4570198, 0xc000216540, 0xc00008e780)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:201 +0x1af
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:198 +0x19c

goroutine 70 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func1(0xc0003d91a0, 0xc000201200, 0xc00024a0c0, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:182 +0x109
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:179 +0x138

goroutine 68 [IO wait]:
internal/poll.runtime_pollWait(0x6b15490, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00021a198, 0x72, 0x1000, 0x1068, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00021a180, 0xc0004a6000, 0x1068, 0x1068, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00021a180, 0xc0004a6000, 0x1068, 0x1068, 0xc0004a6575, 0xc000398dd8, 0xc000582828)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000094050, 0xc0004a6000, 0x1068, 0x1068, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0003d3188, 0xc0004a6000, 0x1068, 0x1068, 0x0, 0xc000046900, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc00035ecf8, 0x4569000, 0xc0003d3188, 0x4010da5, 0x445c500, 0x44b5720)
	/usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc00035ea80, 0x34701898, 0xc000094050, 0x5, 0xc000094050, 0x44773c0)
	/usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00035ea80, 0x0, 0x0, 0xc000068000)
	/usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc00035ea80, 0xc0003f8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc0002bdd40, 0xc0003a3538, 0x9, 0x9, 0x4263ceb, 0xc000582c78, 0x400c685)
	/usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x4568e60, 0xc0002bdd40, 0xc0003a3538, 0x9, 0x9, 0x9, 0xc0003f6050, 0xacd2e7ebe11300, 0xc0003f6050)
	/usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
net/http.http2readFrameHeader(0xc0003a3538, 0x9, 0x9, 0x4568e60, 0xc0002bdd40, 0x0, 0x0, 0xc0003c5bf0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0003a3500, 0xc0003c5bf0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc000582fa8, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:8322 +0xd8
net/http.(*http2ClientConn).readLoop(0xc000284600)
	/usr/local/go/src/net/http/h2_bundle.go:8244 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7208 +0x6c5

goroutine 98 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func1(0xc0000975a0, 0xc00008e840, 0xc00024a000, 0x4570198, 0xc000216540)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:182 +0x109
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:179 +0x138

goroutine 99 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func2(0xc0000975a0, 0xc00024a000, 0x4570198, 0xc000216540, 0xc00008e840)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:201 +0x1af
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:198 +0x19c

goroutine 23 [select]:
github.com/matryer/xbar/pkg/plugins.(*Plugin).Run.func2(0xc000096090, 0xc00024a180, 0x4570198, 0xc000216540, 0xc00008e300)
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:201 +0x1af
created by github.com/matryer/xbar/pkg/plugins.(*Plugin).Run
	/Users/matryer/Code/go/src/github.com/matryer/xbar/pkg/plugins/plugin.go:198 +0x19c

rax    0x0
rbx    0x7db9e00
rcx    0x7ffeefbfd678
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfd6a0
rsp    0x7ffeefbfd678
r8     0x7ffeefbfd540
r9     0x7ffeefbfd710
r10    0x7db9e00
r11    0x246
r12    0x307
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7fff205c3462
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
</code></pre>
</details>

_Originally posted by @magicus in https://github.com/matryer/xbar/issues/614#issuecomment-793145216_

**Comment by matryer** [comment]
@magicus Thanks for the update. I think the `template=true` feature in xbar is broken. That plugin must've been using it. For now, I have disabled that feature until we can get it working. This issue will track that work.

**Comment by magicus** [comment]
A grep gave me this match:
`return "\(subject.title) | href=\(url) templateImage=\(subject.icon)"`

So it seems it's using `templateImage`. (I don't know the finer details of all these xbar commands though)

**Comment by leaanthony** [comment]
@magicus - do you know if it was generating a valid base64 image?

**Comment by magicus** [comment]
I think it was/is. It always looked good using BitBar. For the moment I reverted back to BitBar since I needed stuff to Just Work<tm>, but I'll be happy to try out further betas in my spare time.

FYI, this was the plugin that was causing the issues: https://github.com/kaishin/github-notifications-bitbar
I have made small changes to it (adding a refresh menu item, iirc), but I'm guessing the crash could be reproduced with the 2.0.7 beta and the original script.

**Comment by leaanthony** [comment]
Thanks for letting us know the plugin!

**Comment by magicus** [comment]
No, actually, thank **you** for reviving xbar! I've always loved BitBar but it has bitrotten and felt abandoned. I hope I can help bring it back to it's former glory, if not by PRs so at least by testing. :)

**Comment by leaanthony** [comment]
One thing, do you know what rights the PAT needs for that plugin? There's no details at all. Running it without a PAT or with a PAT that I thought was right just gives a blank line with no errors. I'm stumped!

**Comment by magicus** [comment]
FWIF (hijacking this bug report...) I also realized the coloring does not work either. The plugin used to generate a blue icon, now it's black.

**Comment by matryer** [comment]
@leaanthony see https://github.com/matryer/xbar/blob/master/app/app.go#L179-L200

I found the problem - cycle items (the ones that appear in the menu bar itself) are different to the menu (extended) items we use in the dropdown. So we don't process it in the same way we process the other menu items, i.e. there are no actions, no fonts, colours, images, etc.

So of course we need to process these items in the same way, and figure out what that means for swapping the items in and out of the tray menu.

One suggestion I made would be to have `TrayMenu` use an `Item` to represent it, even if some features aren't allowed in that context:

```go
type TrayMenu struct {
  Item *menu.Item
  //...
}
```

**Comment by leaanthony** [comment]
@matryer - I think we should move the "image in tray" issue to another ticket. 

Regarding this specific issue of the crash, it's been fixed in alpha.49 and the menu items are looking good (Notice the tag images):

![Screenshot 2021-03-13 at 2 55 18 pm](https://user-images.githubusercontent.com/1943904/111018464-ffbd4480-840c-11eb-8e27-05a79d8fff00.png)

![Screenshot 2021-03-13 at 2 54 57 pm](https://user-images.githubusercontent.com/1943904/111018469-0a77d980-840d-11eb-955f-affc41cf64e2.png)

**Comment by matryer** [comment]
OK, closing as the crash is fixed.

For the other issue, please see https://github.com/matryer/xbar/issues/630
