### ISSUE TITLE
List of plugins not updated in UI when plugin is removed

### ISSUE THREAD

**Issue by magicus** [matryer/xbar#616]
I removed a plugin from my plugin directory. In the "Plugins..." UI I still see it listed in the "Plugins" list. However when I click on it I get:

```
Something went wrong, this: open /Users/me/Library/Application Support/xbar/plugins/bad-plugin.3s.sh: no such file or directory Open issue
×
```

**Comment by matryer** [comment]
@magicus It's because the UI doesn't poll for updates. Technically, we want people to manipulate the plugin directory through the app. But you can try pressing `cmd+r` to refresh the view when things do change.

**Comment by magicus** [comment]
I would not argue for a polling UI. However, the behavior could be more graceful in the face of changes. After all, xbar is appealing to superusers who are more likely to do stuff like editing files directly instead of going through a UI. 

Some ideas:

* Add a "refresh" button to rescan the plugin directory
* If the UI discovers that a plugin is missing, don't treat this as an error, but as a lack of updates and remove it from the list and repaint.
* Or at the very least add a "refresh" action to the missing plugin error text.

Also, the title "Plugins" is a bit too generic. Perhaps "Installed plugins" or just "Installed" would be a better heading?

**Comment by magicus** [comment]
Ok, I think this was an improvement. However:
1) There is no ← navigation button..?
2) I'd still like to see an overall refresh button, perhaps a small ↺ or something like that in the corner. Or some other way to find new plugins. Pressing cmd-R worked, but it is not a very visible action...

**Comment by matryer** [comment]
@magicus I like the idea of a refresh button.

**Comment by matryer** [comment]
@magicus Please check out the latest, including the refresh button. It refreshes the data on the page and refreshes the plugins.

**Comment by matryer** [comment]
Closing this, it's done.
