### ISSUE TITLE
v2.0.12 now starts on 11.2.3

### ISSUE THREAD

**Issue by sydsyd** [matryer/xbar#618]
I've got one plugin
dnscrypt-proxy-switcher.10s.sh
but the menu doesn't display any icon. See screenshot
![Screen Shot 2021-03-09 at 11 45 45 pm](https://user-images.githubusercontent.com/3580983/110472778-e62cac00-8131-11eb-86fb-13a84040dc3d.jpg)

**Comment by matryer** [comment]
@leaanthony Did you see the icon when you ran this plugin?

**Comment by leaanthony** [comment]
No. I believe this is because template images are currently disabled.

**Comment by sydsyd** [comment]
All fixed now

**Comment by leaanthony** [comment]
Just to clarify, the image was emoji and not a template image. Working well 👍

**Comment by sydsyd** [comment]
@leaanthony - do you get/see an emoji on the menubar?

**Comment by leaanthony** [comment]
Yup!

**Comment by sydsyd** [comment]
Are you on Big Sur or Catalina? It's broken for me on Big Sur

**Comment by leaanthony** [comment]
Big sur. I'll double check as I've been testing a number of plugins so I may be confusing this with another. The emoji I recall is a person with the hands out in a shrug pose.

**Comment by sydsyd** [comment]
I get this on Catalina, but not on Big Sur. I wonder what broke for me if you see that on Big Sur
![Screen Shot 2021-03-12 at 6 54 59 pm](https://user-images.githubusercontent.com/3580983/110909679-7c481880-8364-11eb-8e69-ffad5aae9fa6.jpg)

**Comment by leaanthony** [comment]
![image](https://user-images.githubusercontent.com/1943904/110919613-91c33f80-8370-11eb-9a4f-87367811d96f.png)

I'm using:
![image](https://user-images.githubusercontent.com/1943904/110919701-a8699680-8370-11eb-8bb4-924abdefeb62.png)

**Comment by sydsyd** [comment]
[dnscrypt-proxy-switcher.10s.sh.zip](https://github.com/matryer/xbar/files/6128903/dnscrypt-proxy-switcher.10s.sh.zip)
I wonder if my plugin version is the same as yours

**Comment by leaanthony** [comment]
I'm using the one in the plugin browser

**Comment by sydsyd** [comment]
I couldn't find it in the plugin browser - what section is it listed in?
