### ISSUE TITLE
Incorrect truncating

### ISSUE THREAD

**Issue by inbalboa** [matryer/xbar#619]
The length parameter is 60, but xbar truncates Unicode string after the ~30th character.
Also looks like it sometimes cuts a two-byte character in half.
![](https://user-images.githubusercontent.com/2811912/110538971-5553d180-812d-11eb-8ed3-5ee2a130ba6b.png)

**Comment by matryer** [comment]
Hi @inbalboa thanks for reporting this. I wonder if you could share a little plugin snippet that will recreate this?

**Comment by ianfoo** [comment]
I've put in a fix that should prevent improper truncation. xbar was truncating on byte length of a string, not rune length of a string.

**Comment by inbalboa** [comment]
> Hi @inbalboa thanks for reporting this. I wonder if you could share a little plugin snippet that will recreate this?

I used this for the screenshot https://gist.github.com/inbalboa/ebb8d006ccf5b339f797944f3bcf32ed

**Comment by ianfoo** [comment]
This script just outputs question marks where the Cyrillic should be, but I suspect that's just because of the language settings differ on our particular computers (I am in the US). I think the change above will address the issue you reported. When Mat makes the next release, would you give it a try and see if it resolves this issue?

**Comment by inbalboa** [comment]
> This script just outputs question marks where the Cyrillic should be, but I suspect that's just because of the language settings differ on our particular computers (I am in the US). I think the change above will address the issue you reported. When Mat makes the next release, would you give it a try and see if it resolves this issue?

Yes, it's ok now (20.0.19-beta) :)

**Comment by matryer** [comment]
Thanks @inbalboa - please let us know if you notice anything else.
