### ISSUE TITLE
bash/shell parameter has no effect

### ISSUE THREAD

**Issue by inbalboa** [matryer/xbar#620]
I even ran xbar in a terminal, but didn't see any reaction, when clicking on such items.

**Comment by ianfoo** [comment]
Can you clarify what you mean here a little more? If you can provide some example code to help reproducing the issue so it can be investigated, that would be great.

**Comment by matryer** [comment]
@ianfoo I think I found the problem here.

**Comment by matryer** [comment]
@inbalboa Can you try [the latest release](https://github.com/matryer/xbar/releases/latest) and see if the problem persists? I think I fixed it.

**Comment by inbalboa** [comment]
> @inbalboa Can you try [the latest release](https://github.com/matryer/xbar/releases/latest) and see if the problem persists? I think I fixed it.

Now it works, thank you.
