### ISSUE TITLE
dnscrypt-proxy-switcher plugin doesn't work as it does in BitBar on macOS 11.2.3

### ISSUE THREAD

**Issue by sydsyd** [matryer/xbar#621]
I've gone back to using BitBar v1.10.1 on Big Sur 11.2.3 (BitBar still works on Big Sur)
for the plugin dnscrypt-proxy-switcher.10s.sh
The plugin doesn't work in xBar when you try to change DNS settings.
If anyone has got it working in xBar - please share your experience.

**Comment by sydsyd** [comment]
Love to have your changes you made to the code and I'll hack it up in my version!

**Comment by matryer** [comment]
@leaanthony I think having pipes like that is acceptable `param1=one | param2=two | shell=echo | terminal=true | key=ctrl+e`

**Comment by matryer** [comment]
@sydsyd the latest release will now support pipes between parameters. This should be fixed now.

**Comment by sydsyd** [comment]
@matryer no, the plugin loads, but I can't switch/change settings in 2.0.21

**Comment by matryer** [comment]
I think this is another symptom of https://github.com/matryer/xbar/issues/626 - looking at it now

**Comment by matryer** [comment]
UPDATE: https://github.com/matryer/xbar/issues/626#issuecomment-796727996

**Comment by matryer** [comment]
This problem was due to the fact that shell commands weren't having their working directory explicitly set.
In v2.0.23-beta+ the working directory is set to the location of the plugin (this is expected behaviour for plugin writers). We also now copy the environment variables - usually useful for plugins that run themselves with different flags to perform some actions.

* You can try the fix out now: https://github.com/matryer/xbar/files/6123187/xbar.v2.0.22-beta-8-gfb1c436d.tar.gz

**Comment by sydsyd** [comment]
It's "almost" there.
The plugin can change settings fine, but it requires two goes before the settings change.
here's the output:

```
% cd /Applications/xbar.app/Contents/MacOS
./xbar
xbar v2.0.22-beta-8-gfb1c436d
2021/03/12 00:34:51 dnscrypt-proxy-switcher.10s.sh: /Users/admin/Library/Application Support/xbar/plugins/dnscrypt-proxy-switcher.10s.sh.vars.json, no such file:
2021/03/12 00:35:36 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:42 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:45 dnscrypt-proxy-switcher.10s.sh: exec: ./dnscrypt-proxy-switcher.10s.sh 9.9.9.9
2021/03/12 00:35:45 dnscrypt-proxy-switcher.10s.sh: action refresh
2021/03/12 00:35:45 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:45 dnscrypt-proxy-switcher.10s.sh: refreshing: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:50 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:55 dnscrypt-proxy-switcher.10s.sh: refreshing: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:55 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:56 dnscrypt-proxy-switcher.10s.sh: exec: ./dnscrypt-proxy-switcher.10s.sh 9.9.9.9
2021/03/12 00:35:56 dnscrypt-proxy-switcher.10s.sh: action refresh
2021/03/12 00:35:57 dnscrypt-proxy-switcher.10s.sh: refreshing: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:35:57 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:02 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:03 dnscrypt-proxy-switcher.10s.sh: exec: ./dnscrypt-proxy-switcher.10s.sh empty
2021/03/12 00:36:04 dnscrypt-proxy-switcher.10s.sh: action refresh
2021/03/12 00:36:04 dnscrypt-proxy-switcher.10s.sh: refreshing: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:04 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:09 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:10 dnscrypt-proxy-switcher.10s.sh: exec: ./dnscrypt-proxy-switcher.10s.sh empty
2021/03/12 00:36:10 dnscrypt-proxy-switcher.10s.sh: action refresh
2021/03/12 00:36:11 dnscrypt-proxy-switcher.10s.sh: refreshing: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:11 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
2021/03/12 00:36:16 dnscrypt-proxy-switcher.10s.sh: cycling: dnscrypt-proxy-switcher.10s.sh
```

**Comment by sydsyd** [comment]
It feels like the first change is being ignored from a timing perspective

**Comment by matryer** [comment]
The refresh wails 500ms before firing, but it isn't waiting for the shell script to finish. That could be why it hasn't updated yet. I may try it waiting for the script to finish executing before firing the refresh. I don't think it matters for the href action.

**Comment by matryer** [comment]
@sydsyd It will now wait for the underlying shell operation to complete before triggering a refresh. Does this help?

Please try it: [xbar.v2.0.22-beta-11-g871a58c9.tar.gz](https://github.com/matryer/xbar/files/6123495/xbar.v2.0.22-beta-11-g871a58c9.tar.gz)

**Comment by sydsyd** [comment]
Yes. Working as before. Now it's just the missing icon, which I believe is an issue with the plugin code.
Well done!
