### ISSUE TITLE
Font size in menu has decreased

### ISSUE THREAD

**Issue by magicus** [matryer/xbar#623]
At first I thought I was getting slightly mad, but I can swear that the menu text has changed in some of latest beta releases. It used to be the case (at least in BitBar) that the plugin output and the fixed text from xbar/BitBar was the same size. Now, the latter is as it used to be, but the former is smaller. See screenshot. (Effect is greater and easier to see when you compare with e.g. Time Machine drop down menu)
<img width="464" alt="Screen Shot 2021-03-10 at 12 00 17" src="https://user-images.githubusercontent.com/6209108/110619807-87e6e400-8198-11eb-814a-adfa07c2067b.png">

**Comment by matryer** [comment]
@magicus You're right - although it's not entirely obvious why. Perhaps @leaanthony can shed some light on this, could be a new default in Wails.

**Comment by matryer** [comment]
v2.0.17-beta has the new font size fix.

**Comment by leaanthony** [comment]
There's been no underlying change so this is pretty curious!

**Comment by magicus** [comment]
Actually, the new beta is ... well... I'm sorry to say, but it's just at bad but the other way around -- now the font is too large. :-( The "Preferences" is still what I'd consider normal font size -- it's the same as in BitBar, and in other tray icon menues. But now the plugin output is *larger* than this...

<img width="239" alt="Screen Shot 2021-03-10 at 22 45 31" src="https://user-images.githubusercontent.com/6209108/110702151-6fa3b300-81f2-11eb-9a08-8db7de905c55.png">

**Comment by matryer** [comment]
@magicus OK I'm going to try one more tweak that will go out in the next release. (will be v2.0.20-beta+)

**Comment by Joshfindit** [comment]
I was just noticing that my fonts are smaller with xbar than they are with BitBar.

![image](https://user-images.githubusercontent.com/1937155/113008794-baf41600-914d-11eb-9a49-e16a2c1aae0b.png)
*xbar to the left of the dropbox icon, bitbar to the right*

On my system (`10.13.6` and `xbar v2.0.37-beta`), the BitBar font is the system default, and xbar is something else.

@matryer Is it possible to expose the default font/size/style as a preference in xbar? I feel like MacOS is not making this easy with the change in APis due to font rendering on HiDPI displays.

**Comment by leaanthony** [comment]
Will test on High Sierra and get back to you 👍

**Comment by leaanthony** [comment]
PR #677 should fix this. Screenshots from High Sierra 👍

**Comment by Joshfindit** [comment]
The reason that I asked about a preference is that, in my experience, stuff like this is _extremely_ fiddly.

![image](https://user-images.githubusercontent.com/1937155/113163617-b6476480-9216-11eb-91de-7b2ac0f68acf.png)
*View in full to see that the tops and bottoms of the characters don't line up in the menubar. Line height for menus is bang-on though*
