### ISSUE TITLE
xbar stops displaying anything when refreshing too quickly with the API

### ISSUE THREAD

**Issue by nikersify** [matryer/xbar#624]
1. Create any plugin with output, say just `print("hello\n")` at `plugin.py`
2. Refresh the plugin twice in quick succession
```bash
open -jg 'xbar://app.xbarapp.com/refreshPlugin?path=plugin.py' & open -jg 'xbar://app.xbarapp.com/refreshPlugin?path=plugin.py'
```
3. xbar stops displaying any text, until its process gets killed and restarted.

For context, I'm trying to create a simple plugin for displaying all opened windows/spaces in [yabai](https://github.com/koekeishiya/yabai) and some of the callbacks on space/window focus change can happen simultaneously, breaking xbar.

Also, it seems like the `path` attribute has no effect, all plugins get refreshed no matter which one is specified with it.

Thanks for your work on this app, I really appreciate it.

**Comment by nikersify** [comment]
Hi, thanks for the quick release!

The changes seem to prevent the crash, but the way the limit is implemented isn't really suitable for me. If I call the API, say, 10 times "at once", all of the refreshes will queue rather than dropping the old ones.

https://user-images.githubusercontent.com/7091471/110780097-9995bd80-8264-11eb-8671-e603b9db723a.mov

In the video above I'm switching spaces quickly, ideally xbar would only refresh once when the API calls are finished.

Also a delay seem to have been introduced (around 1s?) upon each refresh, despite the script itself taking <100ms to execute in the terminal.

**Comment by matryer** [comment]
@nikersify yes, the delay is so we can see the interim state. It is `1s`.

You're right about the queuing. I suppose it would be better if it disregarded previous runs instead of running them all in order. That'll take a bit more thinking.

I'll remove the 1s delay now and push a new release.

**Comment by matryer** [comment]
@nikersify Please try https://github.com/matryer/xbar/releases/tag/v2.0.21-beta

**Comment by nikersify** [comment]
works great now for my use case, thank you so much!


https://user-images.githubusercontent.com/7091471/110784630-33ac3480-826a-11eb-8116-4b31eb21c8de.mov

**Comment by matryer** [comment]
Thanks @nikersify
