### ISSUE TITLE
Plugin browser not displaying detail on selection of plugin

### ISSUE THREAD

**Issue by darrenparkinson** [matryer/xbar#627]
Hi Mat,

I've just installed v2.0.24-beta and when I selected the option for "Plugin browser" I see the featured plugins and I can select the different categories to see other plugins. 

If I select one of the plugins by clicking it's name, the right pane goes blank.  Selecting a category or clicking home in the breadcrumb bar will bring back a list of plugins.

Also, clicking Install on one of the plugins doesn't appear to do anything.

Using macOS Big Sur Version 11.2.2

Apologies if this feature is still a WIP or I'm being a bit dim.

![Screenshot 2021-03-12 at 08 58 06](https://user-images.githubusercontent.com/4262917/110916930-3877f380-8311-11eb-8860-930dcb2e7b0f.png)

Thanks.

**Comment by matryer** [comment]
@darrenparkinson No you're right - that's a real bug. It should be fixed now, please go to an xbar menu, and choose **Preferences > Clear cache** and then click around again - you should notice an improvement?

**Comment by matryer** [comment]
@darrenparkinson Thanks for reporting this, I've verified it's working now so I'll close this issue. Feel free to comment here if you have any further difficulties.

**Comment by darrenparkinson** [comment]
Apologies for the delay in responding... I've just got around to it and can confirm that it looks great now, thanks.
