### ISSUE TITLE
No color on menubar with xbar

### ISSUE THREAD

**Issue by drbayer** [matryer/xbar#628]
I'm trying to move from bitbar to xbar, and I notice that plugins in xbar do not display color on the menubar but they do in the drop down. Here is a very simple plugin to illustrate:

test.5s.sh
```bash
#!/usr/bin/env bash

declare -a colors=('#ff0000' '#00ff00' '#0000ff')
time=$(date "+%s")
index=$((time % 3))

echo "Test ${colors[index]} | color=${colors[index]}"
echo "---"
echo "color: ${colors[index]} | color=${colors[index]}"
```

When I run this using bitbar I see the `Test` line in color on the menubar and the `color:` line in color in the drop down. When I run this using xbar I only get color on the `color:` line in the drop down. 

I'm running xbar v2.0.19-beta on macOS 11.2.3 Big Sur.

**Comment by leaanthony** [comment]
Thanks for the detailed report! We'll look into this 👍

**Comment by matryer** [comment]
I think this has something to do with this: https://github.com/matryer/xbar/issues/630

**Comment by leaanthony** [comment]
Duplicate duplicate! 😃

**Comment by matryer** [comment]
@drbayer we think this is fixed, could you try the latest release and let us know?

**Comment by drbayer** [comment]
Beautiful! Works great.

**Comment by matryer** [comment]
@drbayer thanks David :)
