### ISSUE TITLE
token too long error

### ISSUE THREAD

**Issue by tsurezuregusa** [matryer/xbar#629]
Hello, I have written a complicated script (https://github.com/tsurezuregusa/jma.bitbar/).
In xbar version 2.0.25 with OS 10.15 (thank you!), there is this error:

`parse stdout: scanning: bufio.Scanner: token too long`

It runs in SwiftBar. Old versions of the script were OK in BitBar.

**Comment by matryer** [comment]
@tsurezuregusa Firstly, congratulations - I've never seen buffo.Scanner return that error. I will use your script as input to a test and see if I can fix this.

**Comment by matryer** [comment]
@tsurezuregusa Can you run the script and paste the output of it in a gist? I don't have all the dependencies installed to run your plugin.

**Comment by tsurezuregusa** [comment]
There are three images in menus, but altogether is only 905K. Sorry that the instructions are in Japanese only...

https://gist.github.com/tsurezuregusa/160dc31448b84b3e6a7b0416ea49d61d

**Comment by matryer** [comment]
tsurezuregusa please try [v2.0.26-beta](https://github.com/matryer/xbar/releases/latest).

**Comment by tsurezuregusa** [comment]
It does work. Thank you. I look forward to see this develop!
