### ISSUE TITLE
Run scripts more than once a second

### ISSUE THREAD

**Issue by strafe** [matryer/xbar#632]
The previous workaround was to use scientific notation (e.g. `script.1e-1s.sh`). This doesn't seem to work in xbar though. 

My specific use case is displaying a list of workspaces and highlighting the focused one. When switching between workspaces the up to 1 second delay is perceivable and quite annoying.

**Comment by matryer** [comment]
@strafe I do support `ms` internally for testing. I won't recommend it in the docs, but I'd prefer that to scientific notation wouldn't you?

**Comment by matryer** [comment]
@strafe How well does the plugin perform if it's being refreshed more often?

**Comment by strafe** [comment]
> @strafe How well does the plugin perform if it's being refreshed more often?

Seems fine for me, personally I'm refreshing a script that takes roughly `60ms` to execute every `200ms`. What I would say is that I believe this is really useful functionality for certain users, but when it comes to plugins in the official repository there should probably be a lower bound on refresh rate (not below 1 second?) because depending on the script/environment I'm sure this could cause issues.

**Comment by matryer** [comment]
@strafe You've articulated my thinking perfectly.

OK, I'll do a release and you can use `filename.500ms.sh`

**Comment by matryer** [comment]
@strafe please try [v2.0.27-beta... or above](https://github.com/matryer/xbar/releases/latest).

**Comment by matryer** [comment]
Closing now that `ms` is a supported unit.

**Comment by strafe** [comment]
> Closing now that `ms` is a supported unit.

Thanks for getting this in so quick, will test it out soon!
