### ISSUE TITLE
unable to open directory "Time/itstimeto.15m.py": exit status 1

### ISSUE THREAD

**Issue by maksimov** [matryer/xbar#635]
Installed [this extension](https://xbarapp.com/docs/plugins/Time/itstimeto.15m.py.html), without exiting the preferences screen wanted to edit the code (to replace an emoji), but got this error. It worked when I reopened it via the "Open Plugin" menu.

**Comment by matryer** [comment]
Hi @maksimov thanks for reporting this, you're right - it was a bug.

**Comment by matryer** [comment]
@maksimov I think this is fixed now, can you try the latest release and let me know?

**Comment by maksimov** [comment]
Thanks @matryer, the edit button is now gone from that initial screen, so I'm unable to reproduce it.

**Comment by matryer** [comment]
@maksimov the edit button should only appear in 'installed plugins'
