### ISSUE TITLE
Plugins privacy issue

### ISSUE THREAD

**Issue by jpillora** [matryer/xbar#636]
Hey Mat,

Awesome project, and the plugin browser makes for a nice user experience, however it seems plugin contributors can host their icon/image on the web server of their choosing. If I were a bad actor, I could "contribute" an AWS plugin (default category), host my plugin image on my own tracking server, and collect a list of all xbar user IPs.

My suggestion is setup a caching image proxy on `xbarapp.com`, maybe this could be a handler like `xbarapp.com/plugin-images/<plugin-id>.jpg`?

Also this will reduce the number of Little Snitch prompts that I get by visiting the plugins browser 😁

**Comment by matryer** [comment]
@jpillora thanks for pointing this out. This has been on the list for a while for a number of reasons, speed, reliability, content moderation, but your point about privacy is a great one.

I think at the time we generate the website from the xbar-plugins repo, we should try and download the images and host them ourselves. It will also allow us to spot broken images and remove them from the experience.

**Comment by jpillora** [comment]
Sounds good - and maybe add periodic refresh to allow plug-in authors to
improve/fix their images 👍

**Comment by matryer** [comment]
Yeah, that’ll happen whenever we re-generate the site. I plan on regenerating it daily. Today it’s run manually.

**Comment by jpillora** [comment]
Ah it’s static - definitely makes sense

**Comment by matryer** [comment]
Yeah :) in fact, the entire API is just made up of static json files.

**Comment by matryer** [comment]
Thanks @jpillora - all images are now hosted in the xbar website.

**Comment by jpillora** [comment]
Awesome, nice work!
