### ISSUE TITLE
$XBARDarkMode doesn't follow the color of the status bar in 'Auto' appearance option

### ISSUE THREAD

**Issue by ggrelet** [matryer/xbar#638]
# Problem description
I'm trying to use the value of `$XBARDarkMode` to select colors for menus to be on par with macOS color mode at all times.
However sometimes my appearance shows a Light status bar color (white) but `$XBARDarkMode` has value `true`
## Reproducible script
```bash
#!/bin/bash
echo "dark mode = " $XBARDarkMode
```

## Result
Screenshot:

<img width="124" alt="image" src="https://user-images.githubusercontent.com/10114131/111191906-cfb2a480-85b8-11eb-8047-5dfb72db043f.png">

**As you can see, the variable is set to true even though the status bar is white (i.e. light mode)**

# This behavior is maybe not an xbar problem but more of a macOS problem
The command
```shell
defaults read -g AppleInterfaceStyle
```
is supposed to return the active status of the appearance mode. [Stackoverflow source](https://stackoverflow.com/a/25214873/4949074).
However when in Auto mode (that is, when the OS switches modes given the hour of the day, [as seen on this official Apple documentation](https://support.apple.com/en-us/HT208976)) the variable seems to be always set to `Dark`

The results can be compiled in the following table: 
| Selected mode in the pref panel GUI  | `AppleInterfaceStyle` output | `$XBARDarkMode` value |
| ------------- | ------------- | ------------- |
| <img width="80" alt="image" src="https://user-images.githubusercontent.com/10114131/111192704-a5adb200-85b9-11eb-98a7-a77b357e8b7d.png"></br>_Light mode_ | `2021-03-15 18:06:14.496 defaults[7806:263599] The domain/default pair of (kCFPreferencesAnyApplication, AppleInterfaceStyle) does not exist` | `false`|
| <img width="75" alt="image" src="https://user-images.githubusercontent.com/10114131/111192985-f7eed300-85b9-11eb-98a5-6b78845bf9b1.png"></br>_Dark mode_ | `Dark` | `true`|
| <img width="78" alt="image" src="https://user-images.githubusercontent.com/10114131/111193403-692e8600-85ba-11eb-8445-40cd8032e3df.png"></br>_Auto mode_ | `Dark` at all times, even if the status bar is white | `true`|

## My config
```
macOS 10.15.7
xbar 2.0.27-beta17
```

**Comment by matryer** [comment]
@ggrelet Thanks for that great report. Very interesting stuff. @leaanthony I don't suppose there's another, more deterministic, way of getting the light/dark mode status?

**Comment by leaanthony** [comment]
We're currently keying off the change event. Will check it out.

**Comment by matryer** [comment]
@leaanthony What do you think we can do about this? Is it just a quirk of macOS that we have to live with?

**Comment by matryer** [comment]
Closing because I don't think there's anything we can do about this for now.
