### ISSUE TITLE
missing xbar icon in the tab

### ISSUE THREAD

**Issue by sadhasivam** [matryer/xbar#639]
I could not see Xbar icon 

![image](https://user-images.githubusercontent.com/253447/111244033-807c6c00-85d8-11eb-859b-95dfbae28858.png)

macOS version 10.15.7 (19H114)

**Comment by leaanthony** [comment]
I believe it's been removed.

**Comment by matryer** [comment]
Hi @sadhasivam What were you expecting to see?

**Comment by sadhasivam** [comment]
I could be wrong but I thought xbar icon shows up as like Bluetooth, wifi, sound icons type macos preference
![image](https://user-images.githubusercontent.com/253447/111322130-f7e4e680-863e-11eb-80c8-3253397945ca.png)

**Comment by matryer** [comment]
I see. No we moved it for simplicity's sake, but I wouldn't be against having it back for the case when no plugins are installed. Thanks for the idea.

**Comment by matryer** [comment]
Closing for now, but thanks for the ideas.
