### ISSUE TITLE
xbar name changed to "Swift"

### ISSUE THREAD

**Issue by sadhasivam** [matryer/xbar#640]
xbar app name changed to "Swift" after i installed the "github trending plugin"

![image](https://user-images.githubusercontent.com/253447/111244411-3778e780-85d9-11eb-988e-8311fcda3c7b.png)

macOS Catalina : Version 10.15.7

**Comment by leaanthony** [comment]
What's the expected behaviour? Presumably Swift is trending on GitHub?

**Comment by matryer** [comment]
@sadhasivam It looks like xbar is working. When you install plugins, it hides the **xbar** menu item and shows the data from the plugin. Does that make sense?

**Comment by sadhasivam** [comment]
ahh. my mistake. now I understand the working model of Xbar. thanks @matryer  this is not a the issue.
