### ISSUE TITLE
Update check on startup locks the app

### ISSUE THREAD

**Issue by chew-z** [matryer/xbar#646]
Checking for latest xbar version, displaying gallery of plugins and delaying start up as a result seems like a bad idea. I would rather prefer to start my own plugin ASAP....

**Comment by matryer** [comment]
Hey @chew-z thanks for reporting this, you're right. I've introduced a delay. @leaanthony was also talking about making the dialogs a non-blocking operation too, which might be nice.

**Comment by matryer** [comment]
Closing as the update delay means it doesn't bother you right away.
