### ISSUE TITLE
xbar beta - Closing "Plugin browser..." does not close it

### ISSUE THREAD

**Issue by ramonmata** [matryer/xbar#647]
When I try to close the Plugin browser window by using the mac os top left window buttons, nothing happens.  The screen seems to go behind all other windows but stays open.

The workaround I have found is to use the "cmd + w"

regards!

**Comment by matryer** [comment]
@ramonmata thanks for reporting - you're right, it's so weird.

@leaanthony our little plugin window is very disrespectful, and is outstaying its welcome.

1. Run xbar
2. Access "Plugin browser..." from the xbar menu
3. Press the red dot to close the window
4. Window goes to the background trying to hide, but the pesky little bugger is still there

**Comment by matryer** [comment]
One workaround for now is to always leave it open :)

**Comment by thuss** [comment]
Another workaround is to use Command-h to hide it

**Comment by ramonmata** [comment]
Not familiar with Wails but maybe it allows to intercept the close event? and then app could hide the window.

**Comment by leaanthony** [comment]
Wow, are you saying all those times we tested it, we had other windows obscuring it? 😃 This has to be a fallout of the NSResponder change. Will investigate 👍

**Comment by leaanthony** [comment]
Fix pushed and will be included in next xbar release 👍

**Comment by matryer** [comment]
OK I'll release now.

**Comment by matryer** [comment]
@ramonmata please check out the [latest release](https://github.com/matryer/xbar/releases/latest) and let me know if it's better for you.

**Comment by ramonmata** [comment]
@matryer Just tested the latest release and it is working great!

**Comment by matryer** [comment]
Thanks, @ramonmata :)
