### ISSUE TITLE
Idea: Preview of new plugins

### ISSUE THREAD

**Issue by magicus** [matryer/xbar#650]
Sometimes there are multiple plugins in the plugin repository, that are trying to solve the same problem. And often then, it's mostly "look and feel" that differentiates them.

It would be great if there were some kind of "preview" functionality when browsing plugins, so that a plugin could be run and it's actual behavior shown -- not in the menu bar but in the plugin browser window. (After sufficient warning that this means that code downloaded from the internet actually will execute on your computer.)

**Comment by magicus** [comment]
Feel free to shoot this down if you do not believe it is a good idea. :)

**Comment by matryer** [comment]
@magicus This is a nice idea, although installing it and trying it is pretty easy at the moment. The trouble is, some plugins still need editing before they work, but when they transition more to using Variables, stuff like this will be easier.
