### ISSUE TITLE
Folders in the plugins directory get "executed"

### ISSUE THREAD

**Issue by gzphreak** [matryer/xbar#651]
It would appear that xbar, when trying to execute all the scripts in the plugins directory, tries to execute directories. BitBar did not do this.
![Screen Shot 2021-03-19 at 8 41 39 AM](https://user-images.githubusercontent.com/1158916/111797618-ed209080-888e-11eb-84df-e42b2f24d6b4.png)
The `Dir` function in `pkg/plugins/plugin.go` should include, in its ignore logic, something like this:
```go
if file.IsDir() {
  // ignore  directories
  continue
}
```
I would have made a PR but the readme suggests opening an issue first.

Thanks for this project. 😄

**Comment by matryer** [comment]
@gzphreak doh - nice catch. We'll fix this.

**Comment by gzphreak** [comment]
Thanks!

**Comment by matryer** [comment]
@@gzphreak please try the [latest release](https://github.com/matryer/xbar/releases/latest) and let me know if that's fixed it for you.

**Comment by gzphreak** [comment]
@matryer The [latest release](https://github.com/matryer/xbar/releases/latest) ignores directories. Thanks for the quick turn around. ❤️

**Comment by matryer** [comment]
@gzphreak most welcome - let me know if you notice any other annoyances. Have a nice weekend.
