### ISSUE TITLE
Can plugin variables be edited from the UI?

### ISSUE THREAD

**Issue by nicolasff** [matryer/xbar#655]
Hello,

I've been trying to integrate the variables feature into some of my plugins, and I've tried everything I could think of to change the values of these variables from the UI (in the ⌘+E panel for a plugin), but nothing has worked so far.

I started with the most basic plugin, saved as `test.sh`:
```sh
#!/bin/bash
#
#  <xbar.var>string(VAR_OPT_1=foo): Option 1.</xbar.var>
#  <xbar.var>string(VAR_OPT_2=bar): Option 2.</xbar.var>
#
echo test
echo ---
echo "Option 1: ${VAR_OPT_1}"
echo "Option 2: ${VAR_OPT_2}"
```

When I opened the plugin settings, I could see the two variables and their default values:
![image](https://user-images.githubusercontent.com/7276/111853688-53ca9c00-88d9-11eb-964c-e6fd2759f9f3.png)

I tried changing these strings – meaning setting a custom value that's different from the default – and I was expecting to see `test.sh.vars.json` show up in the plugins directory, but no file was created. As soon as I navigated away from the details panel for this plugin and went back, the variables had been reset to their default values.

I figured if xbar couldn't create the JSON file, maybe I could create it and it would be able to edit it. So I added `test.sh.vars.json` with the following contents:

```json
{
    "VAR_OPT_1": "from-json-1",
    "VAR_OPT_2": "from-json-2"
}
```
And after restarting the app I did see these values… not only in the menu bar:
![image](https://user-images.githubusercontent.com/7276/111853398-131e5300-88d8-11eb-82a1-1bd2467bf387.png)

but in the plugin config panel too:
![image](https://user-images.githubusercontent.com/7276/111853421-23363280-88d8-11eb-9986-4a96d3bfad2d.png)

There's even a label underneath that says "💡 You must refresh the plugin for changes to take effect."
The string fields are clearly editable, for variables defined as integers there are even up and down arrows to change the value, and booleans are displayed as checkboxes that can be changed too.

And here even though I had created the JSON file and xbar had managed to load values from it both at runtime and in the plugin config panel, nothing I did in the editor caused these values to be saved back into the file. I tried pressing Enter, I tried ⌘ + S, I tried ⌘ + R… nothing worked. The JSON file was never created if it didn't already exist, and was never updated if it did exist.

Is the editing feature for variables something that is not fully implemented yet? Or am I just using it wrong? (in which case how can I get xbar to save updated values for variables?)

**Comment by matryer** [comment]
Hey @nicolasff looks like you've found a bug. The variables should update exactly as you're expecting. We'll look into this.

**Comment by matryer** [comment]
Hey @nicolasff - please try the latest release, this should be fixed now.

**Comment by nicolasff** [comment]
Thanks @matryer! I can confirm the feature works with [release v2.0.34-beta](https://github.com/matryer/xbar/releases/tag/v2.0.34-beta).

I now see the `<name>.vars.json` file being created when I make changes to variables in the plugin settings panel, and the plugin receives the expected values as environment variables when I press the ⟲ button at the top.
