### ISSUE TITLE
malformed xbar.var format (name needs VAR_ prefix)

### ISSUE THREAD

**Issue by picatz** [matryer/xbar#656]
After updating to the latest version, I ran into https://github.com/matryer/xbar/commit/7c935c5a79626247c74b82ec74e85bca0cc64a7f which impacted a [Vault xbar plugin](https://github.com/picatz/xbar-plugin-hashicorp-vault) I've been tinkering with. The plugin still worked, but the plugin page in the xbar app now throws an error due to a malformed format. The plugin continued to function thanks to the JSON config saved on disk from the old version, but I can no longer edit the value from the app because the variables don't have the `VAR_` prefix.

```shell
# <xbar.var>string(VAULT_ADDR="http://localhost:8200"): Vault address.</xbar.var>
# <xbar.var>string(VAULT_TOKEN=""): Vault API token.</xbar.var>
# <xbar.var>string(VAULT_CACERT=""): Full path to the Vault CA cert.</xbar.var>
# <xbar.var>string(VAULT_CLIENT_CERT=""): Full path to the Vault client cert.</xbar.var>
# <xbar.var>string(VAULT_CLIENT_KEY=""): Full path to the Vault client key.</xbar.var>
```

<img width="1076" alt="Screen Shot 2021-03-20 at 7 00 54 PM" src="https://user-images.githubusercontent.com/14850816/111887913-9b6f2780-89ae-11eb-8ed5-d30400542925.png">

These environment variables were helpful/easy as a plugin developer, since they are [naturally supported](https://www.vaultproject.io/docs/commands#environment-variables) by the `vault` binary on the system.

🤔 Would it make sense to continue supporting setting any environment variables from the config as a feature?

**Comment by matryer** [comment]
@picatz I think you're right. The `VAR_` prefix was supposed to prevent clashes but maybe we can trust plugin developers a little more than this. I'll remove this constraint.

**Comment by matryer** [comment]
@picatz please try the latest release and let me know how that is for you.

**Comment by picatz** [comment]
Works with the latest release ( [v2.0.33-beta](https://github.com/matryer/xbar/releases/tag/v2.0.33-beta) ). Thank you!

**Comment by matryer** [comment]
No @picatz thank you.
