### ISSUE TITLE
Get "https://xbarapp.com/docs/plugins/categories.json": context deadline exceeded

### ISSUE THREAD

**Issue by raguay** [matryer/xbar#657]
Just found this version of the program and installed it. When trying to browse the categories, this is put on the top.

**Comment by raguay** [comment]
Pressing the refresh button fixed the issue and it seems to be working. After closing and restarting, the issue never shows up again. Just the very first time the program is ran.

macOS Catalina 10.15.7

**Comment by matryer** [comment]
@raguay it looks like that first request is just taking a long time. I'll increase the timeout.
