### ISSUE TITLE
Output format seems to be broken

### ISSUE THREAD

**Issue by vedhavyas** [matryer/xbar#662]
Here is what I tried so far...
Flow:
- Brew install
- start xbar
- when I click on the app, it showed `missing ~/.bitbarrc`
- Created the file
- Added github-ci plugin and updated the `~/.bitbarrc` file accordingly

What I expected:
I expected to see the result of the github ci formatted.

What I see:
<img width="244" alt="Screenshot 2021-03-25 at 7 04 24 PM" src="https://user-images.githubusercontent.com/7549475/112522150-91c63500-8d9d-11eb-8ffe-a40f074bfea5.png">

What am I doing wrong ?

**Comment by leaanthony** [comment]
xbar doesn't use .bitbarrc at all. The [plugin](https://xbarapp.com/docs/plugins/Dev/GitHub/github-ci.1m.php.html) appears to be trying to read it to get settings. The plugin will need to be updated.

**Comment by matryer** [comment]
@vedhavyas yeah @leaanthony is right - there's no support for that file.

Is it worth sourcing that file (if it exists) in the plugin itself?

**Comment by vedhavyas** [comment]
@matryer even before I added the plugin, I got 	`missing ~/.bitbarrc` error on xbar. Is that not expected?

**Comment by leaanthony** [comment]
xbar itself does not reference that file. It must be coming from a plugin. Can you paste that message here please?

**Comment by vedhavyas** [comment]
@leaanthony I guess u are right. Not seeing that error anymore. Thanks!
