### ISSUE TITLE
Is xbar.var working?

### ISSUE THREAD

**Issue by kawarimidoll** [matryer/xbar#668]
Hello,

I'm trying to write my plugin with variables.
I copied the code from https://xbarapp.com/docs/2021/03/14/variables-in-xbar.html, but this didn't work...

My plugin `~/Library/Application Support/xbar/plugins/hello.10m.sh` is below:
```sh
#!/bin/bash

# <xbar.var>string(VAR_NAME="World"): Your name.</xbar.var>
echo "Hello, ${VAR_NAME}"
```

The output on the menubar is only "Hello,", as this screenshot (I added annotations).

![screenshot](https://user-images.githubusercontent.com/8146876/112743809-6f1e6100-8fd5-11eb-8931-fbb880afc5ee.png)

It was not changed after refresh.

Do I need any other settings to use variables?

Version: macOS 11.2.3, xbar v2.0.33-beta

**Comment by matryer** [comment]
@kawarimidoll The UI is broken... fixing now...

**Comment by matryer** [comment]
@kawarimidoll please try the latest release, this should be fixed now.

**Comment by kawarimidoll** [comment]
It works! Thank you for the quick fix 😄
