### ISSUE TITLE
Default variable value not being honoured on first run

### ISSUE THREAD

**Issue by Joshfindit** [matryer/xbar#669]
When modifying the `Network/bandwidth_primary.1s.sh` plugin (https://github.com/matryer/xbar-plugins/pull/1566)

I set the variable as documented:
`<xbar.var>string(VAR_NETWORK_INTERFACE="en0"): The interface to track (Usual interface for MacOS wifi is en0)</xbar.var>`

Then closed and reopened xbar, and browsed to to Plugin Browser.
It did show successfully:
![image](https://user-images.githubusercontent.com/1937155/112754799-26a27b80-8fb4-11eb-9b1e-5e7eb2275db3.png)

However, `001-bandwidth.1s.sh.vars.json` was not created and the variable was not passed in to the plugin.
(Verified by `echo`ing `${VAR_NETWORK_INTERFACE}`)

I had to change the value in xbar before it created `001-bandwidth.1s.sh.vars.json` then change it back to `en0` to track the proper interface.

**Comment by matryer** [comment]
Hey @Joshfindit thanks for reporting this, I think you found a bug where default values weren't being used unless you explicitly change them. Will look now.

**Comment by matryer** [comment]
@Joshfindit I think I've fixed it, can you confirm by trying the [latest release](https://github.com/matryer/xbar/releases).

**Comment by Joshfindit** [comment]
Awesome, I do confirm that the bug is resolved in `v2.0.35-beta`.
It loads defaults without issue, and displays the variable in the Plugin Browser.

Thank you
