### ISSUE TITLE
xbar not able to record screen

### ISSUE THREAD

**Issue by juanpac** [matryer/xbar#671]
I don't think this is a plugin problem but an xbar one, since the plugin only calls screencapture command

When using ScreenShooter plugin, xbar asks for Screen Recording permissions as expected.

But the permission is not honored and you can see it will ask again after a restart.

I'm using 2.0.35beta version.

![](https://user-images.githubusercontent.com/25234447/112851130-eac8ee00-9067-11eb-9227-dfdd5bae7395.png)

**Comment by matryer** [comment]
@leaanthony Do you know if the app requires specific entitlements to access special features like this?

**Comment by leaanthony** [comment]
I'll need to research this. I would have thought this would be between the plugin and the OS

**Comment by matryer** [comment]
Yeah me too - but I wonder if they share 'privileges' or 'entitlements' with the launching app.

**Comment by leaanthony** [comment]
I'll look it up but as we're spawning the process, you'd think it would be out of your hands

**Comment by shepazon** [comment]
I've found this to be the case with any of these privileges I encounter in shell scripts; the privilege has to be given to the parent application, whether that be Terminal or xbar.

**Comment by leaanthony** [comment]
The tricky thing about that is knowing what privileges scripts will require at sign time!

**Comment by juanpac** [comment]
maybe this info helps:

if i run the exact same command xbar would run itself from a terminal, it does the job.

but if i try to do it using xbar, it will ask me again to grant screen recording permissions to xbar

despite both Terminal and xbar being listed on allowed apps to screen record.

using v2.0.42beta

**Comment by leaanthony** [comment]
It must be related to the fact that the script is being launched from xbar. Does it work if you set terminal=true?

**Comment by juanpac** [comment]
no, it doesn't.

I have duplicated the menu entry to use one command with terminal=true and the other with terminal=false (as the original)  
The terminal=true don't do anything at all.  
terminal=false option ask again for permissions to be granted.

**Comment by juanpac** [comment]
Somehow xbar asked me to allow control "System Events.app".  
After accepting, xbar is not asking to grant screen recording permissions again and the screencapture command works as expected.  
I don't think this is an issue anymore.
