### ISSUE TITLE
Variables Unknown xbar.var type: list

### ISSUE THREAD

**Issue by ramonmata** [matryer/xbar#673]
I was trying this new feature but Plugin browser always return this error message:
`Something went wrong, this: unknown xbar.var type: list `

The metadata I used was: (as [documented](https://xbarapp.com/docs/2021/03/14/variables-in-xbar.html))
`#  <xbar.var>list(VAR_STYLE="normal"): Which style to use. [small, normal, big]</xbar.var>`

So took a look in the code and `plugin_metadata_test.go` is expecting `select` so I tried, error is gone, but dropdown is not rendered in the screen.

**Comment by matryer** [comment]
@ramonmata you're right - it was changed from `list` to `select` but wasn't updated everywhere. Thanks for pointing it out, I'll fix this today.

**Comment by matryer** [comment]
@ramonmata please try the latest release, and let me know

**Comment by ramonmata** [comment]
Hi @matryer, it works!
