### ISSUE TITLE
Remain left most menu item

### ISSUE THREAD

**Issue by adamkdean** [matryer/xbar#678]
With the original BitBar, if new menu icons appeared, you could refresh all BitBar scripts and they would appear on the left. However with the recent updates, while refresh still works, the menu objects are no longer recreated and thus, if you wish to position XBar back on the left-most side of icons, you have to quit and restart it.

I use a single script that displays text, so I like to keep it on the left. I imagine with icons it doesn't matter their position.

![image](https://user-images.githubusercontent.com/1639527/113129388-bb0a1980-9212-11eb-9c91-5267d94344ff.png)

> (IP obfuscated, but usually text is there, not a gap)

Is there anything we can do to ensure it remains on the left?

**Comment by magicus** [comment]
I wonder if this is also related to how xbar behaves in conjunction with Bartender 4. I'm running both, and most of the times it works fine, and sometimes the icons just gets shuffled around. I was planning on opening a bug as soon as I had figured out exactly what was going on. Restarting/refreshing tend to mess with things, though, is my impression.

**Comment by matryer** [comment]
@adamkdean @magicus thanks for reporting this, I don't see this behaviour. Perhaps you can elaborate on exactly what you have running so I can try and recreate it?

**Comment by leaanthony** [comment]
I've just looked through the BitBar code and there's nothing to indicate a preferred location within the system extras panel, so I suspect that Bartender is moving them around. If you are keen on setting this as a preference, there's an interesting thread [here](https://github.com/Mortennn/Dozer/issues/69) about doing just that. However, I suspect Bartender may be modifying these preferences to do what it does so YMMV.

**Comment by adamkdean** [comment]
@matryer Other than a few other apps that also place items in the menu bar, it's just XBar. No Bartender or any other menu bar altering applications. Here's something you may be able to do to try and replace it:

Create an XBar plugin script that simply outputs some text, and then after that has launched, launch or restart any app that also places an item in the menu bar. If you have nothing ordering the icons, then the new icon (of the app you launched after XBar) would be placed on the left most side, moving your XBar text further toward the right.

If you then click the XBar plugin text and select refresh, you'd expect it to appear on the left most side again (at least, that was the behaviour within Bitbar), but for me, it retains its position.

I'm not necessarily sure if this is a bug really, just a curious change in behaviour from Bitbar.

Thanks all for your contributions

**Comment by leaanthony** [comment]
It sounds like bitbar would remove the different components rather than refresh them.

**Comment by matryer** [comment]
I think BitBar would destroy and recreate menus. xbar is more memory efficient, and reuses the menu items if it can. So I'd say this is expected behaviour now. I don't think there's much we can do to ensure xbar appears on the left, except maybe delay it starting up or something - but that seems strange.

Closing this for now.

**Comment by adamkdean** [comment]
That makes sense. No worries folks, thanks for discussing.
