### ISSUE TITLE
your 'Info.plist' file is named 'info.plist'

### ISSUE THREAD

**Issue by core-code** [matryer/xbar#685]
meaning the app won't work on any case-sensitive file-system

**Comment by leaanthony** [comment]
Thanks for raising this. It will be addressed by #686

**Comment by matryer** [comment]
Fixed in new release. Thanks all.

**Comment by core-code** [comment]
awesome thanks

**Comment by core-code** [comment]
actually, in 2.0.40-beta it is still lowercase "info.plist" so i cannot confirm this has been resolved

**Comment by leaanthony** [comment]
@matryer - just double check you've removed `info.plist` from your local `app/assets/Mac` dir. As the FS is case insensitive it'll pick it up.

**Comment by matryer** [comment]
![image](https://user-images.githubusercontent.com/101659/113587115-40803600-9626-11eb-9c1e-8b7c1d38bf2b.png)

Can someone else's brain please confirm that this is right?

**Comment by matryer** [comment]
Let's see if this is better: https://github.com/matryer/xbar/releases/tag/v2.0.41-beta

**Comment by core-code** [comment]
sorry but i don't see any improvements:

```
ls -la /Volumes/Install\ xbar/xbar.app/Contents/
total 8
drwxr-xr-x  5 julian  staff   170 Apr  5 16:49 .
drwxr-xr-x  3 julian  staff   102 Apr  5 16:49 ..
drwxr-xr-x  3 julian  staff   102 Apr  5 16:49 MacOS
drwxr-xr-x  3 julian  staff   102 Apr  5 16:49 Resources
-rw-r--r--  1 julian  staff  1116 Apr  5 16:49 info.plist
```

i downloaded `xbar.v2.0.41-beta.dmg` and did not check the `tgz` version

**Comment by matryer** [comment]
I’m baffled. Might just drop my iMac out the window.

**Comment by matryer** [comment]
@core-code ok - how about now? (And thank you for your patience while we get this right)

**Comment by core-code** [comment]
its fixed now, thanks!
