### ISSUE TITLE
(bash plugin) Escape sequences doesn't work

### ISSUE THREAD

**Issue by The-Michael-R** [matryer/xbar#689]
Change the color using escape sequences fail:
```bash
#!/bin/bash

echo -e "WOL\033[32m⇡\033[0m"
```
result in: 
```
WOL[32m⇡[0m
```
Obviously with no color for the arrow. Running the script in terminal does the right thing.

That used to work in BitBar.

**Comment by leaanthony** [comment]
This is in progress 👍

**Comment by leaanthony** [comment]
#703 fixes this

**Comment by leaanthony** [comment]
Please check latest version

**Comment by The-Michael-R** [comment]
@leaanthony: Yes, works as expected.

Thank you!
