### ISSUE TITLE
Please demonstrate how to open an application from xbar?

### ISSUE THREAD

**Issue by dstranathan** [matryer/xbar#690]
I have a "Get Support" xbar sub-menu that provides typical IT URLs to my IT help desk site (ServiceNow), as well as user-facing KBs and documentation (Confluence). Very useful for end-users.

I'd like to add a clickable link to open a specific screen-sharing app located in /Applications (TeamViewer QuickSupport.app). 

I have tried everything to get xbar to open an app when selected (via zsh plug-in), but I'm unable to do so. Can someone please provide an example of the appropriate API syntax, please?

Thanks!

**Comment by matryer** [comment]
This worked for me:

```
echo "Say hi | shell=open | param1=/Applications/Pages.app"
```

**Comment by matryer** [comment]
@dstranathan I hope this answers your question?
