### ISSUE TITLE
Run in terminal misses xbar.var entires

### ISSUE THREAD

**Issue by The-Michael-R** [matryer/xbar#692]
Using <xbar.var> parameters are not used in terminal:
```bash
#!/bin/bash
# <xbar.var>string(VAR_FOO="Bar"): Foo.</xbar.var>

echo ">${VAR_FOO}<"
```
Works in the menu bar (it should show **>Bar<**)  but the terminal stays empty.
```
><
```

**Comment by matryer** [comment]
Thanks @The-Michael-R. This is a good point. The appropriate env vars won't be getting set in the same way. We'll look into this.

**Comment by matryer** [comment]
@The-Michael-R Can you try this build for me please and let me know if it's working for you?

[Uploading xbar.v2.0.42-beta-1-gfcd8eec.tar.gz…]()

**Comment by The-Michael-R** [comment]
@matryer Yes, that seems to work as expected.

That way you set the variables actually shows another (small!) issue: The <pluginname>.vars.json file will remember all variables ever used. Including obsolete ones that were used during development (ore got remaned). I think a note in the readme.md here in git will be sufficient as this only troubles plugin developers.

**Comment by matryer** [comment]
@The-Michael-R Hmm, I'm not sure that's a big enough problem to solve. Although, I do want the dev experience to be better.

Would a "Reset to defaults" button in the UI work? It could just delete that `.vars.json` file?

**Comment by The-Michael-R** [comment]
@matryer How about re-writing the complete json file all the time with the current values and not just update the changed value? That's my assumption what the code currently does. And this would allow you to first do a backup of the values (`mv <pluginname>.vars.json <pluginname>.vars.json.bak`) as a feature.

Writing the complete files is probably not as performant, but this happens only during configure the plugin. So not during the 'normal' operation.

But a 'reset to defaults' button would do as well.

**Comment by matryer** [comment]
OK @The-Michael-R I'm going to close this one, since the vars are now working in Run in terminal. I do like the idea of a "Reset to defaults" button, because it'll be very easy to implement.

**Comment by The-Michael-R** [comment]
@matryer yes makes sense. And thank you for the fix and the great app!
