### ISSUE TITLE
xbar.app requests access to control "System Events.app" after each and every update

### ISSUE THREAD

**Issue by ggrelet** [matryer/xbar#696]
The title is self explanatory but here is a screenshot (sorry it is in French):
<img width="532" alt="Capture d’écran 2021-04-07 à 09 30 24" src="https://user-images.githubusercontent.com/10114131/113828065-47bd5600-9784-11eb-8ede-1207f24ea055.png">
That roughly translates to:

> "xbar.app" requests authorization to control "System Events.app". Accept if you want to allow it to access files and data located in "System Events.app" and to allow actions.

> | Do not allow |     | OK |

I'm running on a mi-2014 MBP with macOS 10.15.7. This behavior happened again this morning when updating from 2.0.39 to 2.0.42 but from what I recall, has happened every time in the last 4 to 5 updates I allowed.

**Comment by matryer** [comment]
@ggrelet Thanks for opening this. We recently fixed the bundle identifier, so I suspect this will stop happening. Can you keep an eye on it for me, and when there's another update see if it happens again? Hopefully it's fixed.

**Comment by matryer** [comment]
@ggrelet have you seen this since?

**Comment by ggrelet** [comment]
> @ggrelet have you seen this since?

No, I think you can close, indeed! Thanks

**Comment by matryer** [comment]
Thank you.
