### ISSUE TITLE
Get "https://xbarapp.com/docs/plugins/featured-plugins.json": dial tcp: lookup xbarapp.com: no such host

### ISSUE THREAD

**Issue by edjusted** [matryer/xbar#700]
Just reporting the issue (on startup) as requested.

**Comment by matryer** [comment]
Hey @edjusted - can you access that URL in a browser?

**Comment by edjusted** [comment]
Hi @matryer Yes. And I also checked Little Snitch and xbar has full internet access. But I also just noticed that I'm on beta 2.0.39 so I upgraded to 2.0.42. On relaunching xbar, Little Snitch complained...something about xbar being different but I ok'd it.

It's working now, so I'm closing this. Thanks!
