### ISSUE TITLE
xbar:// control API fails

### ISSUE THREAD

**Issue by jonzhan** [matryer/xbar#702]
Using v2.0.42-beta

If I use the cli and try:

`open "xbar://app.xbarapp.com/openPlugin?path=test.60m.sh"`

I get:

`The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-600 "procNotFound: no eligible process with specified descriptor" UserInfo={_LSLine=379, _LSFunction=_LSAnnotateAndSendAppleEventWithOptions}`

I'm pretty sure that it used to work in a previous version. 🤔

**Comment by matryer** [comment]
Hi @jonzhan, thanks for reporting. What OS version are you using?

**Comment by ciaranmag** [comment]
I experienced the same issue on
MacOS 11.2.3 Big Sur

updated to 
MacOS 11.3 Big Sur

and it is no longer an issue

**Comment by jonzhan** [comment]
> Hi @jonzhan, thanks for reporting. What OS version are you using?

I have just tried again for the first time since updating to MacOS 11.3 Big Sur like @ciaranmag and it is also no longer an issue for me!

**Comment by jonzhan** [comment]
Closed: Resolve by updating MacOS
