### ISSUE TITLE
Toggling dark/light mode causes text plugins to disappear

### ISSUE THREAD

**Issue by bcuccioli** [matryer/xbar#707]
1. Have a plugin which outputs text, e.g. `print "hi"`.
2. Start xbar with the system theme set as either light or dark.
3. Toggle system theme

The text output of the plugin stops rendering in the menu bar, although the plugin's space is still interactable, even if you toggle back. You need to restart xbar to have it showing up again.

**Comment by leaanthony** [comment]
What version of MacOS are you using?

**Comment by bcuccioli** [comment]
11.2.3

**Comment by leaanthony** [comment]
I'm not able to reproduce. What is your plugin? Using this:
```
#!/usr/bin/env bash

echo "hi"
echo "---"
echo "hello world!"
```
I get the following when switching between dark/light theme:
![Screenshot 2021-04-21 at 6 54 33 am](https://user-images.githubusercontent.com/1943904/115462960-9bdd3580-a26e-11eb-925e-7314f10a3860.png)
![Screenshot 2021-04-21 at 6 54 20 am](https://user-images.githubusercontent.com/1943904/115462974-9ed82600-a26e-11eb-8cc4-cb94b25b95b9.png)

**Comment by bcuccioli** [comment]
I investigated further. It seems that when toggling light/dark mode, the plugins are re-run. My plugin was making a network request, and the server on the other end handles fast subsequent requests very very slowly. I'll close this issue. Sorry for the false alarm!

I'm not sure if it's intentional that we re-run plugins when toggling light/dark mode - is that a bug?
