### ISSUE TITLE
Access calendar from Python or Bash

### ISSUE THREAD

**Issue by jchomarat** [matryer/xbar#709]
I am writing a simple command to get my next calendar event.
For that I am using icalBuddy that can read the Calendar.

The script is very simple:

```python
#!/usr/bin/env python3
import subprocess
import os
from typing import NewType

next_event = subprocess.Popen(
    [
        "icalBuddy", "-b", "", "-sd", "-n", "--noCalendarNames",
        "-li", "1", "-tf", "%H:%M", "-iep", "title,datetime,notes", "-po", "title,datetime,notes",
        "eventsToday"
    ],
    stdout=subprocess.PIPE,
    universal_newlines=True,
    env = {'PATH': '/opt/homebrew/bin:%s' % os.environ['PATH']}
).stdout.readlines()

print(next_event[2])
```

it should just display for now the next event title.

It works on terminal, but on the topbar, xbar says that `next_event`is empty. So that means that the command `icalBuddy` returns an empty output. 

I am not sure if it's permission related (xbar should have access to the calendar) or something else. Any idea?

Thanks

**Comment by matryer** [comment]
Hey @jchomarat thanks for your question. I can't think of any reason why this would be the case, xbar just executes your plugin script in a very normal way. Are you seeing any other kinds of errors?

@leaanthony Could @ jchomarat be right, would xbar itself need these permissions?

**Comment by leaanthony** [comment]
Not sure. How are app developers supposed to know what permissions scripts will need ahead of time? My understanding is that MacOS asks the user to grant the permissions on demand. Maybe there's something i'm missing.

**Comment by matryer** [comment]
Maybe code signing will help here, we'll prioritise this, again :)

**Comment by jchomarat** [comment]
I tried to read the `~/Library/Calendar` directly from a bash script, this script being called by xbar, and it worked - I can then reproduce what icalbuddy is doing manually. So maybe the issue is on iCalBuddy's side not xbar ... This being said, having the app signed would be awesome :) Thanks

**Comment by alins** [comment]
@jchomarat have you managed to make `icalBuddy` work? i have the same problem, even with the latest signed build of xbar

**Comment by alins** [comment]
found a solution here: https://forum.keyboardmaestro.com/t/icalbuddy-doesnt-work-within-keyboard-maestro-mojave-calendar-permissions/15446/6

**Comment by jchomarat** [comment]
Nope, I did it in bash instead ... but i'll look at your link, thanks

**Comment by matryer** [comment]
@jchomarat the latest version is signed, I wonder if this would help?

Closing this issue as we seem to have found a workaround.
