### ISSUE TITLE
Unable to open xbar after quitting

### ISSUE THREAD

**Issue by ianrispin** [matryer/xbar#710]
After quitting xbar, I get the following error message when I attempt to open the app again:
![image](https://user-images.githubusercontent.com/50210259/115621657-ac5fd100-a2ab-11eb-9fe0-6a7edcdbc7a8.png)
It reopens properly after restarting my mac, but I would prefer to not have to restart every time I quit the app. I am on version v2.0.42-beta of xbar and macOS Catalina 10.15.7.

**Comment by tgrrr** [comment]
Same problem. Same version of Catalina. Xbar version: xbar.v2.0.42-beta.dmg.

I previously had bitbar installed.

**Comment by leaanthony** [comment]
Are you able to bring up a process Pietro see if the application quits correctly? I'm wondering if there's a shutdown issue on this OS version

**Comment by matryer** [comment]
@ianrispin thanks for reporting this, I've seen this during development but never when running the prod app. Can you detail the exact steps you took to recreate this please?

**Comment by matryer** [comment]
Please try the latest version, with code signing we expect this to be improved.

**Comment by ianrispin** [comment]
Fixed, closing this issue
