### ISSUE TITLE
Linode plugin output flashes

### ISSUE THREAD

**Issue by galexa** [matryer/xbar#715]
The output of the Linode checking plugin flashes in the menu bar, on for 5 seconds, off for 5 seconds **roughly**. Refresh is set to 10m. Anybody else seeing this? Or any ideas on a fix? I'm on M1 with Big Sur. Thanks.

**Comment by matryer** [comment]
@galexa This sounds like an issue with the plugin, the best thing would be to open an issue via the app's **Open Issue...** button for that plugin.

**Comment by galexa** [comment]
sorry, I'm not a big GitHub user so might have got this wrong again. I clicked the Open Issue button in the Browser so hopefully it's gone to the right place this time, although I suspect it's a dead plugin. Thanks for your work anyway.
