### ISSUE TITLE
Write script without absolute shebang

### ISSUE THREAD

**Issue by RayPS** [matryer/xbar#721]
I've been using Nodejs to make my own Bitbar scripts for years.
There's the shebang in the beginning of my every scripts:
```
#!/usr/bin/env /path/to/the/node/executable
```

But recently, for some reason on my work, the path to my node will need to change very frequently.
I can't use absolute path to my node anymore.
I wonder is there a way to use something like:

```
#!/usr/bin/env node
```

to let bitbar find it from my env variables?

I've tried a way from this [stackoverflow post](https://unix.stackexchange.com/questions/65235/universal-node-js-shebang) but it didn't work

**Comment by matryer** [comment]
That looks right to me. What happens when you execute `/usr/bin/env node` in terminal?

**Comment by RayPS** [comment]
<img width="426" alt="Screen Shot 2021-05-22 at 11 18 24" src="https://user-images.githubusercontent.com/1941540/119213102-6fc40700-baef-11eb-97ef-4aa021504d83.png">

In my terminal:
```bash
$ /usr/bin/env node
Welcome to Node.js v16.1.0.
Type ".help" for more information.
>
```

Error message from xbar: `exit status 127: env: No such file or directory`

**Comment by pshirali** [comment]
@RayPS the issue you are facing is with environment variables.

You will have to consider supplying the absolute path to node in the shebang
```
#!/path/to/the/node/executable
```

Reason: When `env` is executed, the `PATH` isn't set to find `node`. The same is true with other languages like  `python`

You can test it using this script (add this as a plugin).

This plugin dumps environment keys and the current `PATH` into a file `TEST_ENV_CONTENT`. The output file is placed a level below the plugins folder to avoid this file from being considered for execution.
```
#!/usr/bin/env bash

awk 'BEGIN{for(v in ENVIRON) print v}' > ../TEST_ENV_CONTENT
echo "---" >> ../TEST_ENV_CONTENT
echo $PATH >> ../TEST_ENV_CONTENT
echo "Dumped ENV"
```

The output I find in `TEST_ENV_CONTENT` on my system is:
```
XBARDarkMode
Apple_PubSub_Socket_Render
BitBarDarkMode
LOGNAME
XPC_SERVICE_NAME
USER
PATH
__CF_USER_TEXT_ENCODING
SHLVL
TMPDIR
SECURITYSESSIONID
HOME
SHELL
_
PWD
SSH_AUTH_SOCK
XPC_FLAGS
---
/usr/bin:/bin:/usr/sbin:/sbin
```

The number of environment variables set at this point are limited (lower than those which typically get set on terminal once bashrc/bash_profile have been sourced)

Also, observe that the PATH is just `/usr/bin:/bin:/usr/sbin:/sbin`

cc: @matryer

**Comment by RayPS** [comment]
@pshirali Thanks for the hint. That makes lots of sense.
I solved this by launching Bitbar in my terminal, so my PATH is loaded before bitbar launches.
```
>　open /Applications/xbar.app
```
After this my **PATH**s is appeared in `TEST_ENV_CONTENT `
Next thing to do I will try to automate this or find a way to launch bitbar with my PATHs.
Thanks!

**Comment by RayPS** [comment]
@pshirali Try adding this one to see if you can get your PATHs?
```
echo `/usr/libexec/path_helper` >> ../TEST_ENV_CONTENT
```

**Comment by leaanthony** [comment]
Would getting xbar to run `path_helper` to load paths at startup be a solution?
