### ISSUE TITLE
Now playing menu bar item that if clicked opens the Big SurBig Sur Music widget.

### ISSUE THREAD

**Issue by Aahil52** [matryer/xbar#723]
I want to make a now playing menu bar item that if you click on it, it opens the Big Sur music widget. Is this possible?

**Comment by matryer** [comment]
@Aahil52 the short answer is, we don't know. But you can run any script using xbar, so if you can find a way to do this in bash (or some other way) then it should be possible with xbar. Sorry we can't help more with specifics like this.
