### ISSUE TITLE
Apple sillicon support for xbar

### ISSUE THREAD

**Issue by ashwaniii** [matryer/xbar#727]
I just realized xbar is running through Rosetta2 on M1 Macs.
Is native support in consideration?
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/33101255/120105138-4f421f80-c175-11eb-80a2-757ba2c5ec49.png">

**Comment by matryer** [comment]
@ashwaniii yes - coming soon

**Comment by leaanthony** [comment]
Please check latest release

**Comment by leaanthony** [comment]
Apple Silicon builds available.
