### ISSUE TITLE
What controls path for xbar?

### ISSUE THREAD

**Issue by Raboo** [matryer/xbar#730]
Hi

Having a shebang like `#!/usr/bin/env python3` doesn't seem to work because it doesn't appear to have `/usr/local/bin` in the path. Instead I have to specify the full path to python3 `#!/usr/bin/env /usr/local/bin/python3` or just `#!/usr/local/bin/python3`

What is it that controls the xbar path? wouldn't it be sane to include /usr/local/bin by default?

**Comment by sfuerte** [comment]
`/usr/local/bin` isn't in the default `PATH`. 
Using the following shebang works for me: `#!/usr/bin/env -S PATH="/usr/local/bin:${PATH}" python3`

**Comment by matryer** [comment]
@Raboo did that work for you?

**Comment by matryer** [comment]
Closing, hoping that helps. Please reopen if not.
