### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Etheryte** [matryer/xbar#731]
xbar version: v2.0.42-beta  
macOS version: 10.15.7  

Starting xbar up, it uses about 40MB. Running for a few minutes, it builds up to 50MB. Left unchecked for hours, it ended up using multiple GBs which eventually caught my attention.  

Running [Instruments' Leaks tool](https://en.wikipedia.org/wiki/Instruments_(software)) on the process shortly after startup yields thousands of small leaks over a roughly two-minute time span. The majority of the leaks stem from `CreateMenuItemCallbackData`:  

<img width="2160" alt="Screenshot 2021-06-17 at 16 06 07" src="https://user-images.githubusercontent.com/3171718/122402375-b5a0ad80-cf7d-11eb-821f-dd44a66de8f8.png">

I removed all of my scripts to narrow down the scope of the problem, left only the following script running as `foo.2s.sh`, and the leak persisted:  

```
#!/usr/bin/env bash

echo "Foo"
```

I don't know whether this problem is new or a regression since I've only started using xbar recently.  

I've checked the following versions and the leaks are present in all of them:  
 - v2.0.42-beta  
 - v2.0.37-beta
 - v2.0.27-beta

**Comment by Etheryte** [comment]
The old codebase [version 1.9.1](https://github.com/matryer/xbar/releases/tag/v1.9.1) doesn't seem to leak memory and currently I'm using that as a workaround.

**Comment by leaanthony** [comment]
Thank you so much for this!! I'd tried in vain to get Valgrind working on Mac so thanks for bringing this tool up. Can address this much quicker now 👍👍👍

**Comment by leaanthony** [comment]
Thanks to your amazing work, this will be fixed in #736

**Comment by Etheryte** [comment]
Confirmed that this issue is resolved in [release v2.1.0-beta](https://github.com/matryer/xbar/releases/tag/v2.1.0-beta). Thanks a lot for your help and time.
