### ISSUE TITLE
jq not working

### ISSUE THREAD

**Issue by peha2407** [matryer/xbar#732]
Hi matryer
I am very enthusiastic about xbar. But now I have a problem: For a script I have brewed "jq" with homebrew. This command is executed in the terminal, but not by xbar. 
The script I run is called:
#!/bin/bash
echo "SMA 🌡"
echo "---"
echo -n "SMA: " > /Users/peter/Library/Caches/SMA.txt; curl -s "https://app-prod-ws.meteoswiss-app.ch/v1/stationOverview?station=SMA" | jq | grep "temperature" | cut -c20- | rev | cut -c2- |rev >> /Users/peter/Library/Caches/SMA.txt; echo $(cat -s /Users/peter/Library/Caches/SMA.txt)"°C"
exit 0
The command "jq" is not executed, the menu displays "SMA 🌡" and then "SMA: °C" instead of, for example, "SMA: 18.3°C". 
What can I do?

**Comment by jsok** [comment]
I found that I needed to add `$(brew --prefix)/bin` to the `PATH` in my script. Alternatively you can hardcode it like `/usr/local/bin/jq`.

**Comment by matryer** [comment]
Closing. :)
