### ISSUE TITLE
`signal: killed` error

### ISSUE THREAD

**Issue by alisterburt** [matryer/xbar#735]
Thanks for xbar, such a fun app to play with!

I've been toying with a few custom plugins on an M1 macbook air running Big Sur (11.2.1) and keep running into a `signal: killed` error - I'm not sure exactly what causes it. If it helps, I also keep seeing #710.

![image](https://user-images.githubusercontent.com/7307488/123562877-4c087680-d7a9-11eb-9b05-3d765ec05913.png)

**Comment by matryer** [comment]
Hey @alisterburt thanks for reporting this. It looks like an issue with the plugin itself, can you link to it?

**Comment by alisterburt** [comment]
Hi @matryer - it's a simple script I wrote myself which can be found at https://gist.github.com/alisterburt/15280eae3d03ccb28e45713c3e10aeed

Since restarting I've only seen this issue very rarely, usually after waking the mac up from sleep

**Comment by darylzz** [comment]
I got the same issue. It might be caused by plugin scripts, it's difficult to debug with this message...

**Comment by matryer** [comment]
@leaanthony Do we think we know what was causing this?

**Comment by leaanthony** [comment]
No idea off the top of my head. If the app is still running then it would seem to me like context cancel is being called and the command killed.

**Comment by Cueball** [comment]
I get this *regularly* with my (changed-and-not-definitely-improved) Homebrew plugin. I'm also running 4 other plugins, which never have any issues. I can post the "WIP" plugin script if that's helpful.

I'd rewrite the plugin to be more robust in handling error conditions, but I'm not sure where the "signal: killed" is coming from - if there's a debug log somewhere for each plugin that I can read, that'd be great (I'm sure I looked in the doco ages ago for that but didn't see anything relevant then; I'll re-explore the doco when I get a spare moment this evening.)

**Comment by darylzz** [comment]
> I get this _regularly_ with my (changed-and-not-definitely-improved) Homebrew plugin. I'm also running 4 other plugins, which never have any issues. I can post the "WIP" plugin script if that's helpful.
> 
> I'd rewrite the plugin to be more robust in handling error conditions, but I'm not sure where the "signal: killed" is coming from - if there's a debug log somewhere for each plugin that I can read, that'd be great (I'm sure I looked in the doco ages ago for that but didn't see anything relevant then; I'll re-explore the doco when I get a spare moment this evening.)

Which language are you using in your Homebrew plugin? Any modules are you using in it?

**Comment by Cueball** [comment]
Plugin is currently written as a shell script; I think the original is a bash script and so I haven't altered the shebang from `/bin/bash` - but I don't think it's using any particular bashisms. Nothing fancy about it.

I noticed it was still using the `bash=` style rather than `shell=` so I fixed that just now; will post if that seems to make any difference (I don't expect it to tho'.)

TBC I'd planned to eventually rewrite it in Ruby and maybe publish that version, so I'd rather put more effort into the Ruby version than fix this one.

**Comment by zessx** [comment]
Try to use `response = requests.get(request_url, timeout=1)`, it seems `requests` it trying IPv6 first and if you don't specify a timeout your script will fail *before* IPv4 was tried.

**Comment by alisterburt** [comment]
Thanks @zessx - will try that!

**Comment by matryer** [comment]
@alisterburt did @zessx's approach work?

**Comment by alisterburt** [comment]
@matryer - no errors so far but they were very intermittent anyway, will report back if it crops up again! 🙂

**Comment by TiagoRibeiroCA** [comment]
I don't know if this ship has sailed already but, @matryer any chance the timeout could be increased to 3 or 4 mins? I have a gitlab MR fetcher, but I'm fetching hundreds of groups, each with several hundred projects/repos, with dozens of MR's each, so I get the signal:killed error, although it works like a charm via terminal

**Comment by leaanthony** [comment]
I thin kit might be possible to add a config for this, but it would affect all plugins.

**Comment by TiagoRibeiroCA** [comment]
I consider 3 or 4 mins very acceptable. But ideally there would be a way to override this so anyone would use their desired timeout. Because on my specific case, 2 mins is just impossible, even using cache, the first request has to scan thousands of projects and MRs under them /:
