### ISSUE TITLE
Literally crashing like all the time

### ISSUE THREAD

**Issue by akharrou** [matryer/xbar#746]
Crashes when you refresh, crashes when you change name of script, crashes when you make something clickable and click on it, crashes on `shell=...` script launches, and when it doesn't crash, well they just don't work ... what's up with this thing ?!?

**Comment by matryer** [comment]
Hey @akharrou thanks for your feedback. The project is still in beta and the tech is still being firmed up. We expect to have these creases ironed out soon. If you have any specific reproducible steps to recreate a crash, please let us know. Meanwhile, keep getting the updates, it's getting better all the time.
