### ISSUE TITLE
Questions about editing/reloading scripts

### ISSUE THREAD

**Issue by tandpfun** [matryer/xbar#758]
Hi all!
I'm working on a plugin, and I had a couple questions. 
My plugin has a login system and I don't want to reload it too often, so the following questions are about that.

- Is there a way to edit/replace a line?
- Is there a way to reload the script without user input, for example to reload it at a certain time each day.

Thank you!

**Comment by tandpfun** [comment]
Ah, I guess this wouldn't be possible since the script has to finish running to display.

**Comment by matryer** [comment]
@tandpfun We have a streaming plugin option in the works, but it's not ready yet. Meanwhile, people do clever things by making their script create little files to keep track of state etc. Maybe that'll help you?
