### ISSUE TITLE
Can I still use BitBar?

### ISSUE THREAD

**Issue by lswainemoore** [matryer/xbar#760]
Apologies if this is covered somewhere--I read the README and the [website](https://xbarapp.com/), but I might've missed the answer. 

I'm a former user of BitBar looking to get going again on a new laptop, but I'm unsure what the story behind the change of name is, and whether BitBar is still functional. I gather from the README there has been a rewrite in Go, but I'm not sure what the motivation was.

The main reason I'm asking this is that I'd like to use the `terminal=true` functionality as discussed in [this thread](https://github.com/matryer/xbar/issues/680), but I gather that's not working yet in xbar. Not trying to rush you all on that--understand that there may be many wrinkles to that sort of thing. But I am curious whether I could get away with running BitBar for the time being, and it's hard to evaluate whether that's a bad idea without knowing the reasons behind the rewrite and name change.

My 2 cents: it might be worth including a line or two of context on the differences between xbar and BitBar from a user perspective in the README or on the website.

Thanks in advance for any help, and thanks for creating such a wonderful and flexible product.

**Comment by matryer** [comment]
@lswainemoore You can still use BitBar here: https://github.com/matryer/xbar/releases/tag/v2.0.4.beta

Good idea re the README, thanks.
