### ISSUE TITLE
Commuter API not usable with German locale

### ISSUE THREAD

**Issue by elchead** [matryer/xbar#765]
I think it should be mentioned that its a python2 script which is deprecated. Hence it was not so straightforward to install the missing dependency (simplejson).

Also the script cannot process German Umlaute in the response JSON and can thus not be used in Germany. 
It would be nice to mention the install steps also as a comment at the top:

1. Install simplejson dependency and use python2
2. Create 'origin.txt' and 'dest.txt' in commute_folder
3. Add API key

**Comment by matryer** [comment]
Hey @elchead, I think this might fall outside of the scope of xbar. Or do you think there's something xbar can do to help?

**Comment by elchead** [comment]
Yes, I agree, but since they are officially supported in this repo, it would be nice to have these caveats documented.

I will close the issue :)
