### ISSUE TITLE
Replace broken readme anchor with working link

### ISSUE THREAD

**Issue by josephschito** [matryer/xbar#785]
[This anchor (#writing-plugins)](https://github.com/matryer/xbar/blob/1410be750e94d29f1a10079ad2d47c28dd625b20/README.md?plain=1#L33) is broken, I suggest to replace it with `https://github.com/matryer/xbar-plugins/blob/main/CONTRIBUTING.md`

Screenshot ↓
<img width="529" alt="Screenshot 2021-10-25 at 15 46 07" src="https://user-images.githubusercontent.com/4095923/138707539-86145d06-c18f-4588-a9bb-129ea0f49e84.png">

**Comment by matryer** [comment]
I think this is fixed now. Thanks for reporting it @josephschito.
