### ISSUE TITLE
Background colors from bitbar plugins do not work

### ISSUE THREAD

**Issue by ahmetb** [matryer/xbar#792]
v2.1.7-beta

Repro: https://xbarapp.com/docs/plugins/Dev/Tutorial/ansi.sh.html

renders as 
![image](https://user-images.githubusercontent.com/159209/142263938-6826069a-b360-41a2-96f8-4d04511ae07e.png)

but it should render as
![image](https://user-images.githubusercontent.com/159209/142263882-712769ec-be17-4c0d-a562-a15e358c4c11.png)

another repro is at https://github.com/ahmetb/dotfiles/blob/master/bitbar-plugins/yahoo_stock_ticker.1m.py renders as

![image](https://user-images.githubusercontent.com/159209/142264068-4c4ec779-e13d-40f1-b003-27e11a28fb15.png)

whereas bitbar renders this as
![image](https://user-images.githubusercontent.com/159209/142264118-398747b3-c331-4f47-aee8-b4da692f0e87.png)

**Comment by ahmetb** [comment]
Any love for this issue? 😇

**Comment by leaanthony** [comment]
Thanks for the ping! Is there a one liner plugin that highlights this bug? Thanks

**Comment by ahmetb** [comment]
If you need a repro: https://github.com/ahmetb/dotfiles/blob/master/bitbar-plugins/yahoo_stock_ticker.1m.py

**Comment by leaanthony** [comment]
Thanks. This'll be the weekend now. It looks like a parse error so I'll need to create a test case out of this for https://github.com/leaanthony/go-ansi-parser

**Comment by leaanthony** [comment]
Partial fix: 
![image](https://user-images.githubusercontent.com/1943904/155830505-3917c552-29a4-4a02-87e9-b3a16aa0096b.png)

**Comment by leaanthony** [comment]
@ahmetb - after more looking at this, it seems bitbar didn't render it correctly anyway. `[40m` should be black, not grey. I'm also reading that `[1m` (bold) should be interpreted as "high intensity" so it would make the colours brighter. Running this script in a terminal seems to set it to intense colours by default, which is weird. 

I've fixed a small parse error which cleared it all up: 
![image](https://user-images.githubusercontent.com/1943904/155839030-2ac03303-197e-467f-957a-3d80299a074a.png)

I believe, based on what I'm reading in the standards, this is the correct output for those codes. If you disagree and have more insights, please let me know. Cheers.

**Comment by leaanthony** [comment]
Should also mention that the bitbar rendering of the yahoo finance plugin in this thread is also a bit off. The screenshot on the plugin page looks like there are no background colours:
https://xbarapp.com/docs/plugins/Finance/yahoo_stock_ticker.10m.py.html
