### ISSUE TITLE
Running locally wails error "dialog... does not contain package"

### ISSUE THREAD

**Issue by andymckay** [matryer/xbar#794]
The `README` in `app` says that to start the application locally:

`cd app && wails dev`

When I do that I get:

```
➜ wails dev        
Wails CLI v2.0.0-beta.21

Updating go.mod to use Wails 'v2.0.0-beta.21'
Executing: go mod tidy
go: finding module for package github.com/wailsapp/wails/v2/pkg/options/dialog
github.com/matryer/xbar/app imports
	github.com/wailsapp/wails/v2/pkg/options/dialog: module github.com/wailsapp/wails/v2@latest found (v2.0.0-beta.21), but does not contain package github.com/wailsapp/wails/v2/pkg/options/dialog

ERROR: exit status 1
```

It looks like there was a `wails` update to beta:

```
--- a/app/go.mod
+++ b/app/go.mod
@@ -18,7 +18,7 @@ require (
        github.com/peterbourgon/diskv v2.0.1+incompatible // indirect
        github.com/pierrec/lz4 v2.6.1+incompatible // indirect
        github.com/pkg/errors v0.9.1
-       github.com/wailsapp/wails/v2 v2.0.0-alpha.72
+       github.com/wailsapp/wails/v2 v2.0.0-beta.21
```

Thank you 🙇🏾

**Comment by leaanthony** [comment]
Hi there. It looks like your local version was updated somehow? The version that should be used is that specified in [go.mod](https://github.com/matryer/xbar/blob/main/app/go.mod). You should be able to install this by doing `go install github.com/wailsapp/wails@v2.0.0-alpha.72`. I've updated the readme to reflect this. Thanks for bringing it to our attention 👍

**Comment by andymckay** [comment]
Thanks @leaanthony sticking to that version works. 

```
➜ wails dev        
Wails CLI v2.0.0-beta.21

Updating go.mod to use Wails 'v2.0.0-beta.21'
Executing: go mod tidy
```

☝🏾 did the upgrade for me so 🤷🏾 anyways seems to be ok now. Thank you 🙇🏾
